/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_exception_d/@pdb_connector@sdb_sqlite.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_exception_d/@pdb_connector@sdb_sqlite.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_TStmt__9b689aPswhlvISciIt6vrswg tyObject_TStmt__9b689aPswhlvISciIt6vrswg;
typedef struct tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ;
typedef struct tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ;
typedef struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA tySequence__ObNb3ZkQVfF9aSBtrVROGjA;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content;
typedef struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef N_CDECL_PTR(int, tyProc__yfHoRdzkeuOFFD5YR67x8w) (tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* db_p0, NCSTRING zSql_p1, int nByte_p2, tyObject_TStmt__9b689aPswhlvISciIt6vrswg** ppStmt_p3, NCSTRING* pzTail_p4);
typedef N_CDECL_PTR(NI32, tyProc__qewvwIMSKE9bTykkFRxF5lw) (tyObject_TStmt__9b689aPswhlvISciIt6vrswg* PStmt_p0);
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA {
  NI len; tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__ObNb3ZkQVfF9aSBtrVROGjA trace;
	Exception* up;
};
struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A {
	Exception Sup;
};
struct tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ {
	tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A Sup;
};
struct tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ {
	tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ Sup;
};
typedef N_CDECL_PTR(NCSTRING, tyProc__iWZ78Y8r9bDIEUfo9bjfTQ2g) (tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* para1_p0);
typedef N_CDECL_PTR(NI32, tyProc__d29b1HrYVYl4Re1sFfapGOQ) (tyObject_TStmt__9b689aPswhlvISciIt6vrswg* para1_p0, NI32 para2_p1);
typedef N_CDECL_PTR(NI32, tyProc__9cVQ1imSHqUK6MAKf8NL79cw) (tyObject_TStmt__9b689aPswhlvISciIt6vrswg* para1_p0, NI32 para2_p1, NI64 para3_p2);
typedef N_CDECL_PTR(NI32, tyProc__GyIu9cU7oaqPHANgMM1bHTg) (tyObject_TStmt__9b689aPswhlvISciIt6vrswg* para1_p0, NI32 para2_p1, NF para3_p2);
typedef N_CDECL_PTR(void, tyProc__32w2ZypAyMWuajvi2Jt79cg) (void* para1_p0);
typedef N_CDECL_PTR(NI32, tyProc__GgqOXj9aHaca7DZiYYSogIg) (tyObject_TStmt__9b689aPswhlvISciIt6vrswg* para1_p0, NI32 para2_p1, NCSTRING para3_p2, NI32 n_p3, tyProc__32w2ZypAyMWuajvi2Jt79cg para5_p4);
typedef N_CDECL_PTR(NI32, tyProc__kQNlH835yVeUWzqpTWVDfA) (tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* para1_p0);
typedef N_CDECL_PTR(NI32, tyProc__1qLMpOrx00Gg5jU7zh1rfg) (NCSTRING filename_p0, tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw** ppDb_p1);
struct tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw {
	char dummy;
};
struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content { NI cap; tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g data[SEQ_DECL_SIZE]; };
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(void, dbError__pkgZdb95connectorZdb95sqlite_u67)(tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* db_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pkgZdb95connectorZdb95common_u79)(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2698)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
static N_INLINE(void, nimMarkCyclic)(void* p_p0);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___pkgZdb95connectorZdb95common_u76)(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ** dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, bindParam__pkgZdb95connectorZdb95sqlite_u22)(tyObject_TStmt__9b689aPswhlvISciIt6vrswg* ps_p0, NI paramIdx_p1, NI64 val_p2);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
extern TNimTypeV2 NTIv2__ZTUKfBXNbIdOgGwPXsX9a9cQ_;
static const struct {
  NI cap; NIM_CHAR data[32+1];
} TM__heBtp2LeWBx5KdnYQwGVCA_2 = { 32 | NIM_STRLIT_FLAG, "error binding param in position " };
static const NimStringV2 TM__heBtp2LeWBx5KdnYQwGVCA_3 = {32, (NimStrPayload*)&TM__heBtp2LeWBx5KdnYQwGVCA_2};
static const NimStringV2 TM__heBtp2LeWBx5KdnYQwGVCA_5 = {32, (NimStrPayload*)&TM__heBtp2LeWBx5KdnYQwGVCA_2};
static const NimStringV2 TM__heBtp2LeWBx5KdnYQwGVCA_6 = {32, (NimStrPayload*)&TM__heBtp2LeWBx5KdnYQwGVCA_2};
static const NimStringV2 TM__heBtp2LeWBx5KdnYQwGVCA_7 = {32, (NimStrPayload*)&TM__heBtp2LeWBx5KdnYQwGVCA_2};
static const struct {
  NI cap; NIM_CHAR data[159+1];
} TM__heBtp2LeWBx5KdnYQwGVCA_8 = { 159 | NIM_STRLIT_FLAG, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim(322, 9) `not db.isNil` Database not connected." };
static const NimStringV2 TM__heBtp2LeWBx5KdnYQwGVCA_9 = {159, (NimStrPayload*)&TM__heBtp2LeWBx5KdnYQwGVCA_8};
extern tyProc__yfHoRdzkeuOFFD5YR67x8w Dl_4177527014_;
extern tyProc__qewvwIMSKE9bTykkFRxF5lw Dl_4177527135_;
extern tyProc__iWZ78Y8r9bDIEUfo9bjfTQ2g Dl_4177527004_;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
extern tyProc__d29b1HrYVYl4Re1sFfapGOQ Dl_4177527044_;
extern tyProc__9cVQ1imSHqUK6MAKf8NL79cw Dl_4177527040_;
extern tyProc__GyIu9cU7oaqPHANgMM1bHTg Dl_4177527032_;
extern tyProc__GgqOXj9aHaca7DZiYYSogIg Dl_4177527047_;
extern tyProc__kQNlH835yVeUWzqpTWVDfA Dl_4177526918_;
extern tyProc__1qLMpOrx00Gg5jU7zh1rfg Dl_4177526996_;
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
static N_INLINE(void, nimMarkCyclic)(void* p_p0) {
	nimfr_("nimMarkCyclic", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/orc.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, dbError__pkgZdb95connectorZdb95sqlite_u67)(tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* db_p0) {
	tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* e_1;
	NCSTRING T2_;
	NimStringV2 T3_;
	tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* blitTmp_1;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("dbError", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	e_1 = NIM_NIL;
	nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");	eqdestroy___pkgZdb95connectorZdb95common_u79(e_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(209, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	e_1 = (tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ*) nimNewObj(sizeof(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ), NIM_ALIGNOF(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ));
	(*e_1).Sup.Sup.Sup.Sup.m_type = (&NTIv2__ZTUKfBXNbIdOgGwPXsX9a9cQ_);
	(*e_1).Sup.Sup.Sup.name = "DbError";
	nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	nimlf_(210, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	T2_ = (NCSTRING)0;
	T2_ = Dl_4177527004_(db_p0);
	T3_.len = 0; T3_.p = NIM_NIL;
	T3_ = cstrToNimstr(T2_);
	nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	eqsink___system_u2698((&(*e_1).Sup.Sup.Sup.message), T3_);
	nimlf_(211, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	blitTmp_1 = e_1;
	nimMarkCyclic(e_1);
	nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");	eqwasMoved___pkgZdb95connectorZdb95common_u76(&e_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(211, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	raiseExceptionEx((Exception*)blitTmp_1, "DbError", "dbError", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim", 211);
goto LA1_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqdestroy___pkgZdb95connectorZdb95common_u79(e_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TStmt__9b689aPswhlvISciIt6vrswg*, prepare__pkgZdb95connectorZdb95sqlite_u117)(tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* db_p0, NimStringV2 q_p1) {
	tyObject_TStmt__9b689aPswhlvISciIt6vrswg* result;
NIM_BOOL* nimErr_;
	nimfr_("prepare", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_TStmt__9b689aPswhlvISciIt6vrswg*)0;
	nimlf_(231, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	{
		int T3_;
		NI32 T6_;
		if ((q_p1.len) < ((int)(-2147483647 -1)) || (q_p1.len) > ((int)2147483647)){ raiseRangeErrorI(q_p1.len, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
		}
		T3_ = (int)0;
		T3_ = Dl_4177527014_(db_p0, nimToCStringConv(q_p1), ((int) (q_p1.len)), &result, ((NCSTRING*) NIM_NIL));
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		nimln_(232);		T6_ = (NI32)0;
		T6_ = Dl_4177527135_(result);
		(void)(T6_);
		nimln_(233);		dbError__pkgZdb95connectorZdb95sqlite_u67(db_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__heBtp2LeWBx5KdnYQwGVCA_4;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__heBtp2LeWBx5KdnYQwGVCA_4)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__heBtp2LeWBx5KdnYQwGVCA_4);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, bindNull__pkgZdb95connectorZdb95sqlite_u46)(tyObject_TStmt__9b689aPswhlvISciIt6vrswg* ps_p0, NI paramIdx_p1) {
NIM_BOOL oldNimErrFin6_;
NIM_BOOL* nimErr_;
	nimfr_("bindNull", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	nimln_(854);	{
		NI32 T3_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* eX60gensym81__1;
		NimStringV2 colontmpD_;
		NimStringV2 T7_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* blitTmp_1;
		if ((paramIdx_p1) < ((NI32)(-2147483647 -1)) || (paramIdx_p1) > ((NI32)2147483647)){ raiseRangeErrorI(paramIdx_p1, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
		}
		T3_ = (NI32)0;
		T3_ = Dl_4177527044_(ps_p0, ((NI32) (paramIdx_p1)));
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		eX60gensym81__1 = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym81__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimlf_(825, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		eX60gensym81__1 = (tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ*) nimNewObj(sizeof(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ), NIM_ALIGNOF(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ));
		(*eX60gensym81__1).Sup.Sup.Sup.Sup.m_type = (&NTIv2__ZTUKfBXNbIdOgGwPXsX9a9cQ_);
		(*eX60gensym81__1).Sup.Sup.Sup.name = "DbError";
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(826, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u14(paramIdx_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T7_ = rawNewString(colontmpD_.len + 32);
appendString((&T7_), TM__heBtp2LeWBx5KdnYQwGVCA_3);
appendString((&T7_), colontmpD_);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&(*eX60gensym81__1).Sup.Sup.Sup.message), T7_);
		nimlf_(855, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		blitTmp_1 = eX60gensym81__1;
		nimMarkCyclic(eX60gensym81__1);
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqwasMoved___pkgZdb95connectorZdb95common_u76(&eX60gensym81__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimlf_(855, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		raiseExceptionEx((Exception*)blitTmp_1, "DbError", "bindNull", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim", 855);
goto LA6_;
		{
			LA6_:;
		}
		{
			oldNimErrFin6_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");			eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym81__1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin6_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, bindParam__pkgZdb95connectorZdb95sqlite_u22)(tyObject_TStmt__9b689aPswhlvISciIt6vrswg* ps_p0, NI paramIdx_p1, NI64 val_p2) {
NIM_BOOL oldNimErrFin6_;
NIM_BOOL* nimErr_;
	nimfr_("bindParam", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(836, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	{
		NI32 T3_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* eX60gensym71__1;
		NimStringV2 colontmpD_;
		NimStringV2 T7_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* blitTmp_1;
		if ((paramIdx_p1) < ((NI32)(-2147483647 -1)) || (paramIdx_p1) > ((NI32)2147483647)){ raiseRangeErrorI(paramIdx_p1, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
		}
		T3_ = (NI32)0;
		T3_ = Dl_4177527040_(ps_p0, ((NI32) (paramIdx_p1)), val_p2);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		eX60gensym71__1 = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym71__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimlf_(825, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		eX60gensym71__1 = (tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ*) nimNewObj(sizeof(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ), NIM_ALIGNOF(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ));
		(*eX60gensym71__1).Sup.Sup.Sup.Sup.m_type = (&NTIv2__ZTUKfBXNbIdOgGwPXsX9a9cQ_);
		(*eX60gensym71__1).Sup.Sup.Sup.name = "DbError";
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(826, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u14(paramIdx_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T7_ = rawNewString(colontmpD_.len + 32);
appendString((&T7_), TM__heBtp2LeWBx5KdnYQwGVCA_5);
appendString((&T7_), colontmpD_);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&(*eX60gensym71__1).Sup.Sup.Sup.message), T7_);
		nimlf_(837, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		blitTmp_1 = eX60gensym71__1;
		nimMarkCyclic(eX60gensym71__1);
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqwasMoved___pkgZdb95connectorZdb95common_u76(&eX60gensym71__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimlf_(837, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		raiseExceptionEx((Exception*)blitTmp_1, "DbError", "bindParam", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim", 837);
goto LA6_;
		{
			LA6_:;
		}
		{
			oldNimErrFin6_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");			eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym71__1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin6_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, bindParam__pkgZdb95connectorZdb95sqlite_u30)(tyObject_TStmt__9b689aPswhlvISciIt6vrswg* ps_p0, NI paramIdx_p1, NI val_p2) {
NIM_BOOL* nimErr_;
	nimfr_("bindParam", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(842, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	bindParam__pkgZdb95connectorZdb95sqlite_u22(ps_p0, paramIdx_p1, ((NI64) (val_p2)));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, bindParam__pkgZdb95connectorZdb95sqlite_u38)(tyObject_TStmt__9b689aPswhlvISciIt6vrswg* ps_p0, NI paramIdx_p1, NF val_p2) {
NIM_BOOL oldNimErrFin6_;
NIM_BOOL* nimErr_;
	nimfr_("bindParam", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	nimln_(848);	{
		NI32 T3_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* eX60gensym77__1;
		NimStringV2 colontmpD_;
		NimStringV2 T7_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* blitTmp_1;
		if ((paramIdx_p1) < ((NI32)(-2147483647 -1)) || (paramIdx_p1) > ((NI32)2147483647)){ raiseRangeErrorI(paramIdx_p1, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
		}
		T3_ = (NI32)0;
		T3_ = Dl_4177527032_(ps_p0, ((NI32) (paramIdx_p1)), val_p2);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		eX60gensym77__1 = NIM_NIL;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym77__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimlf_(825, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		eX60gensym77__1 = (tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ*) nimNewObj(sizeof(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ), NIM_ALIGNOF(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ));
		(*eX60gensym77__1).Sup.Sup.Sup.Sup.m_type = (&NTIv2__ZTUKfBXNbIdOgGwPXsX9a9cQ_);
		(*eX60gensym77__1).Sup.Sup.Sup.name = "DbError";
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(826, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		T7_.len = 0; T7_.p = NIM_NIL;
		colontmpD_ = dollar___systemZdollars_u14(paramIdx_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		T7_ = rawNewString(colontmpD_.len + 32);
appendString((&T7_), TM__heBtp2LeWBx5KdnYQwGVCA_6);
appendString((&T7_), colontmpD_);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&(*eX60gensym77__1).Sup.Sup.Sup.message), T7_);
		nimlf_(849, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		blitTmp_1 = eX60gensym77__1;
		nimMarkCyclic(eX60gensym77__1);
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqwasMoved___pkgZdb95connectorZdb95common_u76(&eX60gensym77__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA6_;
		nimlf_(849, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		raiseExceptionEx((Exception*)blitTmp_1, "DbError", "bindParam", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim", 849);
goto LA6_;
		{
			LA6_:;
		}
		{
			oldNimErrFin6_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
			nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");			eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym77__1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin6_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, bindParam__pkgZdb95connectorZdb95sqlite_u53)(tyObject_TStmt__9b689aPswhlvISciIt6vrswg* ps_p0, NI paramIdx_p1, NimStringV2 val_p2, NIM_BOOL copy_p3) {
	tyProc__32w2ZypAyMWuajvi2Jt79cg colontmpD_;
	tyProc__32w2ZypAyMWuajvi2Jt79cg colontmpD__2;
NIM_BOOL oldNimErrFin12_;
NIM_BOOL* nimErr_;
	nimfr_("bindParam", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_ = (tyProc__32w2ZypAyMWuajvi2Jt79cg)0;
	colontmpD__2 = (tyProc__32w2ZypAyMWuajvi2Jt79cg)0;
	nimlf_(860, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	{
		tyProc__32w2ZypAyMWuajvi2Jt79cg T3_;
		NI32 T9_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* eX60gensym85__1;
		NimStringV2 colontmpD__3;
		NimStringV2 T13_;
		tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ* blitTmp_1;
		if ((paramIdx_p1) < ((NI32)(-2147483647 -1)) || (paramIdx_p1) > ((NI32)2147483647)){ raiseRangeErrorI(paramIdx_p1, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
		}
		if ((val_p2.len) < ((NI32)(-2147483647 -1)) || (val_p2.len) > ((NI32)2147483647)){ raiseRangeErrorI(val_p2.len, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
		}
		T3_ = (tyProc__32w2ZypAyMWuajvi2Jt79cg)0;
		{
			if (!copy_p3) goto LA6_;
			colontmpD_ = ((tyProc__32w2ZypAyMWuajvi2Jt79cg)-1);
			T3_ = colontmpD_;
		}
		goto LA4_;
LA6_: ;
		{
			colontmpD__2 = NIM_NIL;
			T3_ = colontmpD__2;
		}
LA4_: ;
		T9_ = (NI32)0;
		T9_ = Dl_4177527047_(ps_p0, ((NI32) (paramIdx_p1)), nimToCStringConv(val_p2), ((NI32) (val_p2.len)), T3_);
		if (!!((T9_ == ((NI32)0)))) goto LA10_;
		eX60gensym85__1 = NIM_NIL;
		colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym85__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
		nimlf_(825, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		eX60gensym85__1 = (tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ*) nimNewObj(sizeof(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ), NIM_ALIGNOF(tyObject_DbError__ZTUKfBXNbIdOgGwPXsX9a9cQ));
		(*eX60gensym85__1).Sup.Sup.Sup.Sup.m_type = (&NTIv2__ZTUKfBXNbIdOgGwPXsX9a9cQ_);
		(*eX60gensym85__1).Sup.Sup.Sup.name = "DbError";
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(826, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		T13_.len = 0; T13_.p = NIM_NIL;
		colontmpD__3 = dollar___systemZdollars_u14(paramIdx_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
		T13_ = rawNewString(colontmpD__3.len + 32);
appendString((&T13_), TM__heBtp2LeWBx5KdnYQwGVCA_7);
appendString((&T13_), colontmpD__3);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&(*eX60gensym85__1).Sup.Sup.Sup.message), T13_);
		nimlf_(861, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		blitTmp_1 = eX60gensym85__1;
		nimMarkCyclic(eX60gensym85__1);
		nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");		eqwasMoved___pkgZdb95connectorZdb95common_u76(&eX60gensym85__1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA12_;
		nimlf_(861, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");		raiseExceptionEx((Exception*)blitTmp_1, "DbError", "bindParam", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim", 861);
goto LA12_;
		{
			LA12_:;
		}
		{
			oldNimErrFin12_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			nimlf_(99, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_common.nim");			eqdestroy___pkgZdb95connectorZdb95common_u79(eX60gensym85__1);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			*nimErr_ = oldNimErrFin12_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA10_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_TStmt__9b689aPswhlvISciIt6vrswg*, setupQuery__pkgZdb95connectorZdb95sqlite_u299)(tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* db_p0, tyObject_TStmt__9b689aPswhlvISciIt6vrswg* stmtName_p1) {
	tyObject_TStmt__9b689aPswhlvISciIt6vrswg* result;
NIM_BOOL* nimErr_;
	nimfr_("setupQuery", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_TStmt__9b689aPswhlvISciIt6vrswg*)0;
	nimlf_(322, "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");	{
		if (!!(!((db_p0 == 0)))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__heBtp2LeWBx5KdnYQwGVCA_9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(323);	result = stmtName_p1;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pkgZdb95connectorZdb95sqlite_u658)(tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* db_p0) {
NIM_BOOL* nimErr_;
	nimfr_("close", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	nimln_(782);	{
		NI32 T3_;
		T3_ = (NI32)0;
		T3_ = Dl_4177526918_(db_p0);
		if (!!((T3_ == ((NI32)0)))) goto LA4_;
		dbError__pkgZdb95connectorZdb95sqlite_u67(db_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw*, open__pkgZdb95connectorZdb95sqlite_u660)(NimStringV2 connection_p0, NimStringV2 user_p1, NimStringV2 password_p2, NimStringV2 database_p3) {
	tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* result;
	tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw* db_1;
NIM_BOOL* nimErr_;
	nimfr_("open", "/Users/gcao/.nimble/pkgs2/db_connector-0.1.0-b20053975976f94afac253d67cc6ef9200b32d02/db_connector/db_sqlite.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw*)0;
	db_1 = (tyObject_Sqlite3__tsecoeaimnHdwycu3ZRtzw*)0;
	nimln_(802);	{
		NI32 T3_;
		T3_ = (NI32)0;
		T3_ = Dl_4177526996_(nimToCStringConv(connection_p0), &db_1);
		if (!(T3_ == ((NI32)0))) goto LA4_;
		nimln_(803);		result = db_1;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(805);		dbError__pkgZdb95connectorZdb95sqlite_u67(db_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
