/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_exception_d/@pstd@stypedthreads.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_exception_d/@pstd@stypedthreads.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/types.h>
#include <stdlib.h>
#include <string.h>
#define _GNU_SOURCE
#include <pthread.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef struct tyObject_Thread__KGbP4zYJQNEX4xIA9aeYxoQ tyObject_Thread__KGbP4zYJQNEX4xIA9aeYxoQ;
typedef struct tyObject_GcThread__DBgab9ao9cfqoEWa29aXHW22Q tyObject_GcThread__DBgab9ao9cfqoEWa29aXHW22Q;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_ResourceExhaustedError__t41hElyLz8HFMpbLOFS9aUQ tyObject_ResourceExhaustedError__t41hElyLz8HFMpbLOFS9aUQ;
typedef struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA tySequence__ObNb3ZkQVfF9aSBtrVROGjA;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content;
typedef struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g;
typedef N_NIMCALL_PTR(void, tyProc__7sajhS09bWVSjKTAXjd4MaA) (NI arg_p0);
struct tyObject_GcThread__DBgab9ao9cfqoEWa29aXHW22Q {
	char dummy;
};
struct tyObject_Thread__KGbP4zYJQNEX4xIA9aeYxoQ {
	tyObject_GcThread__DBgab9ao9cfqoEWa29aXHW22Q* core;
	pthread_t sys;
	tyProc__7sajhS09bWVSjKTAXjd4MaA dataFn;
	NI data;
};
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA {
  NI len; tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__ObNb3ZkQVfF9aSBtrVROGjA trace;
	Exception* up;
};
struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A {
	Exception Sup;
};
struct tyObject_ResourceExhaustedError__t41hElyLz8HFMpbLOFS9aUQ {
	tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A Sup;
};
struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content { NI cap; tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void*, allocThreadStorage__stdZtypedthreads_u6)(NI size_p0);
static N_INLINE(void, zeroMem__system_u1738)(void* p_p0, NI size_p1);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NOCONV(void*, threadProcWrapper__OOZsrcZgeneZvm_u81501)(void* closure_p0);
N_LIB_PRIVATE N_NIMCALL(void, threadProcWrapStackFrame__OOZsrcZgeneZvm_u81514)(tyObject_Thread__KGbP4zYJQNEX4xIA9aeYxoQ* thrd_p0);
N_LIB_PRIVATE N_NIMCALL(void, deallocThreadStorage__system_u3924)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static const struct {
  NI cap; NIM_CHAR data[138+1];
} TM__Adpupye79bwOKmMMAmP7uoQ_2 = { 138 | NIM_STRLIT_FLAG, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/typedthreads.nim(273, 5) `pthread_attr_init(a) == 0` " };
static const NimStringV2 TM__Adpupye79bwOKmMMAmP7uoQ_3 = {138, (NimStrPayload*)&TM__Adpupye79bwOKmMMAmP7uoQ_2};
static const struct {
  NI cap; NIM_CHAR data[137+1];
} TM__Adpupye79bwOKmMMAmP7uoQ_4 = { 137 | NIM_STRLIT_FLAG, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/typedthreads.nim(285, 15) `setstacksizeResult == 0` " };
static const NimStringV2 TM__Adpupye79bwOKmMMAmP7uoQ_5 = {137, (NimStrPayload*)&TM__Adpupye79bwOKmMMAmP7uoQ_4};
extern TNimTypeV2 NTIv2__t41hElyLz8HFMpbLOFS9aUQ_;
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__Adpupye79bwOKmMMAmP7uoQ_6 = { 20 | NIM_STRLIT_FLAG, "cannot create thread" };
static const NimStringV2 TM__Adpupye79bwOKmMMAmP7uoQ_7 = {20, (NimStrPayload*)&TM__Adpupye79bwOKmMMAmP7uoQ_6};
static const struct {
  NI cap; NIM_CHAR data[141+1];
} TM__Adpupye79bwOKmMMAmP7uoQ_8 = { 141 | NIM_STRLIT_FLAG, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/typedthreads.nim(288, 5) `pthread_attr_destroy(a) == 0` " };
static const NimStringV2 TM__Adpupye79bwOKmMMAmP7uoQ_9 = {141, (NimStrPayload*)&TM__Adpupye79bwOKmMMAmP7uoQ_8};
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(void, zeroMem__system_u1738)(void* p_p0, NI size_p1) {
	nimZeroMem(p_p0, size_p1);
}
N_LIB_PRIVATE N_NIMCALL(void*, allocThreadStorage__stdZtypedthreads_u6)(NI size_p0) {
	void* result;
	result = malloc(((size_t) (size_p0)));
	zeroMem__system_u1738(result, (size_p0));
	return result;
}
N_LIB_PRIVATE N_NOCONV(void*, threadProcWrapper__OOZsrcZgeneZvm_u81501)(void* closure_p0) {
	void* result;
	tyObject_Thread__KGbP4zYJQNEX4xIA9aeYxoQ* thrdX60gensym0__1;
	tyObject_GcThread__DBgab9ao9cfqoEWa29aXHW22Q* coreX60gensym0__1;
	result = (void*)0;
	thrdX60gensym0__1 = ((tyObject_Thread__KGbP4zYJQNEX4xIA9aeYxoQ*) (closure_p0));
	coreX60gensym0__1 = (*thrdX60gensym0__1).core;
	threadProcWrapStackFrame__OOZsrcZgeneZvm_u81514(thrdX60gensym0__1);
	(*thrdX60gensym0__1).core = ((tyObject_GcThread__DBgab9ao9cfqoEWa29aXHW22Q*) NIM_NIL);
	(*thrdX60gensym0__1).dataFn = NIM_NIL;
	deallocThreadStorage__system_u3924(((void*) (coreX60gensym0__1)));
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, createThread__OOZsrcZgeneZvm_u81480)(tyObject_Thread__KGbP4zYJQNEX4xIA9aeYxoQ* t_p0, tyProc__7sajhS09bWVSjKTAXjd4MaA tp_p1, NI param_p2) {
	void* T1_;
	pthread_attr_t a_1;
	int setstacksizeResult_1;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	T1_ = (void*)0;
	T1_ = allocThreadStorage__stdZtypedthreads_u6(((NI)1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*t_p0).core = ((tyObject_GcThread__DBgab9ao9cfqoEWa29aXHW22Q*) (T1_));
	(*t_p0).data = param_p2;
	(*t_p0).dataFn = tp_p1;
	{
		int T4_;
		T4_ = (int)0;
		T4_ = pthread_attr_init((&a_1));
		if (!!((T4_ == ((NI32)0)))) goto LA5_;
		failedAssertImpl__stdZassertions_u234(TM__Adpupye79bwOKmMMAmP7uoQ_3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	setstacksizeResult_1 = pthread_attr_setstacksize((&a_1), ((NI)2093056));
	{
		if (!!((setstacksizeResult_1 == ((NI32)0)))) goto LA9_;
		failedAssertImpl__stdZassertions_u234(TM__Adpupye79bwOKmMMAmP7uoQ_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA9_: ;
	{
		int T13_;
		tyObject_ResourceExhaustedError__t41hElyLz8HFMpbLOFS9aUQ* T16_;
		T13_ = (int)0;
		T13_ = pthread_create((&(*t_p0).sys), (&a_1), threadProcWrapper__OOZsrcZgeneZvm_u81501, ((void*) (t_p0)));
		if (!!((T13_ == ((NI32)0)))) goto LA14_;
		T16_ = NIM_NIL;
		T16_ = (tyObject_ResourceExhaustedError__t41hElyLz8HFMpbLOFS9aUQ*) nimNewObj(sizeof(tyObject_ResourceExhaustedError__t41hElyLz8HFMpbLOFS9aUQ), NIM_ALIGNOF(tyObject_ResourceExhaustedError__t41hElyLz8HFMpbLOFS9aUQ));
		(*T16_).Sup.Sup.Sup.m_type = (&NTIv2__t41hElyLz8HFMpbLOFS9aUQ_);
		(*T16_).Sup.Sup.name = "ResourceExhaustedError";
		(*T16_).Sup.Sup.message = TM__Adpupye79bwOKmMMAmP7uoQ_7;
		(*T16_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T16_, "ResourceExhaustedError", "createThread", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/typedthreads.nim", 287);
goto BeforeRet_;
	}
LA14_: ;
	{
		int T19_;
		T19_ = (int)0;
		T19_ = pthread_attr_destroy((&a_1));
		if (!!((T19_ == ((NI32)0)))) goto LA20_;
		failedAssertImpl__stdZassertions_u234(TM__Adpupye79bwOKmMMAmP7uoQ_9);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA20_: ;
	}BeforeRet_: ;
}
