/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_repeat_d/@popenssl.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_repeat_d/@popenssl.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA;
typedef struct tyObject_OSError__x9ck23VzJ8bnTp3i9ao1ILxg tyObject_OSError__x9ck23VzJ8bnTp3i9ao1ILxg;
typedef struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA tySequence__ObNb3ZkQVfF9aSBtrVROGjA;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content;
typedef struct tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA;
typedef struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA {
  NI len; tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__ObNb3ZkQVfF9aSBtrVROGjA trace;
	Exception* up;
};
struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A {
	Exception Sup;
};
struct tyObject_OSError__x9ck23VzJ8bnTp3i9ao1ILxg {
	tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A Sup;
	NI32 errorCode;
};
struct tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA {
	tyObject_OSError__x9ck23VzJ8bnTp3i9ao1ILxg Sup;
};
typedef N_CDECL_PTR(int, tyProc__bj29cdE9aA9bshc5NUghhGaWw) (NU64 opts_p0, NU8 settings_p1);
typedef N_CDECL_PTR(int, tyProc__u0PsAQN5ndneEiWxnCoc9aw) (void);
typedef N_CDECL_PTR(void, tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (void);
struct tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA {
	char dummy;
};
typedef N_CDECL_PTR(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*, tyProc__Cz2KMMgCPPHsvY9c9b9cXbFBA) (void);
typedef N_CDECL_PTR(unsigned long, tyProc__Zp8a7gsqfDHPKe06nErJjg) (void);
typedef N_CDECL_PTR(NCSTRING, tyProc__HE9clvqwtdfVXvgz4Z0y1cw) (unsigned long e_p0, NCSTRING buf_p1);
typedef N_CDECL_PTR(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*, tyProc__V1YoAVR9b32CnjlMDNOHmkw) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* meth_p0);
typedef N_CDECL_PTR(int, tyProc__w49b1ufNINSJzazRiRhQtbA) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* s_p0, NCSTRING ciphers_p1);
typedef N_CDECL_PTR(long, tyProc__9bSv2pr9a6oeWkMyFAxsf1zg) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ctx_p0, int cmd_p1, long larg_p2, void* parg_p3);
typedef N_CDECL_PTR(NI, tyProc__aF4y9aPKIi8D4VGrVvX011Q) (NI a_p0, void* b_p1);
typedef N_CDECL_PTR(void, tyProc__eOOMEwhtJsLXt2we9apmrgQ) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* s_p0, NI mode_p1, tyProc__aF4y9aPKIi8D4VGrVvX011Q cb_p2);
typedef N_STDCALL_PTR(int, tyProc__angjg9akd3OrGEmNAc0xjyA) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ctx_p0, NCSTRING filename_p1);
typedef N_CDECL_PTR(int, tyProc__yCpsgD8EFDFwclvguNymwg) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ctx_p0, NCSTRING filename_p1, int typ_p2);
typedef N_CDECL_PTR(int, tyProc__SIyAlzx60yQHC5CJGW8eYQ) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ctx_p0);
typedef N_CDECL_PTR(int, tyProc__iknj9brKiBlkSRnsYKwz66Q) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ctx_p0, NCSTRING CAfile_p1, NCSTRING CApath_p2);
typedef N_CDECL_PTR(int, tyProc__2GNd9aeBUJS68I9cHx7kf5xA) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* s_p0, int ret_code_p1);
typedef N_CDECL_PTR(void, tyProc__rr3BaCzA7aYoh5azGd4Qzg) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0);
typedef N_CDECL_PTR(int, tyProc__5ItwbcHVPMStFNhHhLmxcA) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0, NCSTRING buf_p1, NI num_p2);
typedef N_CDECL_PTR(int, tyProc__Uo9aWMHbHftNNUOXOIAcLaQ) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0, void* buf_p1, NI num_p2);
typedef N_CDECL_PTR(NI, tyProc__0QD0nkDJsgcrQHiHPUHLbw) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0, int cmd_p1, NI larg_p2, void* parg_p3);
typedef N_CDECL_PTR(int, tyProc__Ze9amU3gB2IEcZQRlDt7zSA) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* cert_p0, NCSTRING name_p1, int namelen_p2, unsigned int flags_p3, NCSTRING peername_p4);
typedef N_CDECL_PTR(void, tyProc__JAAuSRLipD6PR9bvYzrAQrA) (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0, int mode_p1);
struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content { NI cap; tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g data[SEQ_DECL_SIZE]; };
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_u193)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_u187)(void* dll_p0, NimStringV2 name_p1, NimStringV2 alternativeName_p2);
N_LIB_PRIVATE N_NIMCALL(void*, symAddr__pureZdynlib_u74)(void* lib_p0, NCSTRING name_p1);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
static N_INLINE(void*, thisModule__wrappersZopenssl_u177)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLib__pureZdynlib_u6)(void);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void*, sslModule__wrappersZopenssl_u180)(void);
N_LIB_PRIVATE N_NIMCALL(void*, loadLibPattern__pureZdynlib_u93)(NimStringV2 pattern_p0, NIM_BOOL globalSymbols_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseDefect)(void);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
static N_INLINE(void, popCurrentException)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___stdZtypedthreads_u223)(Exception** dest_p0, Exception* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_u197)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseInvalidLibrary__pureZdynlib_u9)(NCSTRING name_p0);
static N_INLINE(void*, utilModule__wrappersZopenssl_u184)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*, loadPSSLMethod__wrappersZopenssl_u205)(NimStringV2 method1_p0, NimStringV2 method2_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimLoadLibrary)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimLoadLibraryError)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimGetProcAddr)(void* lib_p0, NCSTRING name_p1);
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_u201)(NimStringV2 name_p0, NimStringV2 alternativeName_p1);
static const struct {
  NI cap; NIM_CHAR data[97+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_2 = { 97 | NIM_STRLIT_FLAG, "libssl(.3|.1.1|.38|.39|.41|.43|.44|.45|.46|.47|.48|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|).dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_3 = {97, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_2};
extern TNimTypeV2 NTIv2__DKnljQcDlAtSw8QuzXy6MA_;
static const struct {
  NI cap; NIM_CHAR data[122+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_4 = { 122 | NIM_STRLIT_FLAG, "Could not load SSL using libssl(.3|.1.1|.38|.39|.41|.43|.44|.45|.46|.47|.48|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|).dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_5 = {122, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_4};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_6 = { 16 | NIM_STRLIT_FLAG, "OPENSSL_init_ssl" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_7 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_6};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_8 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_9 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_10 = { 16 | NIM_STRLIT_FLAG, "SSL_library_init" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_11 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_10};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_12 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[22+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_13 = { 22 | NIM_STRLIT_FLAG, "SSL_load_error_strings" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_14 = {22, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_13};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_15 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[100+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_16 = { 100 | NIM_STRLIT_FLAG, "libcrypto(.3|.1.1|.38|.39|.41|.43|.44|.45|.46|.47|.48|.10|.1.0.2|.1.0.1|.1.0.0|.0.9.9|.0.9.8|).dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_17 = {100, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_16};
static const struct {
  NI cap; NIM_CHAR data[20+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_18 = { 20 | NIM_STRLIT_FLAG, "ERR_load_BIO_strings" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_19 = {20, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_18};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_20 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[31+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_21 = { 31 | NIM_STRLIT_FLAG, "OPENSSL_add_all_algorithms_conf" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_22 = {31, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_21};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_23 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_24 = { 15 | NIM_STRLIT_FLAG, "Could not load " };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_25 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_24};
static const struct {
  NI cap; NIM_CHAR data[5+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_27 = { 5 | NIM_STRLIT_FLAG, " nor " };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_28 = {5, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_27};
static const struct {
  NI cap; NIM_CHAR data[10+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_29 = { 10 | NIM_STRLIT_FLAG, "TLS_method" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_30 = {10, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_29};
static const struct {
  NI cap; NIM_CHAR data[13+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_31 = { 13 | NIM_STRLIT_FLAG, "SSLv23_method" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_32 = {13, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_31};
static const struct {
  NI cap; NIM_CHAR data[17+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_35 = { 17 | NIM_STRLIT_FLAG, "libcrypto.3.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_36 = {17, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_35};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_38 = { 19 | NIM_STRLIT_FLAG, "libcrypto.1.1.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_39 = {19, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_38};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_41 = { 18 | NIM_STRLIT_FLAG, "libcrypto.38.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_42 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_41};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_44 = { 18 | NIM_STRLIT_FLAG, "libcrypto.39.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_45 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_44};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_47 = { 18 | NIM_STRLIT_FLAG, "libcrypto.41.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_48 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_47};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_50 = { 18 | NIM_STRLIT_FLAG, "libcrypto.43.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_51 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_50};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_53 = { 18 | NIM_STRLIT_FLAG, "libcrypto.44.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_54 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_53};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_56 = { 18 | NIM_STRLIT_FLAG, "libcrypto.45.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_57 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_56};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_59 = { 18 | NIM_STRLIT_FLAG, "libcrypto.46.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_60 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_59};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_62 = { 18 | NIM_STRLIT_FLAG, "libcrypto.47.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_63 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_62};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_65 = { 18 | NIM_STRLIT_FLAG, "libcrypto.48.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_66 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_65};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_68 = { 18 | NIM_STRLIT_FLAG, "libcrypto.10.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_69 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_68};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_71 = { 21 | NIM_STRLIT_FLAG, "libcrypto.1.0.2.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_72 = {21, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_71};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_74 = { 21 | NIM_STRLIT_FLAG, "libcrypto.1.0.1.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_75 = {21, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_74};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_77 = { 21 | NIM_STRLIT_FLAG, "libcrypto.1.0.0.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_78 = {21, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_77};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_80 = { 21 | NIM_STRLIT_FLAG, "libcrypto.0.9.9.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_81 = {21, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_80};
static const struct {
  NI cap; NIM_CHAR data[21+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_83 = { 21 | NIM_STRLIT_FLAG, "libcrypto.0.9.8.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_84 = {21, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_83};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_86 = { 15 | NIM_STRLIT_FLAG, "libcrypto.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_87 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_86};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_88 = {100, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_16};
static const struct {
  NI cap; NIM_CHAR data[14+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_95 = { 14 | NIM_STRLIT_FLAG, "libssl.3.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_96 = {14, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_95};
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_98 = { 16 | NIM_STRLIT_FLAG, "libssl.1.1.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_99 = {16, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_98};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_101 = { 15 | NIM_STRLIT_FLAG, "libssl.38.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_102 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_101};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_104 = { 15 | NIM_STRLIT_FLAG, "libssl.39.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_105 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_104};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_107 = { 15 | NIM_STRLIT_FLAG, "libssl.41.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_108 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_107};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_110 = { 15 | NIM_STRLIT_FLAG, "libssl.43.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_111 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_110};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_113 = { 15 | NIM_STRLIT_FLAG, "libssl.44.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_114 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_113};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_116 = { 15 | NIM_STRLIT_FLAG, "libssl.45.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_117 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_116};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_119 = { 15 | NIM_STRLIT_FLAG, "libssl.46.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_120 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_119};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_122 = { 15 | NIM_STRLIT_FLAG, "libssl.47.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_123 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_122};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_125 = { 15 | NIM_STRLIT_FLAG, "libssl.48.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_126 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_125};
static const struct {
  NI cap; NIM_CHAR data[15+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_128 = { 15 | NIM_STRLIT_FLAG, "libssl.10.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_129 = {15, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_128};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_131 = { 18 | NIM_STRLIT_FLAG, "libssl.1.0.2.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_132 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_131};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_134 = { 18 | NIM_STRLIT_FLAG, "libssl.1.0.1.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_135 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_134};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_137 = { 18 | NIM_STRLIT_FLAG, "libssl.1.0.0.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_138 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_137};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_140 = { 18 | NIM_STRLIT_FLAG, "libssl.0.9.9.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_141 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_140};
static const struct {
  NI cap; NIM_CHAR data[18+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_143 = { 18 | NIM_STRLIT_FLAG, "libssl.0.9.8.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_144 = {18, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_143};
static const struct {
  NI cap; NIM_CHAR data[12+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_146 = { 12 | NIM_STRLIT_FLAG, "libssl.dylib" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_147 = {12, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_146};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_148 = {97, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_2};
static const struct {
  NI cap; NIM_CHAR data[19+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_153 = { 19 | NIM_STRLIT_FLAG, "OpenSSL_version_num" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_154 = {19, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_153};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_155 = { 6 | NIM_STRLIT_FLAG, "SSLeay" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_156 = {6, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_155};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_157 = { 24 | NIM_STRLIT_FLAG, "SSL_CTX_set_ciphersuites" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_158 = {24, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_157};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_159 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[11+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_172 = { 11 | NIM_STRLIT_FLAG, "SSL_in_init" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_173 = {11, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_172};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_174 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_175 = { 9 | NIM_STRLIT_FLAG, "SSL_state" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_176 = {9, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_175};
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_177 = {0, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_8};
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_200 = { 24 | NIM_STRLIT_FLAG, "SSL_get_peer_certificate" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_201 = {24, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_200};
static const struct {
  NI cap; NIM_CHAR data[25+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_202 = { 25 | NIM_STRLIT_FLAG, "SSL_get1_peer_certificate" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_203 = {25, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_202};
static const struct {
  NI cap; NIM_CHAR data[68+1];
} TM__SLGpYVEqpFQ7VaPsJH6HIA_204 = { 68 | NIM_STRLIT_FLAG, "Could not load SSL_get_peer_certificate or SSL_get1_peer_certificate" };
static const NimStringV2 TM__SLGpYVEqpFQ7VaPsJH6HIA_205 = {68, (NimStrPayload*)&TM__SLGpYVEqpFQ7VaPsJH6HIA_204};
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
N_LIB_PRIVATE void* thisMod__wrappersZopenssl_u179;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
N_LIB_PRIVATE void* sslMod__wrappersZopenssl_u182;
extern NIM_THREADVAR Exception* currException__system_u4052;
N_LIB_PRIVATE void* utilMod__wrappersZopenssl_u186;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_33;
tyProc__Zp8a7gsqfDHPKe06nErJjg Dl_2080375386_;
tyProc__HE9clvqwtdfVXvgz4Z0y1cw Dl_2080375382_;
static void* TM__SLGpYVEqpFQ7VaPsJH6HIA_93;
tyProc__V1YoAVR9b32CnjlMDNOHmkw Dl_2080375273_;
tyProc__w49b1ufNINSJzazRiRhQtbA Dl_2080375290_;
N_LIB_PRIVATE tyProc__w49b1ufNINSJzazRiRhQtbA theProc__wrappersZopenssl_u451;
tyProc__9bSv2pr9a6oeWkMyFAxsf1zg Dl_2080375445_;
tyProc__eOOMEwhtJsLXt2we9apmrgQ Dl_2080375281_;
tyProc__angjg9akd3OrGEmNAc0xjyA Dl_2080375297_;
tyProc__yCpsgD8EFDFwclvguNymwg Dl_2080375300_;
tyProc__SIyAlzx60yQHC5CJGW8eYQ Dl_2080375304_;
tyProc__iknj9brKiBlkSRnsYKwz66Q Dl_2080375275_;
N_LIB_PRIVATE tyProc__SIyAlzx60yQHC5CJGW8eYQ theProc__wrappersZopenssl_u415;
N_LIB_PRIVATE tyProc__SIyAlzx60yQHC5CJGW8eYQ sslState__wrappersZopenssl_u418;
tyProc__ln4kdL5W9bbX4a1xl8nnVXQ Dl_2080375550_;
tyProc__SIyAlzx60yQHC5CJGW8eYQ Dl_2080375322_;
tyProc__2GNd9aeBUJS68I9cHx7kf5xA Dl_2080375339_;
tyProc__rr3BaCzA7aYoh5azGd4Qzg Dl_2080375260_;
tyProc__5ItwbcHVPMStFNhHhLmxcA Dl_2080375335_;
tyProc__Uo9aWMHbHftNNUOXOIAcLaQ Dl_2080375331_;
tyProc__SIyAlzx60yQHC5CJGW8eYQ Dl_2080375344_;
tyProc__V1YoAVR9b32CnjlMDNOHmkw Dl_2080375258_;
tyProc__2GNd9aeBUJS68I9cHx7kf5xA Dl_2080375319_;
tyProc__0QD0nkDJsgcrQHiHPUHLbw Dl_2080375458_;
tyProc__SIyAlzx60yQHC5CJGW8eYQ Dl_2080375329_;
tyProc__Ze9amU3gB2IEcZQRlDt7zSA Dl_2080375869_;
tyProc__rr3BaCzA7aYoh5azGd4Qzg Dl_2080375875_;
tyProc__SIyAlzx60yQHC5CJGW8eYQ Dl_2080375342_;
tyProc__yCpsgD8EFDFwclvguNymwg Dl_2080375540_;
tyProc__SIyAlzx60yQHC5CJGW8eYQ Dl_2080375518_;
tyProc__yCpsgD8EFDFwclvguNymwg Dl_2080375520_;
tyProc__yCpsgD8EFDFwclvguNymwg Dl_2080375524_;
tyProc__JAAuSRLipD6PR9bvYzrAQrA Dl_2080375324_;
tyProc__yCpsgD8EFDFwclvguNymwg Dl_2080375532_;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, CRYPTO_malloc_init__wrappersZopenssl_u660)(void) {
	nimfr_("CRYPTO_malloc_init", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
	popFrame();
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(void*, thisModule__wrappersZopenssl_u177)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("thisModule", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimlf_(344, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");	{
		void* T5_;
		if (!(thisMod__wrappersZopenssl_u179 == 0)) goto LA3_;
		T5_ = (void*)0;
		T5_ = loadLib__pureZdynlib_u6();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		thisMod__wrappersZopenssl_u179 = T5_;
	}
LA3_: ;
	nimln_(346);	result = thisMod__wrappersZopenssl_u179;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, symNullable__wrappersZopenssl_u187)(void* dll_p0, NimStringV2 name_p1, NimStringV2 alternativeName_p2) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("symNullable", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(365);	{
		if (!!((dll_p0 == 0))) goto LA3_;
		nimln_(366);		result = symAddr__pureZdynlib_u74(dll_p0, nimToCStringConv(name_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(367);		{
			NIM_BOOL T7_;
			T7_ = (NIM_BOOL)0;
			T7_ = (result == 0);
			if (!(T7_)) goto LA8_;
			T7_ = (((NI)0) < alternativeName_p2.len);
LA8_: ;
			if (!T7_) goto LA9_;
			nimln_(368);			result = symAddr__pureZdynlib_u74(dll_p0, nimToCStringConv(alternativeName_p2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA9_: ;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(370);		result = NIM_NIL;
	}
LA1_: ;
	nimln_(373);	{
		void* thisDynlib_1;
		if (!(result == 0)) goto LA14_;
		nimln_(374);		thisDynlib_1 = thisModule__wrappersZopenssl_u177();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(375);		{
			if (!(thisDynlib_1 == 0)) goto LA18_;
			nimln_(363);			nimln_(375);			result = NIM_NIL;
			goto BeforeRet_;
		}
LA18_: ;
		nimln_(376);		result = symAddr__pureZdynlib_u74(thisDynlib_1, nimToCStringConv(name_p1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(377);		{
			NIM_BOOL T22_;
			T22_ = (NIM_BOOL)0;
			T22_ = (result == 0);
			if (!(T22_)) goto LA23_;
			T22_ = (((NI)0) < alternativeName_p2.len);
LA23_: ;
			if (!T22_) goto LA24_;
			nimln_(378);			result = symAddr__pureZdynlib_u74(thisDynlib_1, nimToCStringConv(alternativeName_p2));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA24_: ;
	}
LA14_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, popCurrentException)(void) {
	eqcopy___stdZtypedthreads_u223(&currException__system_u4052, (*currException__system_u4052).up, NIM_FALSE);
}
static N_INLINE(void*, sslModule__wrappersZopenssl_u180)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("sslModule", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(351);	{
		void* T6_;
		if (!(sslMod__wrappersZopenssl_u182 == 0)) goto LA4_;
		T6_ = (void*)0;
		T6_ = loadLibPattern__pureZdynlib_u93(TM__SLGpYVEqpFQ7VaPsJH6HIA_3, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		sslMod__wrappersZopenssl_u182 = T6_;
	}
LA4_: ;
	if (NIM_UNLIKELY(*nimErr_)) {
		LA1_:;
		{
			tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA* T10_;
			*nimErr_ = NIM_FALSE;
			nimln_(353);			raiseDefect();
			T10_ = NIM_NIL;
			T10_ = (tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA*) nimNewObj(sizeof(tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA), NIM_ALIGNOF(tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA));
			(*T10_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__DKnljQcDlAtSw8QuzXy6MA_);
			(*T10_).Sup.Sup.Sup.name = "LibraryError";
			(*T10_).Sup.Sup.Sup.message = TM__SLGpYVEqpFQ7VaPsJH6HIA_5;
			(*T10_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
			popCurrentException();
			raiseExceptionEx((Exception*)T10_, "LibraryError", "sslModule", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim", 353);
goto LA8_;
			popCurrentException();
			LA8_:;
		}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(355);	result = sslMod__wrappersZopenssl_u182;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymNullable__wrappersZopenssl_u193)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("sslSymNullable", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(381);	T1_ = (void*)0;
	T1_ = sslModule__wrappersZopenssl_u180();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = symNullable__wrappersZopenssl_u187(T1_, name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, sslSymThrows__wrappersZopenssl_u197)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("sslSymThrows", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(384);	result = sslSymNullable__wrappersZopenssl_u193(name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(385);	{
		if (!(result == 0)) goto LA3_;
		raiseInvalidLibrary__pureZdynlib_u9(nimToCStringConv(name_p0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_library_init__wrappersZopenssl_u282)(void) {
	int result;
	void* newInitSym_1;
	tyProc__u0PsAQN5ndneEiWxnCoc9aw olderProc_1;
	void* T5_;
NIM_BOOL* nimErr_;
	nimfr_("SSL_library_init", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(407);	result = ((int)0);
	nimln_(408);	newInitSym_1 = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_7, TM__SLGpYVEqpFQ7VaPsJH6HIA_9);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(409);	{
		tyProc__bj29cdE9aA9bshc5NUghhGaWw newInitProc_1;
		if (!!((newInitSym_1 == 0))) goto LA3_;
		nimln_(410);		newInitProc_1 = ((tyProc__bj29cdE9aA9bshc5NUghhGaWw) (newInitSym_1));
		nimln_(412);		nimln_(404);		nimln_(412);		result = newInitProc_1(0ULL, ((NU8)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA3_: ;
	nimln_(413);	T5_ = (void*)0;
	T5_ = sslSymThrows__wrappersZopenssl_u197(TM__SLGpYVEqpFQ7VaPsJH6HIA_11, TM__SLGpYVEqpFQ7VaPsJH6HIA_12);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	olderProc_1 = ((tyProc__u0PsAQN5ndneEiWxnCoc9aw) (T5_));
	nimln_(414);	{
		if (!!((olderProc_1 == 0))) goto LA8_;
		result = olderProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA8_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, SSL_load_error_strings__wrappersZopenssl_u332)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("SSL_load_error_strings", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(418);	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_14, TM__SLGpYVEqpFQ7VaPsJH6HIA_15);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	nimln_(419);	{
		if (!!((theProc_1 == 0))) goto LA4_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void*, utilModule__wrappersZopenssl_u184)(void) {
	void* result;
NIM_BOOL* nimErr_;
	nimfr_("utilModule", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(359);	{
		void* T5_;
		if (!(utilMod__wrappersZopenssl_u186 == 0)) goto LA3_;
		T5_ = (void*)0;
		T5_ = loadLibPattern__pureZdynlib_u93(TM__SLGpYVEqpFQ7VaPsJH6HIA_17, NIM_FALSE);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		utilMod__wrappersZopenssl_u186 = T5_;
	}
LA3_: ;
	nimln_(361);	result = utilMod__wrappersZopenssl_u186;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, ERR_load_BIO_strings__wrappersZopenssl_u357)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
	void* T2_;
NIM_BOOL* nimErr_;
	nimfr_("ERR_load_BIO_strings", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(422);	T1_ = (void*)0;
	T1_ = utilModule__wrappersZopenssl_u184();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (void*)0;
	T2_ = symNullable__wrappersZopenssl_u187(T1_, TM__SLGpYVEqpFQ7VaPsJH6HIA_19, TM__SLGpYVEqpFQ7VaPsJH6HIA_20);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T2_));
	nimln_(423);	{
		if (!!((theProc_1 == 0))) goto LA5_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, OpenSSL_add_all_algorithms__wrappersZopenssl_u377)(void) {
	tyProc__ln4kdL5W9bbX4a1xl8nnVXQ theProc_1;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("OpenSSL_add_all_algorithms", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	nimln_(448);	T1_ = (void*)0;
	T1_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_22, TM__SLGpYVEqpFQ7VaPsJH6HIA_23);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) (T1_));
	nimln_(449);	{
		if (!!((theProc_1 == 0))) goto LA4_;
		theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__SLGpYVEqpFQ7VaPsJH6HIA_26;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__SLGpYVEqpFQ7VaPsJH6HIA_26)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__SLGpYVEqpFQ7VaPsJH6HIA_26);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*, loadPSSLMethod__wrappersZopenssl_u205)(NimStringV2 method1_p0, NimStringV2 method2_p1) {
	tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* result;
	void* methodSym_1;
	tyProc__Cz2KMMgCPPHsvY9c9b9cXbFBA method2Proc_1;
NIM_BOOL* nimErr_;
	nimfr_("loadPSSLMethod", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*)0;
	nimln_(393);	methodSym_1 = sslSymNullable__wrappersZopenssl_u193(method1_p0, method2_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(394);	{
		tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA* T5_;
		NimStringV2 T6_;
		if (!(methodSym_1 == 0)) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA*) nimNewObj(sizeof(tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA), NIM_ALIGNOF(tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__DKnljQcDlAtSw8QuzXy6MA_);
		(*T5_).Sup.Sup.Sup.name = "LibraryError";
		nimln_(395);		T6_.len = 0; T6_.p = NIM_NIL;
		T6_ = rawNewString(method1_p0.len + method2_p1.len + 20);
appendString((&T6_), TM__SLGpYVEqpFQ7VaPsJH6HIA_25);
appendString((&T6_), method1_p0);
appendString((&T6_), TM__SLGpYVEqpFQ7VaPsJH6HIA_28);
appendString((&T6_), method2_p1);
		(*T5_).Sup.Sup.Sup.message = T6_;
		(*T5_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		raiseExceptionEx((Exception*)T5_, "LibraryError", "loadPSSLMethod", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim", 395);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(397);	method2Proc_1 = ((tyProc__Cz2KMMgCPPHsvY9c9b9cXbFBA) (methodSym_1));
	nimln_(398);	nimln_(390);	nimln_(398);	result = method2Proc_1();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*, TLS_method__wrappersZopenssl_u371)(void) {
	tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* result;
NIM_BOOL* nimErr_;
	nimfr_("TLS_method", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*)0;
	nimln_(438);	result = loadPSSLMethod__wrappersZopenssl_u205(TM__SLGpYVEqpFQ7VaPsJH6HIA_30, TM__SLGpYVEqpFQ7VaPsJH6HIA_32);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void*, utilSymNullable__wrappersZopenssl_u201)(NimStringV2 name_p0, NimStringV2 alternativeName_p1) {
	void* result;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("utilSymNullable", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (void*)0;
	nimln_(388);	T1_ = (void*)0;
	T1_ = utilModule__wrappersZopenssl_u184();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = symNullable__wrappersZopenssl_u187(T1_, name_p0, alternativeName_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(unsigned long, getOpenSSLVersion__wrappersZopenssl_u383)(void) {
	unsigned long result;
	unsigned long colontmpD_;
	unsigned long colontmpD__2;
	tyProc__Zp8a7gsqfDHPKe06nErJjg theProc_1;
	void* T1_;
NIM_BOOL* nimErr_;
	nimfr_("getOpenSSLVersion", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (unsigned long)0;
	colontmpD_ = (unsigned long)0;
	colontmpD__2 = (unsigned long)0;
	nimln_(453);	T1_ = (void*)0;
	T1_ = utilSymNullable__wrappersZopenssl_u201(TM__SLGpYVEqpFQ7VaPsJH6HIA_154, TM__SLGpYVEqpFQ7VaPsJH6HIA_156);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	theProc_1 = ((tyProc__Zp8a7gsqfDHPKe06nErJjg) (T1_));
	nimln_(454);	nimln_(455);	{
		if (!(theProc_1 == 0)) goto LA4_;
		colontmpD_ = ((unsigned long)0);
		result = colontmpD_;
	}
	goto LA2_;
LA4_: ;
	{
		nimln_(456);		colontmpD__2 = theProc_1();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
LA2_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_CTX_set_ciphersuites__wrappersZopenssl_u444)(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ctx_p0, NCSTRING str_p1) {
	int result;
NIM_BOOL* nimErr_;
	nimfr_("SSL_CTX_set_ciphersuites", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	nimln_(475);	{
		void* T5_;
		if (!(theProc__wrappersZopenssl_u451 == 0)) goto LA3_;
		nimln_(476);		T5_ = (void*)0;
		T5_ = sslSymThrows__wrappersZopenssl_u197(TM__SLGpYVEqpFQ7VaPsJH6HIA_158, TM__SLGpYVEqpFQ7VaPsJH6HIA_159);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		theProc__wrappersZopenssl_u451 = ((tyProc__w49b1ufNINSJzazRiRhQtbA) (T5_));
	}
LA3_: ;
	nimln_(477);	result = theProc__wrappersZopenssl_u451(ctx_p0, str_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, SSLCTXSetMode__wrappersZopenssl_u670)(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ctx_p0, NI mode_p1) {
	NI result;
	nimfr_("SSLCTXSetMode", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
	nimln_(606);	result = Dl_2080375445_(ctx_p0, ((int)33), ((long) (mode_p1)), NIM_NIL);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, SSL_in_init__wrappersZopenssl_u409)(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0) {
	int result;
NIM_BOOL* nimErr_;
	nimfr_("SSL_in_init", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	nimln_(466);	{
		if (!!((theProc__wrappersZopenssl_u415 == 0))) goto LA3_;
		nimln_(467);		result = theProc__wrappersZopenssl_u415(ssl_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA3_: ;
	{
		int T8_;
		nimln_(468);		if (!!((sslState__wrappersZopenssl_u418 == 0))) goto LA6_;
		nimln_(469);		T8_ = (int)0;
		T8_ = sslState__wrappersZopenssl_u418(ssl_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = (NI32)(T8_ & ((NI32)12288));
	}
	goto LA1_;
LA6_: ;
	{
		nimln_(471);		raiseInvalidLibrary__pureZdynlib_u9("SSL_in_init");
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, SSL_set_tlsext_host_name__wrappersZopenssl_u679)(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0, NCSTRING name_p1) {
	NI result;
	nimfr_("SSL_set_tlsext_host_name", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
	nimln_(614);	result = Dl_2080375458_(ssl_p0, ((int)55), ((NI)0), ((void*) (name_p1)));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*, SSL_get_peer_certificate__wrappersZopenssl_u1045)(tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* ssl_p0) {
	tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA* result;
	void* methodSym_1;
	tyProc__V1YoAVR9b32CnjlMDNOHmkw method2Proc_1;
NIM_BOOL* nimErr_;
	nimfr_("SSL_get_peer_certificate", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim");
{nimErr_ = nimErrorFlag();
	result = (tyObject_SslStruct__exAdaaGi3nj9aepNHgyIQFA*)0;
	nimln_(850);	methodSym_1 = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_201, TM__SLGpYVEqpFQ7VaPsJH6HIA_203);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(851);	{
		tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA* T5_;
		if (!(methodSym_1 == 0)) goto LA3_;
		T5_ = NIM_NIL;
		T5_ = (tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA*) nimNewObj(sizeof(tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA), NIM_ALIGNOF(tyObject_LibraryError__DKnljQcDlAtSw8QuzXy6MA));
		(*T5_).Sup.Sup.Sup.Sup.m_type = (&NTIv2__DKnljQcDlAtSw8QuzXy6MA_);
		(*T5_).Sup.Sup.Sup.name = "LibraryError";
		(*T5_).Sup.Sup.Sup.message = TM__SLGpYVEqpFQ7VaPsJH6HIA_205;
		(*T5_).Sup.Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(852);		raiseExceptionEx((Exception*)T5_, "LibraryError", "SSL_get_peer_certificate", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/wrappers/openssl.nim", 852);
goto BeforeRet_;
	}
LA3_: ;
	nimln_(853);	method2Proc_1 = ((tyProc__V1YoAVR9b32CnjlMDNOHmkw) (methodSym_1));
	nimln_(854);	nimln_(849);	nimln_(854);	result = method2Proc_1(ssl_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atpopenssldotnim_Init000)(void) {
{
	TFrame FR_; FR_.len = 0;
	void* T100001_;
	void* T100002_;
	T100001_ = (void*)0;
	T100001_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_173, TM__SLGpYVEqpFQ7VaPsJH6HIA_174);
	theProc__wrappersZopenssl_u415 = ((tyProc__SIyAlzx60yQHC5CJGW8eYQ) (T100001_));
	T100002_ = (void*)0;
	T100002_ = sslSymNullable__wrappersZopenssl_u193(TM__SLGpYVEqpFQ7VaPsJH6HIA_176, TM__SLGpYVEqpFQ7VaPsJH6HIA_177);
	sslState__wrappersZopenssl_u418 = ((tyProc__SIyAlzx60yQHC5CJGW8eYQ) (T100002_));
}/* preInitProc end */
{
}
}

N_LIB_PRIVATE N_NIMCALL(void, atpopenssldotnim_DatInit000)(void) {
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_36))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_39))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_42))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_45))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_48))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_51))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_54))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_57))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_60))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_63))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_66))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_69))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_72))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_75))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_78))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_81))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_84))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_33 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_87))
)) nimLoadLibraryError(TM__SLGpYVEqpFQ7VaPsJH6HIA_88);
	Dl_2080375386_ = (tyProc__Zp8a7gsqfDHPKe06nErJjg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_33, "ERR_peek_last_error");
	Dl_2080375382_ = (tyProc__HE9clvqwtdfVXvgz4Z0y1cw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_33, "ERR_error_string");
if (!((TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_96))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_99))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_102))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_105))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_108))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_111))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_114))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_117))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_120))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_123))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_126))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_129))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_132))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_135))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_138))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_141))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_144))
||(TM__SLGpYVEqpFQ7VaPsJH6HIA_93 = nimLoadLibrary(TM__SLGpYVEqpFQ7VaPsJH6HIA_147))
)) nimLoadLibraryError(TM__SLGpYVEqpFQ7VaPsJH6HIA_148);
	Dl_2080375273_ = (tyProc__V1YoAVR9b32CnjlMDNOHmkw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_new");
	Dl_2080375290_ = (tyProc__w49b1ufNINSJzazRiRhQtbA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_set_cipher_list");
	Dl_2080375445_ = (tyProc__9bSv2pr9a6oeWkMyFAxsf1zg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_ctrl");
	Dl_2080375281_ = (tyProc__eOOMEwhtJsLXt2we9apmrgQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_set_verify");
	Dl_2080375297_ = (tyProc__angjg9akd3OrGEmNAc0xjyA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_use_certificate_chain_file");
	Dl_2080375300_ = (tyProc__yCpsgD8EFDFwclvguNymwg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_use_PrivateKey_file");
	Dl_2080375304_ = (tyProc__SIyAlzx60yQHC5CJGW8eYQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_check_private_key");
	Dl_2080375275_ = (tyProc__iknj9brKiBlkSRnsYKwz66Q) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_CTX_load_verify_locations");
	Dl_2080375550_ = (tyProc__ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_33, "ERR_clear_error");
	Dl_2080375322_ = (tyProc__SIyAlzx60yQHC5CJGW8eYQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_shutdown");
	Dl_2080375339_ = (tyProc__2GNd9aeBUJS68I9cHx7kf5xA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_get_error");
	Dl_2080375260_ = (tyProc__rr3BaCzA7aYoh5azGd4Qzg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_free");
	Dl_2080375335_ = (tyProc__5ItwbcHVPMStFNhHhLmxcA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_write");
	Dl_2080375331_ = (tyProc__Uo9aWMHbHftNNUOXOIAcLaQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_read");
	Dl_2080375344_ = (tyProc__SIyAlzx60yQHC5CJGW8eYQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_pending");
	Dl_2080375258_ = (tyProc__V1YoAVR9b32CnjlMDNOHmkw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_new");
	Dl_2080375319_ = (tyProc__2GNd9aeBUJS68I9cHx7kf5xA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_set_fd");
	Dl_2080375458_ = (tyProc__0QD0nkDJsgcrQHiHPUHLbw) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_ctrl");
	Dl_2080375329_ = (tyProc__SIyAlzx60yQHC5CJGW8eYQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_connect");
	Dl_2080375869_ = (tyProc__Ze9amU3gB2IEcZQRlDt7zSA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "X509_check_host");
	Dl_2080375875_ = (tyProc__rr3BaCzA7aYoh5azGd4Qzg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "X509_free");
	Dl_2080375342_ = (tyProc__SIyAlzx60yQHC5CJGW8eYQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_accept");
	Dl_2080375540_ = (tyProc__yCpsgD8EFDFwclvguNymwg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_write");
	Dl_2080375518_ = (tyProc__SIyAlzx60yQHC5CJGW8eYQ) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_33, "BIO_ctrl_pending");
	Dl_2080375520_ = (tyProc__yCpsgD8EFDFwclvguNymwg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_33, "BIO_read");
	Dl_2080375524_ = (tyProc__yCpsgD8EFDFwclvguNymwg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_33, "BIO_write");
	Dl_2080375324_ = (tyProc__JAAuSRLipD6PR9bvYzrAQrA) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_set_shutdown");
	Dl_2080375532_ = (tyProc__yCpsgD8EFDFwclvguNymwg) nimGetProcAddr(TM__SLGpYVEqpFQ7VaPsJH6HIA_93, "SSL_read");
}

