/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_repeat_d/@pos.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_repeat_d/@pos.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <math.h>
#include <sys/wait.h>
#include <unistd.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_FileInfo__XNTMHLC0Xgbi2IBpgY6bDg tyObject_FileInfo__XNTMHLC0Xgbi2IBpgY6bDg;
typedef struct tyTuple__Y1K3kqz0t9cdyEnxhHismXA tyTuple__Y1K3kqz0t9cdyEnxhHismXA;
typedef struct tyTuple__PvgfbBpJAtNFJFUm9bQCy3Q tyTuple__PvgfbBpJAtNFJFUm9bQCy3Q;
typedef struct tyObject_Time__cvuLVzcyHxYklIcTNfPlrw tyObject_Time__cvuLVzcyHxYklIcTNfPlrw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_PathComponent__9ab8KaO9aGLsXK6FS9al865Ow;
struct tyTuple__Y1K3kqz0t9cdyEnxhHismXA {
	tyEnum_PathComponent__9ab8KaO9aGLsXK6FS9al865Ow Field0;
	NIM_BOOL Field1;
};
struct tyTuple__PvgfbBpJAtNFJFUm9bQCy3Q {
	dev_t Field0;
	ino_t Field1;
};
typedef NU16 tySet_tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA;
struct tyObject_Time__cvuLVzcyHxYklIcTNfPlrw {
	NI64 seconds;
	NI nanosecond;
};
struct tyObject_FileInfo__XNTMHLC0Xgbi2IBpgY6bDg {
	tyTuple__PvgfbBpJAtNFJFUm9bQCy3Q id;
	tyEnum_PathComponent__9ab8KaO9aGLsXK6FS9al865Ow kind;
	NI64 size;
	tySet_tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA permissions;
	NI64 linkCount;
	tyObject_Time__cvuLVzcyHxYklIcTNfPlrw lastAccessTime;
	tyObject_Time__cvuLVzcyHxYklIcTNfPlrw lastWriteTime;
	tyObject_Time__cvuLVzcyHxYklIcTNfPlrw creationTime;
	NI blockSize;
	NIM_BOOL isSpecial;
};
typedef NU8 tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA;
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
static N_INLINE(tyObject_Time__cvuLVzcyHxYklIcTNfPlrw, toTime__pureZos_u24)(struct timespec ts_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Time__cvuLVzcyHxYklIcTNfPlrw, initTime__pureZtimes_u1190)(NI64 unix_p0, NI nanosecond_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(tyTuple__Y1K3kqz0t9cdyEnxhHismXA, getSymlinkFileKind__stdZprivateZoscommon_u17)(NimStringV2 path_p0);
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NF, toFloat__system_u1691)(NI i_p0);
static N_INLINE(NF, abs__system_u5342)(NF x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL, contains__stdZprivateZospaths2_u380)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1);
static N_INLINE(NI, find__stdZprivateZospaths2_u385)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2698)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosaddFileExt)(NimStringV2 filename_p0, NimStringV2 ext_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileExists)(NimStringV2 filename_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8894)(NimStringV2 s_p0, NI first_p1, NI last_p2);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosjoinPath)(NimStringV2 head_p0, NimStringV2 tail_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, expandTilde__pureZos_u32)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2692)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetHomeDir)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, substr__system_u8907)(NimStringV2 s_p0, NI first_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nossymlinkExists)(NimStringV2 link_p0);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosisAbsolute)(NimStringV2 path_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___system_u2689)(NimStringV2* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosparentDir)(NimStringV2 path_p0);
static const struct {
  NI cap; NIM_CHAR data[115+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_3 = { 115 | NIM_STRLIT_FLAG, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim(830, 17) `path != \"\"` " };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_4 = {115, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_3};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_9 = { 4 | NIM_STRLIT_FLAG, "PATH" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_10 = {4, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_9};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__yu6cxgKBBXbNsTkT9cyMd4g_11 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_12 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_11};
static const NimStringV2 TM__yu6cxgKBBXbNsTkT9cyMd4g_18 = {0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_11};
static NIM_CONST tyTuple__Y1K3kqz0t9cdyEnxhHismXA TM__yu6cxgKBBXbNsTkT9cyMd4g_2 = {((tyEnum_PathComponent__9ab8KaO9aGLsXK6FS9al865Ow)2),
NIM_FALSE}
;
N_LIB_PRIVATE NIM_CONST tyArray__nHXaesL0DJZHyVS07ARPRA ExeExts__pureZos_u72 = {{0, (NimStrPayload*)&TM__yu6cxgKBBXbNsTkT9cyMd4g_11}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
static N_INLINE(tyObject_Time__cvuLVzcyHxYklIcTNfPlrw, toTime__pureZos_u24)(struct timespec ts_p0) {
	tyObject_Time__cvuLVzcyHxYklIcTNfPlrw result;
NIM_BOOL* nimErr_;
	nimfr_("toTime", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Time__cvuLVzcyHxYklIcTNfPlrw));
	nimlf_(85, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");	if ((ts_p0.tv_nsec) < ((NI)0) || (ts_p0.tv_nsec) > ((NI)999999999)){ raiseRangeErrorI(ts_p0.tv_nsec, ((NI)0), ((NI)999999999)); goto BeforeRet_;
	}
	result = initTime__pureZtimes_u1190(((NI64) (ts_p0.tv_sec)), (ts_p0.tv_nsec));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, getFileInfo__pureZos_u384)(NimStringV2 path_p0, NIM_BOOL followSymlink_p1, tyObject_FileInfo__XNTMHLC0Xgbi2IBpgY6bDg* Result) {
	tyTuple__Y1K3kqz0t9cdyEnxhHismXA colontmpD_;
	tyTuple__Y1K3kqz0t9cdyEnxhHismXA colontmpD__2;
	tyTuple__Y1K3kqz0t9cdyEnxhHismXA colontmpD__3;
	struct stat rawInfo_1;
	dev_t colontmp_;
	ino_t colontmp__2;
	tyObject_Time__cvuLVzcyHxYklIcTNfPlrw T18_;
	tyObject_Time__cvuLVzcyHxYklIcTNfPlrw T19_;
	tyObject_Time__cvuLVzcyHxYklIcTNfPlrw T20_;
	tyTuple__Y1K3kqz0t9cdyEnxhHismXA tmpTupleAsgn;
NIM_BOOL* nimErr_;
	nimfr_("getFileInfo", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&colontmpD_), sizeof(tyTuple__Y1K3kqz0t9cdyEnxhHismXA));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyTuple__Y1K3kqz0t9cdyEnxhHismXA));
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyTuple__Y1K3kqz0t9cdyEnxhHismXA));
	nimln_(891);	nimZeroMem((void*)Result, sizeof(tyObject_FileInfo__XNTMHLC0Xgbi2IBpgY6bDg));
	nimln_(903);	nimZeroMem((void*)(&rawInfo_1), sizeof(struct stat));
	nimln_(904);	{
		if (!followSymlink_p1) goto LA3_;
		nimln_(905);		{
			int T7_;
			NI32 T10_;
			T7_ = (int)0;
			T7_ = stat(nimToCStringConv(path_p0), (&rawInfo_1));
			if (!(T7_ < ((NI32)0))) goto LA8_;
			nimln_(906);			T10_ = (NI32)0;
			T10_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			raiseOSError__stdZoserrors_u119(T10_, path_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA8_: ;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(908);		{
			int T14_;
			NI32 T17_;
			T14_ = (int)0;
			T14_ = lstat(nimToCStringConv(path_p0), (&rawInfo_1));
			if (!(T14_ < ((NI32)0))) goto LA15_;
			nimln_(909);			T17_ = (NI32)0;
			T17_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			raiseOSError__stdZoserrors_u119(T17_, path_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA15_: ;
	}
LA1_: ;
	nimln_(805);	colontmp_ = rawInfo_1.st_dev;
	colontmp__2 = rawInfo_1.st_ino;
	(*Result).id.Field0 = colontmp_;
	(*Result).id.Field1 = colontmp__2;
	nimln_(806);	(*Result).size = rawInfo_1.st_size;
	nimln_(807);	(*Result).linkCount = ((NI64) (rawInfo_1.st_nlink));
	nimln_(808);	nimZeroMem((void*)(&T18_), sizeof(tyObject_Time__cvuLVzcyHxYklIcTNfPlrw));
	T18_ = toTime__pureZos_u24(rawInfo_1.st_atimespec);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).lastAccessTime = T18_;
	nimln_(809);	nimZeroMem((void*)(&T19_), sizeof(tyObject_Time__cvuLVzcyHxYklIcTNfPlrw));
	T19_ = toTime__pureZos_u24(rawInfo_1.st_mtimespec);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).lastWriteTime = T19_;
	nimln_(810);	nimZeroMem((void*)(&T20_), sizeof(tyObject_Time__cvuLVzcyHxYklIcTNfPlrw));
	T20_ = toTime__pureZos_u24(rawInfo_1.st_ctimespec);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	(*Result).creationTime = T20_;
	nimln_(811);	(*Result).blockSize = ((NI) (rawInfo_1.st_blksize));
	nimln_(813);	(*Result).permissions = 0;
	nimln_(814);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IRUSR))) == ((mode_t)0)))) goto LA23_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)2))) & 15);
	}
LA23_: ;
	nimln_(815);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IWUSR))) == ((mode_t)0)))) goto LA27_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)1))) & 15);
	}
LA27_: ;
	nimln_(816);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IXUSR))) == ((mode_t)0)))) goto LA31_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)0))) & 15);
	}
LA31_: ;
	nimln_(818);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IRGRP))) == ((mode_t)0)))) goto LA35_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)5))) & 15);
	}
LA35_: ;
	nimln_(819);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IWGRP))) == ((mode_t)0)))) goto LA39_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)4))) & 15);
	}
LA39_: ;
	nimln_(820);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IXGRP))) == ((mode_t)0)))) goto LA43_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)3))) & 15);
	}
LA43_: ;
	nimln_(822);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IROTH))) == ((mode_t)0)))) goto LA47_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)8))) & 15);
	}
LA47_: ;
	nimln_(823);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IWOTH))) == ((mode_t)0)))) goto LA51_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)7))) & 15);
	}
LA51_: ;
	nimln_(824);	{
		nimln_(803);		if (!!(((NU16)(rawInfo_1.st_mode & ((mode_t) (S_IXOTH))) == ((mode_t)0)))) goto LA55_;
		nimln_(804);		(*Result).permissions |= ((NU16)1)<<(((((tyEnum_FilePermission__f2vXuQ0Z7MBGKWdbov0TfA)6))) & 15);
	}
LA55_: ;
	nimln_(826);	nimln_(827);	{
		NIM_BOOL T59_;
		T59_ = (NIM_BOOL)0;
		T59_ = S_ISDIR(rawInfo_1.st_mode);
		if (!T59_) goto LA60_;
		nimln_(828);		colontmpD_ = TM__yu6cxgKBBXbNsTkT9cyMd4g_2;
		tmpTupleAsgn = colontmpD_;
	}
	goto LA57_;
LA60_: ;
	{
		NIM_BOOL T63_;
		nimln_(829);		T63_ = (NIM_BOOL)0;
		T63_ = S_ISLNK(rawInfo_1.st_mode);
		if (!T63_) goto LA64_;
		nimln_(830);		{
			if (!!(!((path_p0.len == 0)))) goto LA68_;
			failedAssertImpl__stdZassertions_u234(TM__yu6cxgKBBXbNsTkT9cyMd4g_4);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA68_: ;
		nimln_(831);		colontmpD__2 = getSymlinkFileKind__stdZprivateZoscommon_u17(path_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		tmpTupleAsgn = colontmpD__2;
	}
	goto LA57_;
LA64_: ;
	{
		NIM_BOOL T71_;
		nimln_(833);		colontmpD__3.Field0 = ((tyEnum_PathComponent__9ab8KaO9aGLsXK6FS9al865Ow)0);
		T71_ = (NIM_BOOL)0;
		T71_ = S_ISREG(rawInfo_1.st_mode);
		colontmpD__3.Field1 = !(T71_);
		tmpTupleAsgn = colontmpD__3;
	}
LA57_: ;
	nimln_(826);	(*Result).kind = tmpTupleAsgn.Field0;
	(*Result).isSpecial = tmpTupleAsgn.Field1;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NI64, nosgetFileSize)(NimStringV2 file_p0) {
	NI64 result;
	struct stat rawInfo_1;
NIM_BOOL* nimErr_;
	nimfr_("getFileSize", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result = (NI64)0;
	nimln_(459);	nimln_(468);	nimZeroMem((void*)(&rawInfo_1), sizeof(struct stat));
	nimln_(469);	{
		int T3_;
		NI32 T6_;
		T3_ = (int)0;
		T3_ = stat(nimToCStringConv(file_p0), (&rawInfo_1));
		if (!(T3_ < ((NI32)0))) goto LA4_;
		nimln_(470);		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T6_, file_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	result = rawInfo_1.st_size;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NF, toFloat__system_u1691)(NI i_p0) {
	NF result;
	nimfr_("toFloat", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");
	nimlf_(1286, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	result = ((NF) (i_p0));
	popFrame();
	return result;
}
static N_INLINE(NF, abs__system_u5342)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL, nimMulInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	NF floatProd_1;
	NF T1_;
	NF T2_;
	NF resAsFloat_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) * (NU64)(((NU) (b_p1))))));
	T1_ = (NF)0;
	T1_ = toFloat__system_u1691(a_p0);
	T2_ = (NF)0;
	T2_ = toFloat__system_u1691(b_p1);
	floatProd_1 = ((NF)(T1_) * (NF)(T2_));
	resAsFloat_1 = toFloat__system_u1691(r_1);
	{
		if (!(resAsFloat_1 == floatProd_1)) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA3_;
LA5_: ;
	{
		{
			NF T10_;
			NF T11_;
			T10_ = (NF)0;
			T10_ = abs__system_u5342(((NF)(resAsFloat_1) - (NF)(floatProd_1)));
			T11_ = (NF)0;
			T11_ = abs__system_u5342(floatProd_1);
			if (!(((NF)(32.0) * (NF)(T10_)) <= T11_)) goto LA12_;
			(*res_p2) = r_1;
		}
		goto LA8_;
LA12_: ;
		{
			result = NIM_TRUE;
		}
LA8_: ;
	}
LA3_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, nossleep)(NI milsecs_p0) {
	struct timespec a_1;
	struct timespec b_1;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_5;
	NI TM__yu6cxgKBBXbNsTkT9cyMd4g_6;
	int T1_;
	nimfr_("sleep", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");
{	nimlf_(452, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");	nimZeroMem((void*)(&a_1), sizeof(struct timespec));
	nimZeroMem((void*)(&b_1), sizeof(struct timespec));
	nimln_(453);	a_1.tv_sec = ((time_t) ((NI)((milsecs_p0) / (((NI)1000)))));
	nimln_(454);	if (nimMulInt((NI)((milsecs_p0) % (((NI)1000))), ((NI)1000), &TM__yu6cxgKBBXbNsTkT9cyMd4g_5)) { raiseOverflow(); goto BeforeRet_;
	};
	if (nimMulInt((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_5), ((NI)1000), &TM__yu6cxgKBBXbNsTkT9cyMd4g_6)) { raiseOverflow(); goto BeforeRet_;
	};
	a_1.tv_nsec = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_6);
	nimln_(455);	T1_ = (int)0;
	T1_ = nanosleep((&a_1), (&b_1));
	(void)(T1_);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, exitStatusLikeShell__pureZos_u180)(int status_p0) {
	int result;
	NI32 colontmpD_;
	int colontmpD__2;
	nimfr_("exitStatusLikeShell", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");
{	result = (int)0;
	colontmpD_ = (NI32)0;
	colontmpD__2 = (int)0;
	nimln_(474);	nimln_(476);	{
		NIM_BOOL T3_;
		int T6_;
		NI TM__yu6cxgKBBXbNsTkT9cyMd4g_7;
		T3_ = (NIM_BOOL)0;
		T3_ = WIFSIGNALED(status_p0);
		if (!T3_) goto LA4_;
		nimln_(478);		T6_ = (int)0;
		T6_ = WTERMSIG(status_p0);
		if (nimAddInt(((NI32)128), T6_, &TM__yu6cxgKBBXbNsTkT9cyMd4g_7)) { raiseOverflow(); goto BeforeRet_;
		};
		if (TM__yu6cxgKBBXbNsTkT9cyMd4g_7 < (-2147483647 -1) || TM__yu6cxgKBBXbNsTkT9cyMd4g_7 > 2147483647){ raiseOverflow(); goto BeforeRet_;
		}
		colontmpD_ = (NI32)(TM__yu6cxgKBBXbNsTkT9cyMd4g_7);
		result = colontmpD_;
	}
	goto LA1_;
LA4_: ;
	{
		nimln_(480);		colontmpD__2 = WEXITSTATUS(status_p0);
		result = colontmpD__2;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, find__stdZprivateZospaths2_u385)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1) {
	NI result;
	nimfr_("find", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");
{	nimlf_(1764, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	result = ((NI)0);
	{
		NIM_CHAR i_1;
		NI i_2;
		i_1 = (NIM_CHAR)0;
		nimlf_(28, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");		i_2 = ((NI)0);
		{
			nimln_(29);			while (1) {
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_8;
				if (!(i_2 < a_p0Len_0)) goto LA3;
				nimlf_(1765, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				if (i_2 < 0 || i_2 >= a_p0Len_0){ raiseIndexError2(i_2,a_p0Len_0-1); goto BeforeRet_;
				}
				i_1 = a_p0[i_2];
				nimln_(1766);				{
					if (!((NU8)(i_1) == (NU8)(item_p1))) goto LA6_;
					goto BeforeRet_;
				}
LA6_: ;
				nimln_(1767);				if (nimAddInt(result, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_8)) { raiseOverflow(); goto BeforeRet_;
				};
				result = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_8);
				nimlf_(13, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");				i_2 += ((NI)1);
			} LA3: ;
		}
	}
	nimlf_(1768, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	result = ((NI)-1);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, contains__stdZprivateZospaths2_u380)(NIM_CHAR* a_p0, NI a_p0Len_0, NIM_CHAR item_p1) {
	NIM_BOOL result;
	NI T1_;
	nimfr_("contains", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");
{	nimln_(1782);	nimln_(1770);	nimln_(1782);	T1_ = (NI)0;
	T1_ = find__stdZprivateZospaths2_u385(a_p0, a_p0Len_0, item_p1);
	result = (((NI)0) <= T1_);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");
	popFrame();
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NimStringV2, slash___stdZprivateZospaths2_u88)(NimStringV2 head_p0, NimStringV2 tail_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("/", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/ospaths2.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(178, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/ospaths2.nim");	result = nosjoinPath(head_p0, tail_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, expandTilde__pureZos_u32)(NimStringV2 path_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("expandTilde", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(130, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (path_p0.len == ((NI)0));
		if (T3_) goto LA4_;
		if (((NI)0) < 0 || ((NI)0) >= path_p0.len){ raiseIndexError2(((NI)0),path_p0.len-1); goto BeforeRet_;
		}
		T3_ = !(((NU8)(path_p0.p->data[((NI)0)]) == (NU8)(126)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqcopy___system_u2692((&result), path_p0);
	}
	goto LA1_;
LA5_: ;
	{
		nimlf_(132, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");		if (!(path_p0.len == ((NI)1))) goto LA8_;
		nimln_(133);		result = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA1_;
LA8_: ;
	{
		NimStringV2 colontmpD_;
		NimStringV2 colontmpD__2;
		nimln_(134);		if (((NI)1) < 0 || ((NI)1) >= path_p0.len){ raiseIndexError2(((NI)1),path_p0.len-1); goto BeforeRet_;
		}
		if (!(((NU8)(path_p0.p->data[((NI)1)])) == ((NU8)(47)) || ((NU8)(path_p0.p->data[((NI)1)])) == ((NU8)(47)))) goto LA11_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
		nimln_(135);		colontmpD_ = nosgetHomeDir();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		colontmpD__2 = substr__system_u8907(path_p0, ((NI)2));
		result = slash___stdZprivateZospaths2_u88(colontmpD_, colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	goto LA1_;
LA11_: ;
	{
		nimln_(1699);		eqcopy___system_u2692((&result), path_p0);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, findExe__pureZos_u73)(NimStringV2 exe_p0, NIM_BOOL followSymlinks_p1, NimStringV2* extensions_p2, NI extensions_p2Len_0) {
	NimStringV2 result;
	NimStringV2 path_1;
NIM_BOOL* nimErr_;
	nimfr_("findExe", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	path_1.len = 0; path_1.p = NIM_NIL;
	nimlf_(237, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");	{
		if (!(exe_p0.len == ((NI)0))) goto LA4_;
		nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
		goto BeforeRet_;
	}
LA4_: ;
	nimlf_(243, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");	{
		NIM_BOOL T8_;
		T8_ = (NIM_BOOL)0;
		T8_ = contains__stdZprivateZospaths2_u380(((exe_p0).p) ? (exe_p0.p->data) : NIM_NIL, exe_p0.len, 47);
		if (!T8_) goto LA9_;
		{
			NimStringV2* extX60gensym9__1;
			NI i_1;
			extX60gensym9__1 = (NimStringV2*)0;
			nimlf_(18, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");			i_1 = ((NI)0);
			{
				nimln_(19);				while (1) {
					NimStringV2 T14_;
					if (!(i_1 < extensions_p2Len_0)) goto LA13;
					nimlf_(243, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");					if (i_1 < 0 || i_1 >= extensions_p2Len_0){ raiseIndexError2(i_1,extensions_p2Len_0-1); goto LA1_;
					}
					extX60gensym9__1 = (&extensions_p2[i_1]);
					nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");					nimlf_(240, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");					T14_.len = 0; T14_.p = NIM_NIL;
					T14_ = nosaddFileExt(exe_p0, (*extX60gensym9__1));
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T14_); goto LA1_;}
					nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");					eqsink___system_u2698((&result), T14_);
					nimlf_(241, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");					{
						NIM_BOOL T17_;
						T17_ = (NIM_BOOL)0;
						T17_ = nosfileExists(result);
						if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
						if (!T17_) goto LA18_;
						nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");						if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
						goto BeforeRet_;
					}
LA18_: ;
					nimlf_(13, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");					i_1 += ((NI)1);
				} LA13: ;
			}
		}
	}
LA9_: ;
	nimlf_(246, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");	path_1 = getEnv__stdZenvvars_u15(TM__yu6cxgKBBXbNsTkT9cyMd4g_10, TM__yu6cxgKBBXbNsTkT9cyMd4g_12);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		NimStringV2 candidate_1;
		NI lastX60gensym34__1;
		NI splitsX60gensym34__1;
		candidate_1.len = 0; candidate_1.p = NIM_NIL;
		nimlf_(390, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strutils.nim");		lastX60gensym34__1 = ((NI)0);
		nimln_(391);		splitsX60gensym34__1 = ((NI)-1);
		{
			nimln_(450);			while (1) {
				NI firstX60gensym34__1;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_14;
				NimStringV2 T32_;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_16;
				NI TM__yu6cxgKBBXbNsTkT9cyMd4g_17;
				nimln_(393);				if (!(lastX60gensym34__1 <= path_1.len)) goto LA23;
				nimln_(394);				firstX60gensym34__1 = lastX60gensym34__1;
				{
					nimln_(395);					while (1) {
						NIM_BOOL T26_;
						NI TM__yu6cxgKBBXbNsTkT9cyMd4g_13;
						T26_ = (NIM_BOOL)0;
						T26_ = (lastX60gensym34__1 < path_1.len);
						if (!(T26_)) goto LA27_;
						if (lastX60gensym34__1 < 0 || lastX60gensym34__1 >= path_1.len){ raiseIndexError2(lastX60gensym34__1,path_1.len-1); goto LA21_;
						}
						T26_ = !(((NU8)(path_1.p->data[lastX60gensym34__1]) == (NU8)(58)));
LA27_: ;
						if (!T26_) goto LA25;
						nimln_(396);						if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_13)) { raiseOverflow(); goto LA21_;
						};
						lastX60gensym34__1 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_13);
					} LA25: ;
				}
				nimln_(397);				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA30_;
					lastX60gensym34__1 = path_1.len;
				}
LA30_: ;
				nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				nimlf_(247, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");				nimlf_(398, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strutils.nim");				if (nimSubInt(lastX60gensym34__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_14)) { raiseOverflow(); goto LA21_;
				};
				nimlf_(247, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");				T32_.len = 0; T32_.p = NIM_NIL;
				T32_ = substr__system_u8894(path_1, firstX60gensym34__1, (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_14));
				nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				eqsink___system_u2698((&candidate_1), T32_);
				{
					NimStringV2 x_1;
					NimStringV2 colontmpD_;
					x_1.len = 0; x_1.p = NIM_NIL;
					colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
					nimlf_(248, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");					{
						if (!(candidate_1.len == ((NI)0))) goto LA37_;
						nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
						nimlf_(248, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");						goto LA33;
					}
LA37_: ;
					nimln_(254);					colontmpD_ = expandTilde__pureZos_u32(candidate_1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA34_;
					x_1 = slash___stdZprivateZospaths2_u88(colontmpD_, exe_p0);
					if (NIM_UNLIKELY(*nimErr_)) goto LA34_;
					{
						NimStringV2* ext_1;
						NI i_2;
						ext_1 = (NimStringV2*)0;
						nimlf_(18, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");						i_2 = ((NI)0);
						{
							nimln_(19);							while (1) {
								NimStringV2 x_2;
								if (!(i_2 < extensions_p2Len_0)) goto LA41;
								x_2.len = 0; x_2.p = NIM_NIL;
								nimlf_(255, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");								if (i_2 < 0 || i_2 >= extensions_p2Len_0){ raiseIndexError2(i_2,extensions_p2Len_0-1); goto LA42_;
								}
								ext_1 = (&extensions_p2[i_2]);
								nimln_(256);								x_2 = nosaddFileExt(x_1, (*ext_1));
								if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
								nimln_(257);								{
									NIM_BOOL T45_;
									T45_ = (NIM_BOOL)0;
									T45_ = nosfileExists(x_2);
									if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
									if (!T45_) goto LA46_;
									{
										nimln_(259);										while (1) {
											if (!followSymlinks_p1) goto LA49;
											nimln_(260);											{
												NIM_BOOL T52_;
												NimStringV2 r_1;
												NI len_1;
												T52_ = (NIM_BOOL)0;
												T52_ = nossymlinkExists(x_2);
												if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
												if (!T52_) goto LA53_;
												r_1.len = 0; r_1.p = NIM_NIL;
												nimln_(261);												r_1 = mnewString(((NI)1024));
												nimln_(262);												len_1 = readlink(nimToCStringConv(x_2), nimToCStringConv(r_1), ((NI)1024));
												nimln_(263);												{
													NI32 T60_;
													if (!(len_1 < ((NI)0))) goto LA58_;
													nimln_(264);													T60_ = (NI32)0;
													T60_ = osLastError__stdZoserrors_u122();
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
													raiseOSError__stdZoserrors_u119(T60_, exe_p0);
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
												}
LA58_: ;
												nimln_(265);												{
													NI TM__yu6cxgKBBXbNsTkT9cyMd4g_15;
													NimStringV2 T65_;
													if (!(((NI)1024) < len_1)) goto LA63_;
													nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");													nimlf_(266, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");													if (nimAddInt(len_1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_15)) { raiseOverflow(); goto LA55_;
													};
													if (((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_15)) < ((NI)0) || ((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_15)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_15), ((NI)0), ((NI)IL64(9223372036854775807))); goto LA55_;
													}
													T65_.len = 0; T65_.p = NIM_NIL;
													T65_ = mnewString(((NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_15)));
													nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");													eqsink___system_u2698((&r_1), T65_);
													nimlf_(267, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");													len_1 = readlink(nimToCStringConv(x_2), nimToCStringConv(r_1), len_1);
												}
LA63_: ;
												nimln_(268);												if ((len_1) < ((NI)0) || (len_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(len_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA55_;
												}
												setLengthStrV2((&r_1), (len_1));
												nimln_(269);												{
													NIM_BOOL T68_;
													T68_ = (NIM_BOOL)0;
													T68_ = nosisAbsolute(r_1);
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
													if (!T68_) goto LA69_;
													nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");													eqsink___system_u2698((&x_2), r_1);
													eqwasMoved___system_u2689((&r_1));
												}
												goto LA66_;
LA69_: ;
												{
													NimStringV2 colontmpD__2;
													NimStringV2 T72_;
													colontmpD__2.len = 0; colontmpD__2.p = NIM_NIL;
													nimlf_(272, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");													colontmpD__2 = nosparentDir(x_2);
													if (NIM_UNLIKELY(*nimErr_)) goto LA55_;
													T72_.len = 0; T72_.p = NIM_NIL;
													T72_ = slash___stdZprivateZospaths2_u88(colontmpD__2, r_1);
													if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T72_); goto LA55_;}
													nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");													eqsink___system_u2698((&x_2), T72_);
													nimln_(394);													if (colontmpD__2.p && !(colontmpD__2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__2.p);
}
												}
LA66_: ;
												{
													LA55_:;
												}
												{
													if (r_1.p && !(r_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(r_1.p);
}
												}
												if (NIM_UNLIKELY(*nimErr_)) goto LA42_;
											}
											goto LA50_;
LA53_: ;
											{
												nimlf_(274, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");												goto LA48;
											}
LA50_: ;
										} LA49: ;
									} LA48: ;
									nimln_(275);									nimln_(224);									nimln_(275);									result = x_2;
									nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");									eqwasMoved___system_u2689((&x_2));
									nimln_(394);									if (x_2.p && !(x_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_2.p);
}
									if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
									if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
									if (candidate_1.p && !(candidate_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(candidate_1.p);
}
									if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
									goto BeforeRet_;
								}
LA46_: ;
								nimlf_(13, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");								i_2 += ((NI)1);
								{
									LA42_:;
								}
								{
									nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");									if (x_2.p && !(x_2.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_2.p);
}
								}
								if (NIM_UNLIKELY(*nimErr_)) goto LA34_;
							} LA41: ;
						}
					}
					{
						LA34_:;
					}
					{
						if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
						if (x_1.p && !(x_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(x_1.p);
}
					}
					if (NIM_UNLIKELY(*nimErr_)) goto LA21_;
				} LA33: ;
				nimlf_(399, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strutils.nim");				{
					if (!(splitsX60gensym34__1 == ((NI)0))) goto LA82_;
					goto LA22;
				}
LA82_: ;
				nimln_(400);				if (nimSubInt(splitsX60gensym34__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_16)) { raiseOverflow(); goto LA21_;
				};
				splitsX60gensym34__1 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_16);
				nimln_(401);				if (nimAddInt(lastX60gensym34__1, ((NI)1), &TM__yu6cxgKBBXbNsTkT9cyMd4g_17)) { raiseOverflow(); goto LA21_;
				};
				lastX60gensym34__1 = (NI)(TM__yu6cxgKBBXbNsTkT9cyMd4g_17);
			} LA23: ;
		} LA22: ;
		{
			LA21_:;
		}
		{
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (candidate_1.p && !(candidate_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(candidate_1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
	nimlf_(276, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/os.nim");	result = TM__yu6cxgKBBXbNsTkT9cyMd4g_18;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		if (path_1.p && !(path_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(path_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
