/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_repeat_d/@pstrformat.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_repeat_d/@pstrformat.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Value__SWDx48y3phX6dE7KVcXeCQ tyObject_Value__SWDx48y3phX6dE7KVcXeCQ;
typedef struct tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng;
typedef struct tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tyObject_Value__SWDx48y3phX6dE7KVcXeCQ {
	NU64 raw;
};
typedef NU16 tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA;
struct tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng {
	NIM_CHAR fill;
	NIM_CHAR align;
	NIM_CHAR sign;
	NIM_BOOL alternateForm;
	NIM_BOOL padWithZero;
	NI minimumWidth;
	NI precision;
	NIM_CHAR typ;
	NI endPosition;
};
struct tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA {
	tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA kind;
	NI16 label;
	NI32 arg1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ arg0;
};
typedef NU16 tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw;
N_LIB_PRIVATE N_NIMCALL(NimStringV2, alignString__pureZstrformat_u20)(NimStringV2 s_p0, NI minimumWidth_p1, NIM_CHAR align_p2, NIM_CHAR fill_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2692)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(NI, validateUtf8__pureZunicode_u7585)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__pureZunicode_u342)(NIM_CHAR* s_p0, NI s_p0Len_0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError4)(NI l1_p0, NI h1_p1, NI h2_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, runeLen__pureZunicode_u7413)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NIM_CHAR* s_p0, NI s_p0Len_0);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nsuRepeatChar)(NIM_CHAR c_p0, NI count_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s_p0, NI addLen_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u14)(NI xX60gensym0__p0);
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZcore_u4702)(NimStringV2* result_p0, NimStringV2 value_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZgeneZtypesZcore_u53)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ self_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZgeneZtypesZtype95defs_u822)(tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA e_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZgeneZnativeZhir_u160)(NI32 b_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatInt__OOZsrcZgeneZtypesZinstructions_u604)(NI n_p0, NI radix_p1, tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng* spec_p2);
static N_INLINE(NimStringV2, mkDigit__pureZstrformat_u5)(NI v_p0, NIM_CHAR typ_p1);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nimCharToStr)(NIM_CHAR x_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2441)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2698)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1);
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZgeneZtypesZinstructions_u473)(tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA self_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatInt__OOZsrcZgeneZtypesZinstructions_u21)(NI32 n_p0, NI radix_p1, tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng* spec_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u29)(NI32 xX60gensym3__p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZgeneZtypesZtype95defs_u285)(tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw e_p0);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___system_u4934)(NF x_p0);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_5 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_6 = {0, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_5};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_7 = { 2 | NIM_STRLIT_FLAG, "0x" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_8 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_7};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_9 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_7};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_10 = { 2 | NIM_STRLIT_FLAG, "0b" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_11 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_10};
static const struct {
  NI cap; NIM_CHAR data[2+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_12 = { 2 | NIM_STRLIT_FLAG, "0o" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_13 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_12};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_14 = { 1 | NIM_STRLIT_FLAG, "0" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_15 = {1, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_14};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_16 = {0, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_5};
static const struct {
  NI cap; NIM_CHAR data[117+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_17 = { 117 | NIM_STRLIT_FLAG, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim(333, 9) `v < 26` " };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_18 = {117, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_17};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__qDXzsifTQdn8ucTam9cFp4w_28 = { 1 | NIM_STRLIT_FLAG, "-" };
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_29 = {1, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_28};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_35 = {0, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_5};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_36 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_7};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_37 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_7};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_38 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_10};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_39 = {2, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_12};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_40 = {1, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_14};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_41 = {0, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_5};
static const NimStringV2 TM__qDXzsifTQdn8ucTam9cFp4w_48 = {1, (NimStrPayload*)&TM__qDXzsifTQdn8ucTam9cFp4w_28};
N_LIB_PRIVATE NIM_CONST tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng spec__OOZsrcZgeneZtypesZinstructions_u602 = {32, 0, 45, NIM_FALSE, NIM_TRUE, ((NI)4), ((NI)-1), 88, ((NI)3)}
;
N_LIB_PRIVATE NIM_CONST tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng spec__OOZsrcZgeneZtypesZinstructions_u19 = {32, 0, 45, NIM_FALSE, NIM_TRUE, ((NI)4), ((NI)-1), 88, ((NI)3)}
;
N_LIB_PRIVATE NIM_CONST tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng spec__OOZsrcZgeneZlogging95core_u2042 = {32, 0, 45, NIM_FALSE, NIM_TRUE, ((NI)2), ((NI)-1), 100, ((NI)3)}
;
N_LIB_PRIVATE NIM_CONST tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng spec__OOZsrcZgeneZtypesZinstructions_u982 = {32, 0, 45, NIM_FALSE, NIM_TRUE, ((NI)3), ((NI)-1), 0, ((NI)2)}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
static N_INLINE(NI, validateUtf8__pureZunicode_u7585)(NimStringV2 s_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("validateUtf8", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimlf_(1199, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");	nimln_(1206);	nimln_(25);	if ((s_p0.len-1)-((NI)0) != -1 && (((NI)0) < 0 || ((NI)0) >= s_p0.len || (s_p0.len-1) < 0 || (s_p0.len-1) >= s_p0.len)){ raiseIndexError4(((NI)0), (s_p0.len-1), s_p0.len); goto BeforeRet_;
	}
	nimln_(1206);	result = validateUtf8__pureZunicode_u342((((s_p0).p) ? ((NIM_CHAR*)s_p0.p->data+(((NI)0))) : NIM_NIL), ((s_p0.len-1))-(((NI)0))+1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NI, runeLen__pureZunicode_u7413)(NimStringV2 s_p0) {
	NI result;
NIM_BOOL* nimErr_;
	nimfr_("runeLen", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");
{nimErr_ = nimErrorFlag();
	result = (NI)0;
	nimln_(1166);	nimln_(1171);	nimln_(25);	if ((s_p0.len-1)-((NI)0) != -1 && (((NI)0) < 0 || ((NI)0) >= s_p0.len || (s_p0.len-1) < 0 || (s_p0.len-1) >= s_p0.len)){ raiseIndexError4(((NI)0), (s_p0.len-1), s_p0.len); goto BeforeRet_;
	}
	nimln_(1171);	result = nucruneLen((((s_p0).p) ? ((NIM_CHAR*)s_p0.p->data+(((NI)0))) : NIM_NIL), ((s_p0.len-1))-(((NI)0))+1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__qDXzsifTQdn8ucTam9cFp4w_3;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__qDXzsifTQdn8ucTam9cFp4w_3)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_3);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, alignString__pureZstrformat_u20)(NimStringV2 s_p0, NI minimumWidth_p1, NIM_CHAR align_p2, NIM_CHAR fill_p3) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("alignString", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(343, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		if (!(minimumWidth_p1 == ((NI)0))) goto LA3_;
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqcopy___system_u2692((&result), s_p0);
	}
	goto LA1_;
LA3_: ;
	{
		NI colontmpD_;
		NI colontmpD__2;
		NI sRuneLen_1;
		NI toFill_1;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_2;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimlf_(346, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		{
			NI T8_;
			T8_ = (NI)0;
			T8_ = validateUtf8__pureZunicode_u7585(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (!(T8_ == ((NI)-1))) goto LA9_;
			colontmpD_ = runeLen__pureZunicode_u7413(s_p0);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			sRuneLen_1 = colontmpD_;
		}
		goto LA6_;
LA9_: ;
		{
			colontmpD__2 = s_p0.len;
			sRuneLen_1 = colontmpD__2;
		}
LA6_: ;
		nimln_(347);		if (nimSubInt(minimumWidth_p1, sRuneLen_1, &TM__qDXzsifTQdn8ucTam9cFp4w_2)) { raiseOverflow(); goto BeforeRet_;
		};
		toFill_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_2);
		nimln_(348);		{
			if (!(toFill_1 <= ((NI)0))) goto LA14_;
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			eqcopy___system_u2692((&result), s_p0);
		}
		goto LA12_;
LA14_: ;
		{
			NIM_BOOL T17_;
			NimStringV2 colontmpD__3;
			NimStringV2 T21_;
			nimlf_(350, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			T17_ = (NIM_BOOL)0;
			T17_ = ((NU8)(align_p2) == (NU8)(60));
			if (T17_) goto LA18_;
			T17_ = ((NU8)(align_p2) == (NU8)(0));
LA18_: ;
			if (!T17_) goto LA19_;
			colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
			nimln_(351);			T21_.len = 0; T21_.p = NIM_NIL;
			if ((toFill_1) < ((NI)0) || (toFill_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__3 = nsuRepeatChar(fill_p3, (toFill_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T21_ = rawNewString(s_p0.len + colontmpD__3.len + 0);
appendString((&T21_), s_p0);
appendString((&T21_), colontmpD__3);
			result = T21_;
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
		}
		goto LA12_;
LA19_: ;
		{
			NimStringV2 colontmpD__4;
			NimStringV2 colontmpD__5;
			NI half_1;
			NimStringV2 T25_;
			NI TM__qDXzsifTQdn8ucTam9cFp4w_4;
			nimlf_(352, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			if (!((NU8)(align_p2) == (NU8)(94))) goto LA23_;
			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
			colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
			nimln_(353);			half_1 = (NI)((toFill_1) / (((NI)2)));
			nimln_(354);			T25_.len = 0; T25_.p = NIM_NIL;
			if ((half_1) < ((NI)0) || (half_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(half_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__4 = nsuRepeatChar(fill_p3, (half_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (nimSubInt(toFill_1, half_1, &TM__qDXzsifTQdn8ucTam9cFp4w_4)) { raiseOverflow(); goto BeforeRet_;
			};
			if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4)) < ((NI)0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__5 = nsuRepeatChar(fill_p3, ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_4)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T25_ = rawNewString(colontmpD__4.len + s_p0.len + colontmpD__5.len + 0);
appendString((&T25_), colontmpD__4);
appendString((&T25_), s_p0);
appendString((&T25_), colontmpD__5);
			result = T25_;
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		}
		goto LA12_;
LA23_: ;
		{
			NimStringV2 colontmpD__6;
			NimStringV2 T27_;
			colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
			nimlf_(356, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			T27_.len = 0; T27_.p = NIM_NIL;
			if ((toFill_1) < ((NI)0) || (toFill_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__6 = nsuRepeatChar(fill_p3, (toFill_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T27_ = rawNewString(colontmpD__6.len + s_p0.len + 0);
appendString((&T27_), colontmpD__6);
appendString((&T27_), s_p0);
			result = T27_;
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
		}
LA12_: ;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZcore_u4702)(NimStringV2* result_p0, NimStringV2 value_p1) {
	NimStringV2 value_2;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	value_2.len = 0; value_2.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(600, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	nimln_(601);	value_2 = value_p1;
	nimln_(611);	colontmpD_ = alignString__pureZstrformat_u20(value_2, ((NI)0), 0, 32);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__pureZterminal_u261)(NimStringV2* result_p0, NI value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(499, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___systemZdollars_u14(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZcore_u4696)(NimStringV2* result_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(633, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___OOZsrcZgeneZtypesZcore_u53(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	formatValue__OOZsrcZgeneZtypesZcore_u4702(result_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZnativeZbytecode95to95hir_u4003)(NimStringV2* result_p0, tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(633, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___OOZsrcZgeneZtypesZtype95defs_u822(value_p1);
	formatValue__OOZsrcZgeneZtypesZcore_u4702(result_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZnativeZhir_u3423)(NimStringV2* result_p0, NI32 value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(633, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___OOZsrcZgeneZnativeZhir_u160(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	formatValue__OOZsrcZgeneZtypesZcore_u4702(result_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NimStringV2, mkDigit__pureZstrformat_u5)(NI v_p0, NIM_CHAR typ_p1) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("mkDigit", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(333, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		if (!!((v_p0 < ((NI)26)))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__qDXzsifTQdn8ucTam9cFp4w_18);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(334);	{
		NI TM__qDXzsifTQdn8ucTam9cFp4w_19;
		if (!(v_p0 < ((NI)10))) goto LA7_;
		nimln_(335);		if (nimAddInt(((NI)48), v_p0, &TM__qDXzsifTQdn8ucTam9cFp4w_19)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_19)) < ((NI)0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_19)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_19), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result = nimCharToStr(((NIM_CHAR) (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_19)))));
	}
	goto LA5_;
LA7_: ;
	{
		NIM_CHAR colontmpD_;
		NIM_CHAR colontmpD__2;
		NIM_CHAR T10_;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_20;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_21;
		colontmpD_ = (NIM_CHAR)0;
		colontmpD__2 = (NIM_CHAR)0;
		nimln_(337);		T10_ = (NIM_CHAR)0;
		{
			if (!((NU8)(typ_p1) == (NU8)(120))) goto LA13_;
			colontmpD_ = 97;
			T10_ = colontmpD_;
		}
		goto LA11_;
LA13_: ;
		{
			colontmpD__2 = 65;
			T10_ = colontmpD__2;
		}
LA11_: ;
		if (nimAddInt(((NU8)(T10_)), v_p0, &TM__qDXzsifTQdn8ucTam9cFp4w_20)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_20), ((NI)10), &TM__qDXzsifTQdn8ucTam9cFp4w_21)) { raiseOverflow(); goto BeforeRet_;
		};
		if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_21)) < ((NI)0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_21)) > ((NI)255)){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_21), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result = nimCharToStr(((NIM_CHAR) (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_21)))));
	}
LA5_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2441(s_p0);
	}
LA5_: ;
}
static N_INLINE(void, appendChar)(NimStringV2* dest_p0, NIM_CHAR c_p1) {
	NI TM__qDXzsifTQdn8ucTam9cFp4w_30;
{	(*(*dest_p0).p).data[(*dest_p0).len] = c_p1;
	if (nimAddInt((*dest_p0).len, ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_30)) { raiseOverflow(); goto BeforeRet_;
	};
	(*dest_p0).len = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_30);
	(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}BeforeRet_: ;
}
static N_INLINE(void, nimAddCharV1)(NimStringV2* s_p0, NIM_CHAR c_p1) {
	NI TM__qDXzsifTQdn8ucTam9cFp4w_31;
{	prepareAdd(s_p0, ((NI)1));
	(*(*s_p0).p).data[(*s_p0).len] = c_p1;
	if (nimAddInt((*s_p0).len, ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_31)) { raiseOverflow(); goto BeforeRet_;
	};
	(*s_p0).len = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_31);
	(*(*s_p0).p).data[(*s_p0).len] = 0;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatInt__OOZsrcZgeneZtypesZinstructions_u604)(NI n_p0, NI radix_p1, tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng* spec_p2) {
	NimStringV2 result;
	NU64 colontmpD_;
	NU64 colontmpD__2;
	NimStringV2 xx_1;
	NI64 n_2;
	NIM_BOOL negative_1;
	NU64 v_1;
NIM_BOOL* nimErr_;
	nimfr_("formatInt", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_ = (NU64)0;
	colontmpD__2 = (NU64)0;
	xx_1.len = 0; xx_1.p = NIM_NIL;
	nimln_(379);	n_2 = ((NI64) (n_p0));
	nimln_(380);	negative_1 = (n_2 < IL64(0));
	nimln_(381);	nimln_(382);	{
		if (!negative_1) goto LA3_;
		nimln_(384);		colontmpD_ = (NU64)((NU64)(((NU64) ((NI64)((NU64) ~(n_2))))) + (NU64)(1ULL));
		v_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(386);		colontmpD__2 = ((NU64) (n_2));
		v_1 = colontmpD__2;
	}
LA1_: ;
	nimln_(388);	xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_6;
	nimln_(389);	{
		if (!(*spec_p2).alternateForm) goto LA8_;
		nimln_(390);		switch (((NU8)((*spec_p2).typ))) {
		case 88:
		{
			nimln_(391);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_8;
		}
		break;
		case 120:
		{
			nimln_(392);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_9;
		}
		break;
		case 98:
		{
			nimln_(393);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_11;
		}
		break;
		case 111:
		{
			nimln_(394);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_13;
		}
		break;
		default:
		{
		}
		break;
		}
	}
LA8_: ;
	nimln_(397);	{
		if (!(v_1 == 0ULL)) goto LA17_;
		nimln_(398);		result = TM__qDXzsifTQdn8ucTam9cFp4w_15;
	}
	goto LA15_;
LA17_: ;
	{
		nimln_(400);		result = TM__qDXzsifTQdn8ucTam9cFp4w_16;
		{
			nimln_(401);			while (1) {
				NimStringV2 colontmpD__3;
				NU64 d_1;
				if (!((NU64)(0ULL) < (NU64)(v_1))) goto LA21;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				nimln_(402);				d_1 = (NU64)((NU64)(v_1) % (NU64)(((NU64) (radix_p1))));
				nimln_(403);				v_1 = (NU64)((NU64)(v_1) / (NU64)(((NU64) (radix_p1))));
				nimln_(404);				if (d_1 > (NU64)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
				}
				colontmpD__3 = mkDigit__pureZstrformat_u5(((NI) (d_1)), (*spec_p2).typ);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
				nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			} LA21: ;
		}
		{
			NI idx_1;
			NI colontmp_;
			NI i_1;
			idx_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(126, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			nimlf_(405, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			colontmp_ = (NI)((result.len) / (((NI)2)));
			nimlf_(128, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			i_1 = ((NI)0);
			{
				nimln_(129);				while (1) {
					NIM_CHAR T25_;
					NI TM__qDXzsifTQdn8ucTam9cFp4w_22;
					NI TM__qDXzsifTQdn8ucTam9cFp4w_23;
					NI TM__qDXzsifTQdn8ucTam9cFp4w_24;
					if (!(i_1 < colontmp_)) goto LA24;
					nimlf_(405, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");					idx_1 = i_1;
					nimln_(406);					nimPrepareStrMutationV2((&result));
					nimPrepareStrMutationV2((&result));
					T25_ = (NIM_CHAR)0;
					if (idx_1 < 0 || idx_1 >= result.len){ raiseIndexError2(idx_1,result.len-1); goto BeforeRet_;
					}
					if (nimSubInt(result.len, idx_1, &TM__qDXzsifTQdn8ucTam9cFp4w_22)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_22), ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_23)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23) < 0 || (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23) >= result.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23),result.len-1); goto BeforeRet_;
					}
					T25_ = result.p->data[idx_1];
					result.p->data[idx_1] = result.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23)];
					result.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_23)] = T25_;
					nimlf_(131, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");					if (nimAddInt(i_1, ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_24)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_24);
				} LA24: ;
			}
		}
	}
LA15_: ;
	nimlf_(407, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		NIM_BOOL sign_1;
		NIM_BOOL T30_;
		NI toFill_1;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_25;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_26;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_27;
		if (!(*spec_p2).padWithZero) goto LA28_;
		nimln_(408);		T30_ = (NIM_BOOL)0;
		T30_ = negative_1;
		if (T30_) goto LA31_;
		T30_ = !(((NU8)((*spec_p2).sign) == (NU8)(45)));
LA31_: ;
		sign_1 = T30_;
		nimln_(409);		if (nimSubInt((*spec_p2).minimumWidth, result.len, &TM__qDXzsifTQdn8ucTam9cFp4w_25)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_25), xx_1.len, &TM__qDXzsifTQdn8ucTam9cFp4w_26)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_26), sign_1, &TM__qDXzsifTQdn8ucTam9cFp4w_27)) { raiseOverflow(); goto BeforeRet_;
		};
		toFill_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_27);
		nimln_(410);		{
			NimStringV2 colontmpD__4;
			NimStringV2 T36_;
			if (!(((NI)0) < toFill_1)) goto LA34_;
			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			nimlf_(411, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			T36_.len = 0; T36_.p = NIM_NIL;
			if ((toFill_1) < ((NI)0) || (toFill_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__4 = nsuRepeatChar(48, (toFill_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T36_ = rawNewString(colontmpD__4.len + result.len + 0);
appendString((&T36_), colontmpD__4);
appendString((&T36_), result);
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			eqsink___system_u2698((&result), T36_);
			nimln_(394);			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		}
LA34_: ;
	}
LA28_: ;
	nimlf_(413, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		NimStringV2 T41_;
		if (!negative_1) goto LA39_;
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(414, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		T41_.len = 0; T41_.p = NIM_NIL;
		T41_ = rawNewString(xx_1.len + result.len + 1);
appendString((&T41_), TM__qDXzsifTQdn8ucTam9cFp4w_29);
appendString((&T41_), xx_1);
appendString((&T41_), result);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&result), T41_);
	}
	goto LA37_;
LA39_: ;
	{
		NimStringV2 T45_;
		nimlf_(415, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		if (!!(((NU8)((*spec_p2).sign) == (NU8)(45)))) goto LA43_;
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(416, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		T45_.len = 0; T45_.p = NIM_NIL;
		T45_ = rawNewString(xx_1.len + result.len + 1);
appendChar((&T45_), (*spec_p2).sign);
appendString((&T45_), xx_1);
appendString((&T45_), result);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&result), T45_);
	}
	goto LA37_;
LA43_: ;
	{
		NimStringV2 T47_;
		nimlf_(418, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		T47_.len = 0; T47_.p = NIM_NIL;
		T47_ = rawNewString(xx_1.len + result.len + 0);
appendString((&T47_), xx_1);
appendString((&T47_), result);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&result), T47_);
	}
LA37_: ;
	nimlf_(420, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		if (!((NU8)((*spec_p2).align) == (NU8)(60))) goto LA50_;
		{
			NI i_2;
			NI colontmp__2;
			NI i_3;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(126, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			nimlf_(421, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			colontmp__2 = result.len;
			nimlf_(128, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			i_3 = colontmp__2;
			{
				nimln_(129);				while (1) {
					NI TM__qDXzsifTQdn8ucTam9cFp4w_32;
					if (!(i_3 < (*spec_p2).minimumWidth)) goto LA54;
					nimlf_(421, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");					i_2 = i_3;
					nimln_(422);					nimAddCharV1((&result), (*spec_p2).fill);
					nimlf_(131, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");					if (nimAddInt(i_3, ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_32)) { raiseOverflow(); goto BeforeRet_;
					};
					i_3 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_32);
				} LA54: ;
			}
		}
	}
	goto LA48_;
LA50_: ;
	{
		NI toFill_2;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_33;
		nimlf_(424, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		if (nimSubInt((*spec_p2).minimumWidth, result.len, &TM__qDXzsifTQdn8ucTam9cFp4w_33)) { raiseOverflow(); goto BeforeRet_;
		};
		toFill_2 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_33);
		nimln_(425);		{
			NimStringV2 colontmpD__5;
			NimStringV2 colontmpD__6;
			NI half_1;
			NimStringV2 T60_;
			NI TM__qDXzsifTQdn8ucTam9cFp4w_34;
			if (!((NU8)((*spec_p2).align) == (NU8)(94))) goto LA58_;
			colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
			colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
			nimln_(426);			half_1 = (NI)((toFill_2) / (((NI)2)));
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			nimlf_(427, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			T60_.len = 0; T60_.p = NIM_NIL;
			if ((half_1) < ((NI)0) || (half_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(half_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__5 = nsuRepeatChar((*spec_p2).fill, (half_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (nimSubInt(toFill_2, half_1, &TM__qDXzsifTQdn8ucTam9cFp4w_34)) { raiseOverflow(); goto BeforeRet_;
			};
			if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_34)) < ((NI)0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_34)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_34), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__6 = nsuRepeatChar((*spec_p2).fill, ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_34)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T60_ = rawNewString(colontmpD__5.len + result.len + colontmpD__6.len + 0);
appendString((&T60_), colontmpD__5);
appendString((&T60_), result);
appendString((&T60_), colontmpD__6);
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			eqsink___system_u2698((&result), T60_);
			nimln_(394);			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		}
		goto LA56_;
LA58_: ;
		{
			nimlf_(429, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			{
				NimStringV2 colontmpD__7;
				NimStringV2 T66_;
				if (!(((NI)0) < toFill_2)) goto LA64_;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				nimlf_(430, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");				T66_.len = 0; T66_.p = NIM_NIL;
				if ((toFill_2) < ((NI)0) || (toFill_2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_2, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				colontmpD__7 = nsuRepeatChar((*spec_p2).fill, (toFill_2));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T66_ = rawNewString(colontmpD__7.len + result.len + 0);
appendString((&T66_), colontmpD__7);
appendString((&T66_), result);
				nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				eqsink___system_u2698((&result), T66_);
				nimln_(394);				if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
			}
LA64_: ;
		}
LA56_: ;
	}
LA48_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZinstructions_u596)(NimStringV2* result_p0, NI value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(505, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = formatInt__OOZsrcZgeneZtypesZinstructions_u604(value_p1, ((NI)16), (&spec__OOZsrcZgeneZtypesZinstructions_u602));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, formatInt__OOZsrcZgeneZtypesZinstructions_u21)(NI32 n_p0, NI radix_p1, tyObject_StandardFormatSpecifier__NjmxwiNsQZ9a6m3WKex4qng* spec_p2) {
	NimStringV2 result;
	NU64 colontmpD_;
	NU64 colontmpD__2;
	NimStringV2 xx_1;
	NI64 n_2;
	NIM_BOOL negative_1;
	NU64 v_1;
NIM_BOOL* nimErr_;
	nimfr_("formatInt", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_ = (NU64)0;
	colontmpD__2 = (NU64)0;
	xx_1.len = 0; xx_1.p = NIM_NIL;
	nimlf_(379, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	n_2 = ((NI64) (n_p0));
	nimln_(380);	negative_1 = (n_2 < IL64(0));
	nimln_(381);	nimln_(382);	{
		if (!negative_1) goto LA3_;
		nimln_(384);		colontmpD_ = (NU64)((NU64)(((NU64) ((NI64)((NU64) ~(n_2))))) + (NU64)(1ULL));
		v_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(386);		colontmpD__2 = ((NU64) (n_2));
		v_1 = colontmpD__2;
	}
LA1_: ;
	nimln_(388);	xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_35;
	nimln_(389);	{
		if (!(*spec_p2).alternateForm) goto LA8_;
		nimln_(390);		switch (((NU8)((*spec_p2).typ))) {
		case 88:
		{
			nimln_(391);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_36;
		}
		break;
		case 120:
		{
			nimln_(392);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_37;
		}
		break;
		case 98:
		{
			nimln_(393);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_38;
		}
		break;
		case 111:
		{
			nimln_(394);			xx_1 = TM__qDXzsifTQdn8ucTam9cFp4w_39;
		}
		break;
		default:
		{
		}
		break;
		}
	}
LA8_: ;
	nimln_(397);	{
		if (!(v_1 == 0ULL)) goto LA17_;
		nimln_(398);		result = TM__qDXzsifTQdn8ucTam9cFp4w_40;
	}
	goto LA15_;
LA17_: ;
	{
		nimln_(400);		result = TM__qDXzsifTQdn8ucTam9cFp4w_41;
		{
			nimln_(401);			while (1) {
				NimStringV2 colontmpD__3;
				NU64 d_1;
				if (!((NU64)(0ULL) < (NU64)(v_1))) goto LA21;
				colontmpD__3.len = 0; colontmpD__3.p = NIM_NIL;
				nimln_(402);				d_1 = (NU64)((NU64)(v_1) % (NU64)(((NU64) (radix_p1))));
				nimln_(403);				v_1 = (NU64)((NU64)(v_1) / (NU64)(((NU64) (radix_p1))));
				nimln_(404);				if (d_1 > (NU64)(((NI)IL64(9223372036854775807)))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
				}
				colontmpD__3 = mkDigit__pureZstrformat_u5(((NI) (d_1)), (*spec_p2).typ);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				prepareAdd((&result), colontmpD__3.len + 0);
appendString((&result), colontmpD__3);
				nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				if (colontmpD__3.p && !(colontmpD__3.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__3.p);
}
			} LA21: ;
		}
		{
			NI idx_1;
			NI colontmp_;
			NI i_1;
			idx_1 = (NI)0;
			colontmp_ = (NI)0;
			nimlf_(126, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			nimlf_(405, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			colontmp_ = (NI)((result.len) / (((NI)2)));
			nimlf_(128, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			i_1 = ((NI)0);
			{
				nimln_(129);				while (1) {
					NIM_CHAR T25_;
					NI TM__qDXzsifTQdn8ucTam9cFp4w_42;
					NI TM__qDXzsifTQdn8ucTam9cFp4w_43;
					NI TM__qDXzsifTQdn8ucTam9cFp4w_44;
					if (!(i_1 < colontmp_)) goto LA24;
					nimlf_(405, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");					idx_1 = i_1;
					nimln_(406);					nimPrepareStrMutationV2((&result));
					nimPrepareStrMutationV2((&result));
					T25_ = (NIM_CHAR)0;
					if (idx_1 < 0 || idx_1 >= result.len){ raiseIndexError2(idx_1,result.len-1); goto BeforeRet_;
					}
					if (nimSubInt(result.len, idx_1, &TM__qDXzsifTQdn8ucTam9cFp4w_42)) { raiseOverflow(); goto BeforeRet_;
					};
					if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_42), ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_43)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_43) < 0 || (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_43) >= result.len){ raiseIndexError2((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_43),result.len-1); goto BeforeRet_;
					}
					T25_ = result.p->data[idx_1];
					result.p->data[idx_1] = result.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_43)];
					result.p->data[(NI)(TM__qDXzsifTQdn8ucTam9cFp4w_43)] = T25_;
					nimlf_(131, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");					if (nimAddInt(i_1, ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_44)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_44);
				} LA24: ;
			}
		}
	}
LA15_: ;
	nimlf_(407, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		NIM_BOOL sign_1;
		NIM_BOOL T30_;
		NI toFill_1;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_45;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_46;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_47;
		if (!(*spec_p2).padWithZero) goto LA28_;
		nimln_(408);		T30_ = (NIM_BOOL)0;
		T30_ = negative_1;
		if (T30_) goto LA31_;
		T30_ = !(((NU8)((*spec_p2).sign) == (NU8)(45)));
LA31_: ;
		sign_1 = T30_;
		nimln_(409);		if (nimSubInt((*spec_p2).minimumWidth, result.len, &TM__qDXzsifTQdn8ucTam9cFp4w_45)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_45), xx_1.len, &TM__qDXzsifTQdn8ucTam9cFp4w_46)) { raiseOverflow(); goto BeforeRet_;
		};
		if (nimSubInt((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_46), sign_1, &TM__qDXzsifTQdn8ucTam9cFp4w_47)) { raiseOverflow(); goto BeforeRet_;
		};
		toFill_1 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_47);
		nimln_(410);		{
			NimStringV2 colontmpD__4;
			NimStringV2 T36_;
			if (!(((NI)0) < toFill_1)) goto LA34_;
			colontmpD__4.len = 0; colontmpD__4.p = NIM_NIL;
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			nimlf_(411, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			T36_.len = 0; T36_.p = NIM_NIL;
			if ((toFill_1) < ((NI)0) || (toFill_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__4 = nsuRepeatChar(48, (toFill_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T36_ = rawNewString(colontmpD__4.len + result.len + 0);
appendString((&T36_), colontmpD__4);
appendString((&T36_), result);
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			eqsink___system_u2698((&result), T36_);
			nimln_(394);			if (colontmpD__4.p && !(colontmpD__4.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__4.p);
}
		}
LA34_: ;
	}
LA28_: ;
	nimlf_(413, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		NimStringV2 T41_;
		if (!negative_1) goto LA39_;
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(414, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		T41_.len = 0; T41_.p = NIM_NIL;
		T41_ = rawNewString(xx_1.len + result.len + 1);
appendString((&T41_), TM__qDXzsifTQdn8ucTam9cFp4w_48);
appendString((&T41_), xx_1);
appendString((&T41_), result);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&result), T41_);
	}
	goto LA37_;
LA39_: ;
	{
		NimStringV2 T45_;
		nimlf_(415, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		if (!!(((NU8)((*spec_p2).sign) == (NU8)(45)))) goto LA43_;
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(416, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		T45_.len = 0; T45_.p = NIM_NIL;
		T45_ = rawNewString(xx_1.len + result.len + 1);
appendChar((&T45_), (*spec_p2).sign);
appendString((&T45_), xx_1);
appendString((&T45_), result);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&result), T45_);
	}
	goto LA37_;
LA43_: ;
	{
		NimStringV2 T47_;
		nimlf_(418, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		T47_.len = 0; T47_.p = NIM_NIL;
		T47_ = rawNewString(xx_1.len + result.len + 0);
appendString((&T47_), xx_1);
appendString((&T47_), result);
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&result), T47_);
	}
LA37_: ;
	nimlf_(420, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	{
		if (!((NU8)((*spec_p2).align) == (NU8)(60))) goto LA50_;
		{
			NI i_2;
			NI colontmp__2;
			NI i_3;
			i_2 = (NI)0;
			colontmp__2 = (NI)0;
			nimlf_(126, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			nimlf_(421, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			colontmp__2 = result.len;
			nimlf_(128, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");			i_3 = colontmp__2;
			{
				nimln_(129);				while (1) {
					NI TM__qDXzsifTQdn8ucTam9cFp4w_49;
					if (!(i_3 < (*spec_p2).minimumWidth)) goto LA54;
					nimlf_(421, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");					i_2 = i_3;
					nimln_(422);					nimAddCharV1((&result), (*spec_p2).fill);
					nimlf_(131, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators_1.nim");					if (nimAddInt(i_3, ((NI)1), &TM__qDXzsifTQdn8ucTam9cFp4w_49)) { raiseOverflow(); goto BeforeRet_;
					};
					i_3 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_49);
				} LA54: ;
			}
		}
	}
	goto LA48_;
LA50_: ;
	{
		NI toFill_2;
		NI TM__qDXzsifTQdn8ucTam9cFp4w_50;
		nimlf_(424, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");		if (nimSubInt((*spec_p2).minimumWidth, result.len, &TM__qDXzsifTQdn8ucTam9cFp4w_50)) { raiseOverflow(); goto BeforeRet_;
		};
		toFill_2 = (NI)(TM__qDXzsifTQdn8ucTam9cFp4w_50);
		nimln_(425);		{
			NimStringV2 colontmpD__5;
			NimStringV2 colontmpD__6;
			NI half_1;
			NimStringV2 T60_;
			NI TM__qDXzsifTQdn8ucTam9cFp4w_51;
			if (!((NU8)((*spec_p2).align) == (NU8)(94))) goto LA58_;
			colontmpD__5.len = 0; colontmpD__5.p = NIM_NIL;
			colontmpD__6.len = 0; colontmpD__6.p = NIM_NIL;
			nimln_(426);			half_1 = (NI)((toFill_2) / (((NI)2)));
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			nimlf_(427, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			T60_.len = 0; T60_.p = NIM_NIL;
			if ((half_1) < ((NI)0) || (half_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(half_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__5 = nsuRepeatChar((*spec_p2).fill, (half_1));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			if (nimSubInt(toFill_2, half_1, &TM__qDXzsifTQdn8ucTam9cFp4w_51)) { raiseOverflow(); goto BeforeRet_;
			};
			if (((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51)) < ((NI)0) || ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51)) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
			}
			colontmpD__6 = nsuRepeatChar((*spec_p2).fill, ((NI)(TM__qDXzsifTQdn8ucTam9cFp4w_51)));
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			T60_ = rawNewString(colontmpD__5.len + result.len + colontmpD__6.len + 0);
appendString((&T60_), colontmpD__5);
appendString((&T60_), result);
appendString((&T60_), colontmpD__6);
			nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			eqsink___system_u2698((&result), T60_);
			nimln_(394);			if (colontmpD__6.p && !(colontmpD__6.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__6.p);
}
			if (colontmpD__5.p && !(colontmpD__5.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__5.p);
}
		}
		goto LA56_;
LA58_: ;
		{
			nimlf_(429, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");			{
				NimStringV2 colontmpD__7;
				NimStringV2 T66_;
				if (!(((NI)0) < toFill_2)) goto LA64_;
				colontmpD__7.len = 0; colontmpD__7.p = NIM_NIL;
				nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				nimlf_(430, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");				T66_.len = 0; T66_.p = NIM_NIL;
				if ((toFill_2) < ((NI)0) || (toFill_2) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(toFill_2, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
				}
				colontmpD__7 = nsuRepeatChar((*spec_p2).fill, (toFill_2));
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				T66_ = rawNewString(colontmpD__7.len + result.len + 0);
appendString((&T66_), colontmpD__7);
appendString((&T66_), result);
				nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				eqsink___system_u2698((&result), T66_);
				nimln_(394);				if (colontmpD__7.p && !(colontmpD__7.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD__7.p);
}
			}
LA64_: ;
		}
LA56_: ;
	}
LA48_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZinstructions_u13)(NimStringV2* result_p0, NI32 value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(505, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = formatInt__OOZsrcZgeneZtypesZinstructions_u21(value_p1, ((NI)16), (&spec__OOZsrcZgeneZtypesZinstructions_u19));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZinstructions_u507)(NimStringV2* result_p0, NimStringV2 value_p1) {
	NimStringV2 value_2;
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	value_2.len = 0; value_2.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(600, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	nimln_(601);	value_2 = value_p1;
	nimln_(611);	colontmpD_ = alignString__pureZstrformat_u20(value_2, ((NI)20), 60, 32);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZinstructions_u806)(NimStringV2* result_p0, NI32 value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(499, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___systemZdollars_u29(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZinstructions_u989)(NimStringV2* result_p0, tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(633, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___OOZsrcZgeneZtypesZinstructions_u473(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	formatValue__OOZsrcZgeneZtypesZcore_u4702(result_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	{
		LA1_:;
	}
	{
		nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZvm_u29338)(NimStringV2* result_p0, tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(633, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___OOZsrcZgeneZtypesZtype95defs_u285(value_p1);
	formatValue__OOZsrcZgeneZtypesZcore_u4702(result_p0, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZnativeZhir_u2870)(NimStringV2* result_p0, NF value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(574, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = dollar___system_u4934(value_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZlogging95core_u2036)(NimStringV2* result_p0, NI value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(505, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = formatInt__OOZsrcZgeneZtypesZinstructions_u604(value_p1, ((NI)10), (&spec__OOZsrcZgeneZlogging95core_u2042));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, formatValue__OOZsrcZgeneZtypesZinstructions_u976)(NimStringV2* result_p0, NI value_p1) {
	NimStringV2 colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("formatValue", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(505, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/strformat.nim");	colontmpD_ = formatInt__OOZsrcZgeneZtypesZinstructions_u604(value_p1, ((NI)10), (&spec__OOZsrcZgeneZtypesZinstructions_u982));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	prepareAdd((&(*result_p0)), colontmpD_.len + 0);
appendString((&(*result_p0)), colontmpD_);
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}BeforeRet_: ;
	popFrame();
}
