/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_scope_unwind_d/@pmath.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_scope_unwind_d/@pmath.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
typedef NU8 tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ;
static N_INLINE(NIM_BOOL, isNaN__pureZmath_u217)(NF x_p0);
static N_INLINE(NF, abs__system_u5342)(NF x_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo__pureZmath_u258)(NI x_p0) {
	NI result;
	result = (NI)0;
	result = (NI)(x_p0 - ((NI)1));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)32))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)16))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)8))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)4))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)2))));
	result = (NI)(result | (NI)((NI64)(result) >> (NU64)(((NI)1))));
	result += (NI)(((NI)1) + (x_p0 <= ((NI)0)));
	return result;
}
static N_INLINE(NIM_BOOL, isNaN__pureZmath_u217)(NF x_p0) {
	NIM_BOOL result;
	result = (NIM_BOOL)0;
	result = isnan(x_p0);
	return result;
}
static N_INLINE(NF, abs__system_u5342)(NF x_p0) {
	NF result;
	result = (NF)0;
	result = fabs(x_p0);
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ, classify__pureZmath_u214)(NF x_p0) {
	tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ result;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isNaN__pureZmath_u217(x_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		result = ((tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ)4);
		goto BeforeRet_;
	}
LA4_: ;
	{
		if (!(x_p0 == 0.0)) goto LA8_;
		{
			if (!(((NF)(1.0) / (NF)(x_p0)) == INF)) goto LA12_;
			result = ((tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ)2);
			goto BeforeRet_;
		}
		goto LA10_;
LA12_: ;
		{
			result = ((tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ)3);
			goto BeforeRet_;
		}
LA10_: ;
	}
LA8_: ;
	{
		if (!(((NF)(x_p0) * (NF)(0.5)) == x_p0)) goto LA17_;
		{
			if (!(0.0 < x_p0)) goto LA21_;
			result = ((tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ)5);
			goto BeforeRet_;
		}
		goto LA19_;
LA21_: ;
		{
			result = ((tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ)6);
			goto BeforeRet_;
		}
LA19_: ;
	}
LA17_: ;
	{
		NF T26_;
		T26_ = (NF)0;
		T26_ = abs__system_u5342(x_p0);
		if (!(T26_ < 2.225073858507201e-308)) goto LA27_;
		result = ((tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ)1);
		goto BeforeRet_;
	}
LA27_: ;
	result = ((tyEnum_FloatClass__VjqgXK7E0lG9byXap6y2bHQ)0);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI64, floorDiv__pureZtimes_u307)(NI64 x_p0, NI64 y_p1) {
	NI64 result;
	NI64 r_1;
	result = (NI64)0;
	result = (NI64)(x_p0 / y_p1);
	r_1 = (NI64)(x_p0 % y_p1);
	{
		NIM_BOOL T3_;
		NIM_BOOL T4_;
		NIM_BOOL T7_;
		T3_ = (NIM_BOOL)0;
		T4_ = (NIM_BOOL)0;
		T4_ = (IL64(0) < r_1);
		if (!(T4_)) goto LA5_;
		T4_ = (y_p1 < IL64(0));
LA5_: ;
		T3_ = T4_;
		if (T3_) goto LA6_;
		T7_ = (NIM_BOOL)0;
		T7_ = (r_1 < IL64(0));
		if (!(T7_)) goto LA8_;
		T7_ = (IL64(0) < y_p1);
LA8_: ;
		T3_ = T7_;
LA6_: ;
		if (!T3_) goto LA9_;
		result -= ((NI)1);
	}
LA9_: ;
	return result;
}
