/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_scope_unwind_d/@pstd@sprivate@sosappdirs.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_scope_unwind_d/@pstd@sprivate@sosappdirs.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NimStringV2 tyArray__sMpvt1sOxOJ3LFGulnbeMQ[4];
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getEnv__stdZenvvars_u15)(NimStringV2 key_p0, NimStringV2 default_p1);
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, rawNewString)(NI space_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___system_u2692)(NimStringV2* dest_p0, NimStringV2 src_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, existsEnv__stdZenvvars_u20)(NimStringV2 key_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___system_u2698)(NimStringV2* dest_p0, NimStringV2 src_p1);
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0);
N_LIB_PRIVATE N_NIMCALL(void, normalizePathEnd__stdZprivateZospaths2_u20)(NimStringV2* path_p0, NIM_BOOL trailingSep_p1);
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_2 = { 4 | NIM_STRLIT_FLAG, "HOME" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_3 = {4, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_2};
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_4 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_5 = {0, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_4};
static const struct {
  NI cap; NIM_CHAR data[1+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_7 = { 1 | NIM_STRLIT_FLAG, "/" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_8 = {1, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_7};
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_9 = {0, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_4};
static const struct {
  NI cap; NIM_CHAR data[6+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_11 = { 6 | NIM_STRLIT_FLAG, "TMPDIR" };
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_12 = { 4 | NIM_STRLIT_FLAG, "TEMP" };
static const struct {
  NI cap; NIM_CHAR data[3+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_13 = { 3 | NIM_STRLIT_FLAG, "TMP" };
static const struct {
  NI cap; NIM_CHAR data[7+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_14 = { 7 | NIM_STRLIT_FLAG, "TEMPDIR" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_15 = {0, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__XnRPlAiwKKY6TokjvYVCvw_16 = { 4 | NIM_STRLIT_FLAG, "/tmp" };
static const NimStringV2 TM__XnRPlAiwKKY6TokjvYVCvw_17 = {4, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_16};
static NIM_CONST tyArray__sMpvt1sOxOJ3LFGulnbeMQ TM__XnRPlAiwKKY6TokjvYVCvw_10 = {{6, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_11},
{4, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_12},
{3, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_13},
{7, (NimStrPayload*)&TM__XnRPlAiwKKY6TokjvYVCvw_14}}
;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, appendString)(NimStringV2* dest_p0, NimStringV2 src_p1) {
{	{
		NI TM__XnRPlAiwKKY6TokjvYVCvw_6;
		if (!(((NI)0) < src_p1.len)) goto LA3_;
		if ((src_p1.len) < ((NI)0) || (src_p1.len) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(src_p1.len, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		copyMem__system_u1741(((void*) ((&(*(*dest_p0).p).data[(*dest_p0).len]))), ((void*) ((&(*src_p1.p).data[((NI)0)]))), (src_p1.len));
		if (nimAddInt((*dest_p0).len, src_p1.len, &TM__XnRPlAiwKKY6TokjvYVCvw_6)) { raiseOverflow(); goto BeforeRet_;
		};
		(*dest_p0).len = (NI)(TM__XnRPlAiwKKY6TokjvYVCvw_6);
		(*(*dest_p0).p).data[(*dest_p0).len] = 0;
	}
LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetHomeDir)(void) {
	NimStringV2 result;
	NimStringV2 colontmpD_;
	NimStringV2 T2_;
NIM_BOOL* nimErr_;
	nimfr_("getHomeDir", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	nimlf_(26, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");	nimln_(7);	nimln_(26);	T2_.len = 0; T2_.p = NIM_NIL;
	colontmpD_ = getEnv__stdZenvvars_u15(TM__XnRPlAiwKKY6TokjvYVCvw_3, TM__XnRPlAiwKKY6TokjvYVCvw_5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_ = rawNewString(colontmpD_.len + 1);
appendString((&T2_), colontmpD_);
appendString((&T2_), TM__XnRPlAiwKKY6TokjvYVCvw_8);
	result = T2_;
	nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, eqdestroy___system_u281)(NimStringV2 x_p0) {
	nimfr_("=destroy", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nosgetTempDir)(void) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("getTempDir", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(161, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");	result = TM__XnRPlAiwKKY6TokjvYVCvw_9;
	{
		NimStringV2 dirX60gensym3__1;
		NI i_1;
		dirX60gensym3__1.len = 0; dirX60gensym3__1.p = NIM_NIL;
		nimlf_(43, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");		i_1 = ((NI)0);
		{
			nimln_(44);			while (1) {
				nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");				eqcopy___system_u2692((&dirX60gensym3__1), TM__XnRPlAiwKKY6TokjvYVCvw_10[(i_1)- 0]);
				nimlf_(126, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");				{
					NIM_BOOL T7_;
					NimStringV2 T10_;
					T7_ = (NIM_BOOL)0;
					T7_ = existsEnv__stdZenvvars_u20(dirX60gensym3__1);
					if (NIM_UNLIKELY(*nimErr_)) goto LA2_;
					if (!T7_) goto LA8_;
					nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");					nimlf_(127, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");					T10_.len = 0; T10_.p = NIM_NIL;
					T10_ = getEnv__stdZenvvars_u15(dirX60gensym3__1, TM__XnRPlAiwKKY6TokjvYVCvw_15);
					if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___system_u281(T10_); goto LA2_;}
					nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");					eqsink___system_u2698((&result), T10_);
					nimln_(394);					if (dirX60gensym3__1.p && !(dirX60gensym3__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dirX60gensym3__1.p);
}
					nimlf_(128, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");					goto LA1;
				}
LA8_: ;
				nimlf_(46, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");				{
					if (!(((NI)3) <= i_1)) goto LA13_;
					goto LA3;
				}
LA13_: ;
				nimln_(13);				i_1 += ((NI)1);
			}
		} LA3: ;
		{
			LA2_:;
		}
		{
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (dirX60gensym3__1.p && !(dirX60gensym3__1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(dirX60gensym3__1.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	} LA1: ;
	nimlf_(175, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");	{
		if (!(result.len == ((NI)0))) goto LA19_;
		nimlf_(1699, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqsink___system_u2698((&result), TM__XnRPlAiwKKY6TokjvYVCvw_17);
	}
LA19_: ;
	nimlf_(177, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/std/private/osappdirs.nim");	normalizePathEnd__stdZprivateZospaths2_u20((&result), NIM_TRUE);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
