/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_arithmetic_d/@punicode.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_arithmetic_d/@punicode.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA tySequence__48JTohSgTy339bRxHzUD8KA;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA_Content tySequence__48JTohSgTy339bRxHzUD8KA_Content;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__48JTohSgTy339bRxHzUD8KA {
  NI len; tySequence__48JTohSgTy339bRxHzUD8KA_Content* p;
};
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, lteqpercent___system_u1082)(NI32 x_p0, NI32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimPrepareStrMutationImpl__system_u2441)(NimStringV2* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_LIB_PRIVATE N_NIMCALL(tySequence__48JTohSgTy339bRxHzUD8KA, newSeq__pureZunicode_u4516)(NI len_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorNoArgs)(void);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NIMCALL(void, add__pureZunicode_u4534)(tySequence__48JTohSgTy339bRxHzUD8KA* x_p0, NI32 y_p1);
N_LIB_PRIVATE N_NIMCALL(void, alignedDealloc)(void* p_p0, NI align_p1);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24 = {0, (NimStrPayload*)&TM__e1RUVS0Bw7xmj9cnDPXLJMQ_23};
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
N_LIB_PRIVATE N_NIMCALL(NI, validateUtf8__pureZunicode_u342)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	NI result;
	NI i_1;
	NI L_1;
	nimfr_("validateUtf8", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");
{	nimlf_(184, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");	i_1 = ((NI)0);
	nimln_(185);	L_1 = s_p0Len_0;
	{
		nimln_(186);		while (1) {
			if (!(i_1 < L_1)) goto LA2;
			nimln_(187);			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2;
				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) <= (NU64)(((NU)127)))) goto LA5_;
				nimln_(188);				if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_2);
			}
			goto LA3_;
LA5_: ;
			{
				nimln_(189);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)5))) == ((NU)6))) goto LA8_;
				nimln_(190);				{
					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) < (NU64)(((NU)194)))) goto LA12_;
					nimln_(176);					nimln_(190);					result = i_1;
					goto BeforeRet_;
				}
LA12_: ;
				nimln_(191);				{
					NIM_BOOL T16_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5;
					T16_ = (NIM_BOOL)0;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3)) { raiseOverflow(); goto BeforeRet_;
					};
					T16_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_3) < L_1);
					if (!(T16_)) goto LA17_;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4),s_p0Len_0-1); goto BeforeRet_;
					}
					T16_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_4)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA17_: ;
					if (!T16_) goto LA18_;
					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_5);
				}
				goto LA14_;
LA18_: ;
				{
					nimln_(192);					nimln_(176);					nimln_(192);					result = i_1;
					goto BeforeRet_;
				}
LA14_: ;
			}
			goto LA3_;
LA8_: ;
			{
				nimln_(193);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)4))) == ((NU)14))) goto LA22_;
				nimln_(194);				{
					NIM_BOOL T26_;
					NIM_BOOL T27_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9;
					T26_ = (NIM_BOOL)0;
					T27_ = (NIM_BOOL)0;
					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6)) { raiseOverflow(); goto BeforeRet_;
					};
					T27_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_6) < L_1);
					if (!(T27_)) goto LA28_;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7),s_p0Len_0-1); goto BeforeRet_;
					}
					T27_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_7)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA28_: ;
					T26_ = T27_;
					if (!(T26_)) goto LA29_;
					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8),s_p0Len_0-1); goto BeforeRet_;
					}
					T26_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_8)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA29_: ;
					if (!T26_) goto LA30_;
					nimln_(195);					if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_9);
				}
				goto LA24_;
LA30_: ;
				{
					nimln_(196);					nimln_(176);					nimln_(196);					result = i_1;
					goto BeforeRet_;
				}
LA24_: ;
			}
			goto LA3_;
LA22_: ;
			{
				nimln_(197);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)3))) == ((NU)30))) goto LA34_;
				nimln_(198);				{
					NIM_BOOL T38_;
					NIM_BOOL T39_;
					NIM_BOOL T40_;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13;
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14;
					nimln_(199);					T38_ = (NIM_BOOL)0;
					nimln_(198);					T39_ = (NIM_BOOL)0;
					T40_ = (NIM_BOOL)0;
					if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10)) { raiseOverflow(); goto BeforeRet_;
					};
					T40_ = ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_10) < L_1);
					if (!(T40_)) goto LA41_;
					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11),s_p0Len_0-1); goto BeforeRet_;
					}
					T40_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_11)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA41_: ;
					T39_ = T40_;
					if (!(T39_)) goto LA42_;
					nimln_(199);					if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12),s_p0Len_0-1); goto BeforeRet_;
					}
					T39_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_12)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA42_: ;
					T38_ = T39_;
					if (!(T38_)) goto LA43_;
					nimln_(200);					if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13)) { raiseOverflow(); goto BeforeRet_;
					};
					if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13),s_p0Len_0-1); goto BeforeRet_;
					}
					T38_ = ((NU)((NU64)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_13)]))))) >> (NU64)(((NI)6))) == ((NU)2));
LA43_: ;
					if (!T38_) goto LA44_;
					nimln_(201);					if (nimAddInt(i_1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_14);
				}
				goto LA36_;
LA44_: ;
				{
					nimln_(202);					nimln_(176);					nimln_(202);					result = i_1;
					goto BeforeRet_;
				}
LA36_: ;
			}
			goto LA3_;
LA34_: ;
			{
				nimln_(204);				nimln_(176);				nimln_(204);				result = i_1;
				goto BeforeRet_;
			}
LA3_: ;
		} LA2: ;
	}
	nimln_(205);	nimln_(176);	nimln_(205);	result = ((NI)-1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, nucruneLen)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	NI result;
	NI i_1;
	nimfr_("runeLen", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");
{	nimln_(52);	result = ((NI)0);
	nimln_(53);	i_1 = ((NI)0);
	{
		nimln_(54);		while (1) {
			NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22;
			if (!(i_1 < s_p0Len_0)) goto LA2;
			nimln_(55);			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15;
				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) <= (NU64)(((NU)127)))) goto LA5_;
				if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_15);
			}
			goto LA3_;
LA5_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16;
				nimln_(56);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)5))) == ((NU)6))) goto LA8_;
				if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_16);
			}
			goto LA3_;
LA8_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17;
				nimln_(57);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)4))) == ((NU)14))) goto LA11_;
				if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_17);
			}
			goto LA3_;
LA11_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18;
				nimln_(58);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)3))) == ((NU)30))) goto LA14_;
				if (nimAddInt(i_1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_18);
			}
			goto LA3_;
LA14_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19;
				nimln_(59);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)2))) == ((NU)62))) goto LA17_;
				if (nimAddInt(i_1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_19);
			}
			goto LA3_;
LA17_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20;
				nimln_(60);				if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
				}
				if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)1))) == ((NU)126))) goto LA20_;
				if (nimAddInt(i_1, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_20);
			}
			goto LA3_;
LA20_: ;
			{
				NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21;
				nimln_(61);				if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21)) { raiseOverflow(); goto BeforeRet_;
				};
				i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_21);
			}
LA3_: ;
			nimln_(62);			if (nimAddInt(result, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22)) { raiseOverflow(); goto BeforeRet_;
			};
			result = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_22);
		} LA2: ;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NI, runeLenAt__pureZunicode_u94)(NIM_CHAR* s_p0, NI s_p0Len_0, NI i_p1) {
	NI result;
	nimfr_("runeLenAt", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");
{	nimln_(74);	{
		if (i_p1 < 0 || i_p1 >= s_p0Len_0){ raiseIndexError2(i_p1,s_p0Len_0-1); goto BeforeRet_;
		}
		if (!((NU64)(((NU) (((NU8)(s_p0[i_p1]))))) <= (NU64)(((NU)127)))) goto LA3_;
		result = ((NI)1);
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(75);		if (i_p1 < 0 || i_p1 >= s_p0Len_0){ raiseIndexError2(i_p1,s_p0Len_0-1); goto BeforeRet_;
		}
		if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_p1]))))) >> (NU64)(((NI)5))) == ((NU)6))) goto LA6_;
		result = ((NI)2);
	}
	goto LA1_;
LA6_: ;
	{
		nimln_(76);		if (i_p1 < 0 || i_p1 >= s_p0Len_0){ raiseIndexError2(i_p1,s_p0Len_0-1); goto BeforeRet_;
		}
		if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_p1]))))) >> (NU64)(((NI)4))) == ((NU)14))) goto LA9_;
		result = ((NI)3);
	}
	goto LA1_;
LA9_: ;
	{
		nimln_(77);		if (i_p1 < 0 || i_p1 >= s_p0Len_0){ raiseIndexError2(i_p1,s_p0Len_0-1); goto BeforeRet_;
		}
		if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_p1]))))) >> (NU64)(((NI)3))) == ((NU)30))) goto LA12_;
		result = ((NI)4);
	}
	goto LA1_;
LA12_: ;
	{
		nimln_(78);		if (i_p1 < 0 || i_p1 >= s_p0Len_0){ raiseIndexError2(i_p1,s_p0Len_0-1); goto BeforeRet_;
		}
		if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_p1]))))) >> (NU64)(((NI)2))) == ((NU)62))) goto LA15_;
		result = ((NI)5);
	}
	goto LA1_;
LA15_: ;
	{
		nimln_(79);		if (i_p1 < 0 || i_p1 >= s_p0Len_0){ raiseIndexError2(i_p1,s_p0Len_0-1); goto BeforeRet_;
		}
		if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_p1]))))) >> (NU64)(((NI)1))) == ((NU)126))) goto LA18_;
		result = ((NI)6);
	}
	goto LA1_;
LA18_: ;
	{
		nimln_(80);		result = ((NI)1);
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, lteqpercent___system_u1082)(NI32 x_p0, NI32 y_p1) {
	NIM_BOOL result;
	nimfr_("<=%", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/comparisons.nim");
	result = ((NU32)(((NU32) (x_p0))) <= (NU32)(((NU32) (y_p1))));
	popFrame();
	return result;
}
static N_INLINE(void, nimPrepareStrMutationV2)(NimStringV2* s_p0) {
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = !(((*s_p0).p == ((NimStrPayload*) NIM_NIL)));
		if (!(T3_)) goto LA4_;
		T3_ = ((NI)((*(*s_p0).p).cap & ((NI)IL64(4611686018427387904))) == ((NI)IL64(4611686018427387904)));
LA4_: ;
		if (!T3_) goto LA5_;
		nimPrepareStrMutationImpl__system_u2441(s_p0);
	}
LA5_: ;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, nuctoUTF8)(NI32 c_p0) {
	NimStringV2 result;
	NI32 iX60gensym21__1;
	nimfr_("toUTF8", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");
{	nimln_(276);	result = TM__e1RUVS0Bw7xmj9cnDPXLJMQ_24;
	nimln_(221);	iX60gensym21__1 = c_p0;
	nimln_(277);	{
		NIM_BOOL T3_;
		nimln_(222);		T3_ = (NIM_BOOL)0;
		T3_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)127));
		if (!T3_) goto LA4_;
		nimln_(223);		setLengthStrV2((&result), ((NI)1));
		nimln_(224);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if ((iX60gensym21__1) < ((NI)0) || (iX60gensym21__1) > ((NI)255)){ raiseRangeErrorI(iX60gensym21__1, ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) (iX60gensym21__1))));
	}
	goto LA1_;
LA4_: ;
	{
		NIM_BOOL T7_;
		nimln_(226);		T7_ = (NIM_BOOL)0;
		T7_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)2047));
		if (!T7_) goto LA8_;
		nimln_(227);		setLengthStrV2((&result), ((NI)2));
		nimln_(228);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) | ((NI32)192))))));
		nimln_(229);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA8_: ;
	{
		NIM_BOOL T11_;
		nimln_(231);		T11_ = (NIM_BOOL)0;
		T11_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)65535));
		if (!T11_) goto LA12_;
		nimln_(232);		setLengthStrV2((&result), ((NI)3));
		nimln_(233);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) | ((NI32)224))))));
		nimln_(234);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(235);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA12_: ;
	{
		NIM_BOOL T15_;
		nimln_(237);		T15_ = (NIM_BOOL)0;
		T15_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)2097151));
		if (!T15_) goto LA16_;
		nimln_(238);		setLengthStrV2((&result), ((NI)4));
		nimln_(239);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) | ((NI32)240))))));
		nimln_(240);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(241);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(242);		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA16_: ;
	{
		NIM_BOOL T19_;
		nimln_(244);		T19_ = (NIM_BOOL)0;
		T19_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)67108863));
		if (!T19_) goto LA20_;
		nimln_(245);		setLengthStrV2((&result), ((NI)5));
		nimln_(246);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) | ((NI32)248))))));
		nimln_(247);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(248);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(249);		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(250);		if (((NI)4) < 0 || ((NI)4) >= result.len){ raiseIndexError2(((NI)4),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA20_: ;
	{
		NIM_BOOL T23_;
		nimln_(252);		T23_ = (NIM_BOOL)0;
		T23_ = lteqpercent___system_u1082(iX60gensym21__1, ((NI32)2147483647));
		if (!T23_) goto LA24_;
		nimln_(253);		setLengthStrV2((&result), ((NI)6));
		nimln_(254);		if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252))) < ((NI)0) || ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)0)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)30))) | ((NI32)252))))));
		nimln_(255);		if (((NI)1) < 0 || ((NI)1) >= result.len){ raiseIndexError2(((NI)1),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)1)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)24))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(256);		if (((NI)2) < 0 || ((NI)2) >= result.len){ raiseIndexError2(((NI)2),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)2)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)18))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(257);		if (((NI)3) < 0 || ((NI)3) >= result.len){ raiseIndexError2(((NI)3),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)3)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)12))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(258);		if (((NI)4) < 0 || ((NI)4) >= result.len){ raiseIndexError2(((NI)4),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)4)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)((NI32)((NI64)(iX60gensym21__1) >> (NU64)(((NI)6))) & ((NI32)63)) | ((NI32)128))))));
		nimln_(259);		if (((NI)5) < 0 || ((NI)5) >= result.len){ raiseIndexError2(((NI)5),result.len-1); goto BeforeRet_;
		}
		nimPrepareStrMutationV2((&result));
		if (((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) < ((NI)0) || ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))) > ((NI)255)){ raiseRangeErrorI((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128)), ((NI)0), ((NI)255)); goto BeforeRet_;
		}
		result.p->data[((NI)5)] = ((NIM_CHAR) (((NI) ((NI32)((NI32)(iX60gensym21__1 & ((NI32)63)) | ((NI32)128))))));
	}
	goto LA1_;
LA24_: ;
	{
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tySequence__48JTohSgTy339bRxHzUD8KA, toRunes__pureZunicode_u4497)(NIM_CHAR* s_p0, NI s_p0Len_0) {
	tySequence__48JTohSgTy339bRxHzUD8KA result;
	nimfr_("toRunes", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/unicode.nim");
{	nimln_(840);	result = newSeq__pureZunicode_u4516(((NI)0));
	{
		NI32 r_1;
		NI i_1;
		NI32 result_2;
		r_1 = (NI32)0;
		nimln_(811);		i_1 = ((NI)0);
		result_2 = (NI32)0;
		{
			nimln_(813);			while (1) {
				NI32 colontmpD_;
				if (!(i_1 < s_p0Len_0)) goto LA3;
				colontmpD_ = (NI32)0;
				nimln_(814);				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25;
					nimln_(90);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU64)(((NU) (((NU8)(s_p0[i_1]))))) <= (NU64)(((NU)127)))) goto LA6_;
					nimln_(814);					nimln_(91);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (((NU) (((NU8)(s_p0[i_1])))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
					}
					result_2 = ((NI32) (((NU) (((NU8)(s_p0[i_1]))))));
					nimln_(92);					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_25);
				}
				goto LA4_;
LA6_: ;
				{
					nimln_(93);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)5))) == ((NU)6))) goto LA9_;
					nimln_(95);					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_28;
						if (nimSubInt(s_p0Len_0, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26)) { raiseOverflow(); goto BeforeRet_;
						};
						if (!(i_1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_26))) goto LA13_;
						nimln_(814);						nimln_(96);						if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(97);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27),s_p0Len_0-1); goto BeforeRet_;
						}
						if ((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)31))) << (NU64)(((NI)6))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
						}
						result_2 = ((NI32) ((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)31))) << (NU64)(((NI)6))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_27)])))) & ((NU)63)))));
						nimln_(98);						if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_28)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_28);
					}
					goto LA11_;
LA13_: ;
					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29;
						nimln_(814);						nimln_(100);						result_2 = ((NI32)65533);
						nimln_(101);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_29);
					}
LA11_: ;
				}
				goto LA4_;
LA9_: ;
				{
					nimln_(102);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)4))) == ((NU)14))) goto LA17_;
					nimln_(105);					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_33;
						if (nimSubInt(s_p0Len_0, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30)) { raiseOverflow(); goto BeforeRet_;
						};
						if (!(i_1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_30))) goto LA21_;
						nimln_(814);						nimln_(106);						nimln_(107);						nimln_(106);						if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(107);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(108);						if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32),s_p0Len_0-1); goto BeforeRet_;
						}
						if ((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)15))) << (NU64)(((NI)12))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
						}
						result_2 = ((NI32) ((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)15))) << (NU64)(((NI)12))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_31)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_32)])))) & ((NU)63)))));
						nimln_(109);						if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_33)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_33);
					}
					goto LA19_;
LA21_: ;
					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34;
						nimln_(814);						nimln_(111);						result_2 = ((NI32)65533);
						nimln_(112);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_34);
					}
LA19_: ;
				}
				goto LA4_;
LA17_: ;
				{
					nimln_(113);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)3))) == ((NU)30))) goto LA25_;
					nimln_(117);					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_39;
						if (nimSubInt(s_p0Len_0, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35)) { raiseOverflow(); goto BeforeRet_;
						};
						if (!(i_1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_35))) goto LA29_;
						nimln_(814);						nimln_(118);						nimln_(120);						nimln_(119);						nimln_(118);						if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(119);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(120);						if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(121);						if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38),s_p0Len_0-1); goto BeforeRet_;
						}
						if ((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)7))) << (NU64)(((NI)18))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
						}
						result_2 = ((NI32) ((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)7))) << (NU64)(((NI)18))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_36)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_37)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_38)])))) & ((NU)63)))));
						nimln_(122);						if (nimAddInt(i_1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_39)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_39);
					}
					goto LA27_;
LA29_: ;
					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40;
						nimln_(814);						nimln_(124);						result_2 = ((NI32)65533);
						nimln_(125);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_40);
					}
LA27_: ;
				}
				goto LA4_;
LA25_: ;
				{
					nimln_(126);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)2))) == ((NU)62))) goto LA33_;
					nimln_(131);					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_46;
						if (nimSubInt(s_p0Len_0, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41)) { raiseOverflow(); goto BeforeRet_;
						};
						if (!(i_1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_41))) goto LA37_;
						nimln_(814);						nimln_(132);						nimln_(135);						nimln_(134);						nimln_(133);						nimln_(132);						if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(133);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(134);						if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(135);						if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(136);						if (nimAddInt(i_1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45),s_p0Len_0-1); goto BeforeRet_;
						}
						if ((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)3))) << (NU64)(((NI)24))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
						}
						result_2 = ((NI32) ((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)3))) << (NU64)(((NI)24))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_42)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_43)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_44)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_45)])))) & ((NU)63)))));
						nimln_(137);						if (nimAddInt(i_1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_46)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_46);
					}
					goto LA35_;
LA37_: ;
					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47;
						nimln_(814);						nimln_(139);						result_2 = ((NI32)65533);
						nimln_(140);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_47);
					}
LA35_: ;
				}
				goto LA4_;
LA33_: ;
				{
					nimln_(141);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (!((NU)((NU64)(((NU) (((NU8)(s_p0[i_1]))))) >> (NU64)(((NI)1))) == ((NU)126))) goto LA41_;
					nimln_(147);					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53;
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_54;
						if (nimSubInt(s_p0Len_0, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48)) { raiseOverflow(); goto BeforeRet_;
						};
						if (!(i_1 <= (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_48))) goto LA45_;
						nimln_(814);						nimln_(148);						nimln_(152);						nimln_(151);						nimln_(150);						nimln_(149);						nimln_(148);						if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(149);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(150);						if (nimAddInt(i_1, ((NI)2), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(151);						if (nimAddInt(i_1, ((NI)3), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(152);						if (nimAddInt(i_1, ((NI)4), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52),s_p0Len_0-1); goto BeforeRet_;
						}
						nimln_(153);						if (nimAddInt(i_1, ((NI)5), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53)) { raiseOverflow(); goto BeforeRet_;
						};
						if ((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53) < 0 || (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53) >= s_p0Len_0){ raiseIndexError2((NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53),s_p0Len_0-1); goto BeforeRet_;
						}
						if ((NU)((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)1))) << (NU64)(((NI)30))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49)])))) & ((NU)63))) << (NU64)(((NI)24)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53)])))) & ((NU)63))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
						}
						result_2 = ((NI32) ((NU)((NU)((NU)((NU)((NU)((NU)((NU64)((NU)(((NU) (((NU8)(s_p0[i_1])))) & ((NU)1))) << (NU64)(((NI)30))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_49)])))) & ((NU)63))) << (NU64)(((NI)24)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_50)])))) & ((NU)63))) << (NU64)(((NI)18)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_51)])))) & ((NU)63))) << (NU64)(((NI)12)))) | (NU)((NU64)((NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_52)])))) & ((NU)63))) << (NU64)(((NI)6)))) | (NU)(((NU) (((NU8)(s_p0[(NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_53)])))) & ((NU)63)))));
						nimln_(154);						if (nimAddInt(i_1, ((NI)6), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_54)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_54);
					}
					goto LA43_;
LA45_: ;
					{
						NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_55;
						nimln_(814);						nimln_(156);						result_2 = ((NI32)65533);
						nimln_(157);						if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_55)) { raiseOverflow(); goto BeforeRet_;
						};
						i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_55);
					}
LA43_: ;
				}
				goto LA4_;
LA41_: ;
				{
					NI TM__e1RUVS0Bw7xmj9cnDPXLJMQ_56;
					nimln_(814);					nimln_(159);					if (i_1 < 0 || i_1 >= s_p0Len_0){ raiseIndexError2(i_1,s_p0Len_0-1); goto BeforeRet_;
					}
					if (((NU) (((NU8)(s_p0[i_1])))) > (NU)(((NI32)2147483647))){ raiseRangeErrorNoArgs(); goto BeforeRet_;
					}
					result_2 = ((NI32) (((NU) (((NU8)(s_p0[i_1]))))));
					nimln_(160);					if (nimAddInt(i_1, ((NI)1), &TM__e1RUVS0Bw7xmj9cnDPXLJMQ_56)) { raiseOverflow(); goto BeforeRet_;
					};
					i_1 = (NI)(TM__e1RUVS0Bw7xmj9cnDPXLJMQ_56);
				}
LA4_: ;
				nimln_(841);				r_1 = result_2;
				nimln_(842);				colontmpD_ = r_1;
				add__pureZunicode_u4534((&result), colontmpD_);
			} LA3: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___pureZunicode_u714)(tySequence__48JTohSgTy339bRxHzUD8KA dest_p0) {
	if (dest_p0.p && !(dest_p0.p->cap & NIM_STRLIT_FLAG)) {
 alignedDealloc(dest_p0.p, NIM_ALIGNOF(NI32));
}
}
