/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_for_d/@pgene@svm@sgenerator.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_for_d/@pgene@svm@sgenerator.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tySequence__aNpJjaoUowCQc7fBn3wtDQ tySequence__aNpJjaoUowCQc7fBn3wtDQ;
typedef struct tySequence__aNpJjaoUowCQc7fBn3wtDQ_Content tySequence__aNpJjaoUowCQc7fBn3wtDQ_Content;
typedef struct tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g;
typedef struct tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA;
typedef struct tyObject_Value__SWDx48y3phX6dE7KVcXeCQ tyObject_Value__SWDx48y3phX6dE7KVcXeCQ;
typedef struct tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__z0sGq7A9cdKlr0udA70xFEw tySequence__z0sGq7A9cdKlr0udA70xFEw;
typedef struct tySequence__z0sGq7A9cdKlr0udA70xFEw_Content tySequence__z0sGq7A9cdKlr0udA70xFEw_Content;
typedef struct tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw;
typedef struct tySequence__dTyLQYzW1cGZoBBW67Gnmw tySequence__dTyLQYzW1cGZoBBW67Gnmw;
typedef struct tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content;
typedef struct tyObject_Table__lszZnMlhqAeiHEXplgyxMg tyObject_Table__lszZnMlhqAeiHEXplgyxMg;
typedef struct tySequence__YxXxm7F9cWRkm9bU9atASi80w tySequence__YxXxm7F9cWRkm9bU9atASi80w;
typedef struct tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content;
typedef struct tyObject_DocumentcolonObjectType___ZreCvWCNZGwXGf3saSD71Q tyObject_DocumentcolonObjectType___ZreCvWCNZGwXGf3saSD71Q;
typedef struct tyObject_Table__wSm1FEVkikY0Yro661FlBQ tyObject_Table__wSm1FEVkikY0Yro661FlBQ;
typedef struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ;
typedef struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content;
typedef struct tyObject_FutureObjcolonObjectType___lVyqvC6y9btmDx5f50djx7g tyObject_FutureObjcolonObjectType___lVyqvC6y9btmDx5f50djx7g;
typedef struct tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA;
typedef struct tyObject_ThreadcolonObjectType___9cw9c9a3NDm8mEB69bLkGLptZA tyObject_ThreadcolonObjectType___9cw9c9a3NDm8mEB69bLkGLptZA;
typedef struct tyObject_ThreadMessagecolonObjectType___bMgIvffznV2N1WxPcSJlTQ tyObject_ThreadMessagecolonObjectType___bMgIvffznV2N1WxPcSJlTQ;
typedef struct tyObject_PackagecolonObjectType___Rr5CWm4wKukVtN2EwbleRg tyObject_PackagecolonObjectType___Rr5CWm4wKukVtN2EwbleRg;
typedef struct tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg;
typedef struct tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg;
typedef struct tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew;
typedef struct tyObject_BlockcolonObjectType___5QIclX57MyQMOwdLXBLwLg tyObject_BlockcolonObjectType___5QIclX57MyQMOwdLXBLwLg;
typedef struct tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg;
typedef struct tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA;
typedef struct tyObject_EnumDefcolonObjectType___Oca059cdYCZ5x9b3TABVPstw tyObject_EnumDefcolonObjectType___Oca059cdYCZ5x9b3TABVPstw;
typedef struct tyObject_EnumMembercolonObjectType___L5PoYyd4vwGBveVneEMGjA tyObject_EnumMembercolonObjectType___L5PoYyd4vwGBveVneEMGjA;
typedef struct tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w;
typedef struct tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ;
typedef struct tyObject_ExceptionDatacolonObjectType___bpptbc0S9bvZvYEvMUQ3ccg tyObject_ExceptionDatacolonObjectType___bpptbc0S9bvZvYEvMUQ3ccg;
typedef struct tyObject_InterceptioncolonObjectType___eWAKsCNb6G1xztiG1V9bJVw tyObject_InterceptioncolonObjectType___eWAKsCNb6G1xztiG1V9bJVw;
typedef struct tyObject_AspectcolonObjectType___Zgz6QVVjTjizn1WiW59cVnQ tyObject_AspectcolonObjectType___Zgz6QVVjTjizn1WiW59cVnQ;
typedef struct tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA;
typedef struct tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA;
typedef struct tyObject_ScopeTrackercolonObjectType___R8lbBr1AIZQilD37aPAfug tyObject_ScopeTrackercolonObjectType___R8lbBr1AIZQilD37aPAfug;
typedef struct tyObject_FunctionDefInfocolonObjectType___SjMhC3kEgzLPHZSpJsyVbg tyObject_FunctionDefInfocolonObjectType___SjMhC3kEgzLPHZSpJsyVbg;
typedef struct tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA;
typedef struct tyObject_NativeFramecolonObjectType___re9aEd2LQ7lO1pRvhb09cQUQ tyObject_NativeFramecolonObjectType___re9aEd2LQ7lO1pRvhb09cQUQ;
typedef struct tyObject_CustomValuecolonObjectType___aoatYF31mo2xDG546n6qaw tyObject_CustomValuecolonObjectType___aoatYF31mo2xDG546n6qaw;
typedef struct tyObject_ValueError__0LTplYjqhVFXG6XBqdJOOg tyObject_ValueError__0LTplYjqhVFXG6XBqdJOOg;
typedef struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA tySequence__ObNb3ZkQVfF9aSBtrVROGjA;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content;
typedef struct tyObject_RtTypeObjcolonObjectType___29cM9a72Z9c4P1GcYIFRQI9bYA tyObject_RtTypeObjcolonObjectType___29cM9a72Z9c4P1GcYIFRQI9bYA;
typedef struct tyObject_Table__Rv3ycXGMz4yU6SoV8QCKGA tyObject_Table__Rv3ycXGMz4yU6SoV8QCKGA;
typedef struct tySequence__PgmO9aRB9bHlGK0CHo1U4m4A tySequence__PgmO9aRB9bHlGK0CHo1U4m4A;
typedef struct tySequence__PgmO9aRB9bHlGK0CHo1U4m4A_Content tySequence__PgmO9aRB9bHlGK0CHo1U4m4A_Content;
typedef struct tyObject_Table__CzL9a9ah9bJoA4y2iz79aSq5Zw tyObject_Table__CzL9a9ah9bJoA4y2iz79aSq5Zw;
typedef struct tySequence__NjZqgHF3cQ5PeGmWOt05Rw tySequence__NjZqgHF3cQ5PeGmWOt05Rw;
typedef struct tySequence__NjZqgHF3cQ5PeGmWOt05Rw_Content tySequence__NjZqgHF3cQ5PeGmWOt05Rw_Content;
typedef struct tySequence__G3vkCCMQulh7oOvJMyBJpw tySequence__G3vkCCMQulh7oOvJMyBJpw;
typedef struct tySequence__G3vkCCMQulh7oOvJMyBJpw_Content tySequence__G3vkCCMQulh7oOvJMyBJpw_Content;
typedef struct tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw;
typedef struct tyTuple__fzfO9cZNjuQk2gYupM9aIG7w tyTuple__fzfO9cZNjuQk2gYupM9aIG7w;
typedef struct tyTuple__jZQK8lovE2CcAHYpGfxW3A tyTuple__jZQK8lovE2CcAHYpGfxW3A;
typedef struct tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ;
typedef struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g;
typedef struct tyTuple__jzMjktzaKmnVkiw5hAwM0g tyTuple__jzMjktzaKmnVkiw5hAwM0g;
typedef struct tyTuple__XfFS8kt8jBNmhBmSJsKzZg tyTuple__XfFS8kt8jBNmhBmSJsKzZg;
typedef struct tyObject_TypeDesc__h39albJtVav9cfP5NWAg0X8w tyObject_TypeDesc__h39albJtVav9cfP5NWAg0X8w;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA tySequence__48JTohSgTy339bRxHzUD8KA;
typedef struct tySequence__48JTohSgTy339bRxHzUD8KA_Content tySequence__48JTohSgTy339bRxHzUD8KA_Content;
struct tySequence__aNpJjaoUowCQc7fBn3wtDQ {
  NI len; tySequence__aNpJjaoUowCQc7fBn3wtDQ_Content* p;
};
typedef struct {
N_NIMCALL_PTR(void, ClP_0) (void* ClE_0);
void* ClE_0;
} tyProc__HzVCwACFYM9cx9aV62PdjtuA;
struct tyObject_Value__SWDx48y3phX6dE7KVcXeCQ {
	NU64 raw;
};
typedef NU16 tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__z0sGq7A9cdKlr0udA70xFEw {
  NI len; tySequence__z0sGq7A9cdKlr0udA70xFEw_Content* p;
};
struct tySequence__dTyLQYzW1cGZoBBW67Gnmw {
  NI len; tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content* p;
};
struct tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw {
	tySequence__dTyLQYzW1cGZoBBW67Gnmw data;
	NI counter;
};
struct tySequence__YxXxm7F9cWRkm9bU9atASi80w {
  NI len; tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content* p;
};
struct tyObject_Table__lszZnMlhqAeiHEXplgyxMg {
	tySequence__YxXxm7F9cWRkm9bU9atASi80w data;
	NI counter;
};
struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ {
  NI len; tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content* p;
};
struct tyObject_Table__wSm1FEVkikY0Yro661FlBQ {
	tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ data;
	NI counter;
};
struct tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ self;
	tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg* method_0;
};
typedef N_NIMCALL_PTR(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, tyProc__ohS1ljvA2eJrXrq8PifaPQ) (tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p1, NI arg_count_p2, NIM_BOOL has_keyword_args_p3);
typedef N_NIMCALL_PTR(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, tyProc__Q9c4i3jiuHIlJvJtkyxxx4w) (tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ gene_value_p1, tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ* caller_frame_p2);
typedef NU16 tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA;
struct tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA {
	tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA kind;
	NI16 label;
	NI32 arg1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ arg0;
};
struct tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ {
	NI ref_count;
	tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ csymbol;
} _kind_2;
	struct {
	NI64 ratio_num;
	NI64 ratio_denom;
} _kind_3;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bin_data;
	NU bin_bit_size;
} _kind_4;
	struct {
	NU64 bin64_data;
	NU bin64_bit_size;
} _kind_5;
	struct {
	NU8 byte_data;
	NU byte_bit_size;
} _kind_6;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_data;
} _kind_7;
	struct {
	NimStringV2 regex_pattern;
	NU8 regex_flags;
	NimStringV2 regex_replacement;
	NIM_BOOL regex_has_replacement;
} _kind_8;
	struct {
	NimStringV2 regex_match_value;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ regex_match_captures;
	NI64 regex_match_start;
	NI64 regex_match_end;
} _kind_9;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ range_start;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ range_end;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ range_step;
} _kind_10;
	struct {
	NimStringV2 selector_pattern;
	tySequence__z0sGq7A9cdKlr0udA70xFEw selector_path;
} _kind_11;
	struct {
	NI16 date_year;
	NI8 date_month;
	NI8 date_day;
} _kind_12;
	struct {
	NI16 dt_year;
	NI8 dt_month;
	NI8 dt_day;
	NI8 dt_hour;
	NI8 dt_minute;
	NI8 dt_second;
	NI16 dt_timezone;
} _kind_13;
	struct {
	NI8 time_hour;
	NI8 time_minute;
	NI8 time_second;
	NI32 time_microsecond;
} _kind_14;
	struct {
	NI16 tz_offset;
	NimStringV2 tz_name;
} _kind_15;
	struct {
	tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw set;
} _kind_16;
	struct {
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg map;
} _kind_17;
	struct {
	tySequence__z0sGq7A9cdKlr0udA70xFEw stream;
	NI64 stream_index;
	NIM_BOOL stream_ended;
} _kind_18;
	struct {
	tyObject_DocumentcolonObjectType___ZreCvWCNZGwXGf3saSD71Q* doc;
} _kind_19;
	struct {
	NimStringV2 file_path;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ file_content;
	NU16 file_permissions;
} _kind_20;
	struct {
	NimStringV2 arc_path;
	tyObject_Table__wSm1FEVkikY0Yro661FlBQ arc_members;
} _kind_21;
	struct {
	NimStringV2 dir_path;
	tyObject_Table__wSm1FEVkikY0Yro661FlBQ dir_members;
} _kind_22;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ quote;
} _kind_23;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ unquote;
	NIM_BOOL unquote_discard;
} _kind_24;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ ref_target;
} _kind_25;
	struct {
	NI64 target_id;
} _kind_26;
	struct {
	tyObject_FutureObjcolonObjectType___lVyqvC6y9btmDx5f50djx7g* future;
} _kind_27;
	struct {
	tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* generator;
} _kind_28;
	struct {
	tyObject_ThreadcolonObjectType___9cw9c9a3NDm8mEB69bLkGLptZA* thread;
} _kind_29;
	struct {
	tyObject_ThreadMessagecolonObjectType___bMgIvffznV2N1WxPcSJlTQ* thread_message;
} _kind_30;
	struct {
	tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* app;
} _kind_31;
	struct {
	tyObject_PackagecolonObjectType___Rr5CWm4wKukVtN2EwbleRg* pkg;
} _kind_32;
	struct {
	tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg* module;
} _kind_33;
	struct {
	tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* ns;
} _kind_34;
	struct {
	tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew* fn;
} _kind_35;
	struct {
	tyObject_BlockcolonObjectType___5QIclX57MyQMOwdLXBLwLg* block_0;
} _kind_36;
	struct {
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* class_0;
} _kind_37;
	struct {
	tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg* method_0;
} _kind_38;
	struct {
	tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA bound_method;
} _kind_39;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ super_instance;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* super_class;
} _kind_40;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ cast_value;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* cast_class;
} _kind_41;
	struct {
	tyObject_EnumDefcolonObjectType___Oca059cdYCZ5x9b3TABVPstw* enum_def;
} _kind_42;
	struct {
	tyObject_EnumMembercolonObjectType___L5PoYyd4vwGBveVneEMGjA* enum_member;
} _kind_43;
	struct {
	tyProc__ohS1ljvA2eJrXrq8PifaPQ native_fn;
} _kind_44;
	struct {
	tyProc__Q9c4i3jiuHIlJvJtkyxxx4w native_macro;
} _kind_45;
	struct {
	tyProc__ohS1ljvA2eJrXrq8PifaPQ native_method;
} _kind_46;
	struct {
	tyObject_ExceptionDatacolonObjectType___bpptbc0S9bvZvYEvMUQ3ccg* exception_data;
} _kind_47;
	struct {
	tyObject_InterceptioncolonObjectType___eWAKsCNb6G1xztiG1V9bJVw* interception;
} _kind_48;
	struct {
	tyObject_AspectcolonObjectType___Zgz6QVVjTjizn1WiW59cVnQ* aspect;
} _kind_49;
	struct {
	NimStringV2 json_data;
} _kind_50;
	struct {
	FILE* native_file;
} _kind_51;
	struct {
	tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA* cu;
} _kind_52;
	struct {
	tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA instr;
} _kind_53;
	struct {
	tyObject_ScopeTrackercolonObjectType___R8lbBr1AIZQilD37aPAfug* scope_tracker;
} _kind_54;
	struct {
	tyObject_FunctionDefInfocolonObjectType___SjMhC3kEgzLPHZSpJsyVbg* function_def;
} _kind_55;
	struct {
	tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA* scope;
} _kind_56;
	struct {
	tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ* frame;
} _kind_57;
	struct {
	tyObject_NativeFramecolonObjectType___re9aEd2LQ7lO1pRvhb09cQUQ* native_frame;
} _kind_58;
	struct {
	void* any_data;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* any_class;
} _kind_59;
	struct {
	tyObject_CustomValuecolonObjectType___aoatYF31mo2xDG546n6qaw* custom_data;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* custom_class;
} _kind_60;
};
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA {
  NI len; tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__ObNb3ZkQVfF9aSBtrVROGjA trace;
	Exception* up;
};
struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A {
	Exception Sup;
};
struct tyObject_ValueError__0LTplYjqhVFXG6XBqdJOOg {
	tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A Sup;
};
struct tySequence__PgmO9aRB9bHlGK0CHo1U4m4A {
  NI len; tySequence__PgmO9aRB9bHlGK0CHo1U4m4A_Content* p;
};
struct tyObject_Table__Rv3ycXGMz4yU6SoV8QCKGA {
	tySequence__PgmO9aRB9bHlGK0CHo1U4m4A data;
	NI counter;
};
struct tySequence__NjZqgHF3cQ5PeGmWOt05Rw {
  NI len; tySequence__NjZqgHF3cQ5PeGmWOt05Rw_Content* p;
};
struct tyObject_Table__CzL9a9ah9bJoA4y2iz79aSq5Zw {
	tySequence__NjZqgHF3cQ5PeGmWOt05Rw data;
	NI counter;
};
struct tySequence__G3vkCCMQulh7oOvJMyBJpw {
  NI len; tySequence__G3vkCCMQulh7oOvJMyBJpw_Content* p;
};
struct tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g {
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* parent;
	NimStringV2 name;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ constructor;
	tyObject_RtTypeObjcolonObjectType___29cM9a72Z9c4P1GcYIFRQI9bYA* runtime_type;
	tyObject_Table__Rv3ycXGMz4yU6SoV8QCKGA methods;
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg members;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ on_extended;
	tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* ns;
	NIM_BOOL for_singleton;
	NU64 version;
	NIM_BOOL has_macro_constructor;
	tyObject_Table__CzL9a9ah9bJoA4y2iz79aSq5Zw prop_types;
	tySequence__G3vkCCMQulh7oOvJMyBJpw prop_type_descs;
};
struct tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw {
	tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A Sup;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ instance;
};
typedef NU8 tySet_tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw[18];
typedef NU8 tyEnum_GeneratorState__9bNPzJQdLf3q6LwHNTeHB9aA;
struct tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA {
	tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew* function;
	tyEnum_GeneratorState__9bNPzJQdLf3q6LwHNTeHB9aA state;
	tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ* frame;
	tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA* cu;
	NI pc;
	tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA* scope;
	tySequence__z0sGq7A9cdKlr0udA70xFEw stack;
	NIM_BOOL done;
	NIM_BOOL has_peeked;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ peeked_value;
};
struct tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA {
	NimStringV2 name;
	tyObject_PackagecolonObjectType___Rr5CWm4wKukVtN2EwbleRg* pkg;
	tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* ns;
	NimStringV2 cmd;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ args;
	tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg* main_module;
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg props;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ global_ns;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ gene_ns;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ genex_ns;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ object_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ nil_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ bool_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ int_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ float_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ char_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ string_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ symbol_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ complex_symbol_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ array_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ map_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ set_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ gene_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ stream_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ document_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ regex_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ range_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ date_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ datetime_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ time_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ timezone_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ selector_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ exception_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ class_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ mixin_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ application_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ package_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ file_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ dir_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ module_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ namespace_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ function_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ macro_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ block_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ future_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ generator_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ thread_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ thread_message_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ thread_message_type_class;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ aspect_class;
};
struct tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg {
	tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg* module;
	tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* parent;
	NIM_BOOL stop_inheritance;
	NimStringV2 name;
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg members;
	tySequence__z0sGq7A9cdKlr0udA70xFEw on_member_missing;
	NU64 version;
};
typedef N_CLOSURE_PTR(void, TM__LXL6yWqSwJg42sh8gcJheg_39) (void* ClE_0);
struct tySequence__aNpJjaoUowCQc7fBn3wtDQ_Content { NI cap; tyProc__HzVCwACFYM9cx9aV62PdjtuA data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__z0sGq7A9cdKlr0udA70xFEw_Content { NI cap; tyObject_Value__SWDx48y3phX6dE7KVcXeCQ data[SEQ_DECL_SIZE]; };
struct tyTuple__fzfO9cZNjuQk2gYupM9aIG7w {
	NI Field0;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ Field1;
};
struct tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content { NI cap; tyTuple__fzfO9cZNjuQk2gYupM9aIG7w data[SEQ_DECL_SIZE]; };
struct tyTuple__jZQK8lovE2CcAHYpGfxW3A {
	NI Field0;
	NI64 Field1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ Field2;
};
struct tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content { NI cap; tyTuple__jZQK8lovE2CcAHYpGfxW3A data[SEQ_DECL_SIZE]; };
struct tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ {
	NI Field0;
	NimStringV2 Field1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ Field2;
};
struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content { NI cap; tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ data[SEQ_DECL_SIZE]; };
struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content { NI cap; tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g data[SEQ_DECL_SIZE]; };
struct tyTuple__jzMjktzaKmnVkiw5hAwM0g {
	NI Field0;
	NI64 Field1;
	tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg* Field2;
};
struct tySequence__PgmO9aRB9bHlGK0CHo1U4m4A_Content { NI cap; tyTuple__jzMjktzaKmnVkiw5hAwM0g data[SEQ_DECL_SIZE]; };
struct tyTuple__XfFS8kt8jBNmhBmSJsKzZg {
	NI Field0;
	NI64 Field1;
	NI32 Field2;
};
struct tySequence__NjZqgHF3cQ5PeGmWOt05Rw_Content { NI cap; tyTuple__XfFS8kt8jBNmhBmSJsKzZg data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_TypeDescKind__0pP0Mvyoi1kxxAk0JVOZJw;
struct tySequence__48JTohSgTy339bRxHzUD8KA {
  NI len; tySequence__48JTohSgTy339bRxHzUD8KA_Content* p;
};
struct tyObject_TypeDesc__h39albJtVav9cfP5NWAg0X8w {
	NimStringV2 module_path;
	tyEnum_TypeDescKind__0pP0Mvyoi1kxxAk0JVOZJw kind;
union{
	struct {
	NimStringV2 name;
} _kind_2;
	struct {
	NimStringV2 ctor;
	tySequence__48JTohSgTy339bRxHzUD8KA args;
} _kind_3;
	struct {
	tySequence__48JTohSgTy339bRxHzUD8KA members;
} _kind_4;
	struct {
	tySequence__48JTohSgTy339bRxHzUD8KA params;
	NI32 ret;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ effects;
} _kind_5;
	struct {
	NI32 var_id;
} _kind_6;
};
};
struct tySequence__G3vkCCMQulh7oOvJMyBJpw_Content { NI cap; tyObject_TypeDesc__h39albJtVav9cfP5NWAg0X8w data[SEQ_DECL_SIZE]; };
struct tySequence__48JTohSgTy339bRxHzUD8KA_Content { NI cap; NI32 data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(void, init_generator__OOZsrcZgeneZvmZgenerator_u70)(void);
N_LIB_PRIVATE N_NIMCALL(void, add__system_u3931)(tySequence__aNpJjaoUowCQc7fBn3wtDQ* x_p0, tyProc__HzVCwACFYM9cx9aV62PdjtuA y_p1);
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___OOZsrcZgeneZvmZgenerator_u71)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___OOZsrcZgeneZtypesZcore_u48)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ a_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ b_p1);
static N_INLINE(tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw, kind__OOZsrcZgeneZtypesZcore_u46)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ v_p0);
static N_INLINE(tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*, ref__OOZsrcZgeneZtypesZcore_u3066)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ v_p0);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NOINLINE(tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw, kind_slow__OOZsrcZgeneZtypesZcore_u3985)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ v_p0, NU64 u_p1, NU64 tag_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZtypesZcore_u5408)(tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZtypesZcore_u5045)(tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g*, new_class__OOZsrcZgeneZtypesZclasses_u83)(NimStringV2 name_p0);
N_LIB_PRIVATE N_NIMCALL(void, def_native_method__OOZsrcZgeneZtypesZclasses_u619)(tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* self_p0, NimStringV2 name_p1, tyProc__ohS1ljvA2eJrXrq8PifaPQ f_p2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, generator_next__OOZsrcZgeneZvmZgenerator_u77)(tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p1, NI arg_count_p2, NIM_BOOL has_keyword_args_p3);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, get_positional_arg__OOZsrcZgeneZtypesZcore_u15954)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p0, NI index_p1, NIM_BOOL has_keyword_args_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* dest_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ src_p1);
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZgeneZvmZgenerator_u17)(tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA** dest_p0, tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* src_p1, NIM_BOOL cyclic_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___OOZsrcZgeneZtypesZtype95defs_u285)(tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw e_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseFieldErrorStr)(NimStringV2 f_p0, NimStringV2 discVal_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZgeneZtypesZcore_u102)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* v_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZvmZgenerator_u14)(tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* dest_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, exec_generator__OOZsrcZgeneZvmZgenerator_u67)(tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* self_p0, tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* gen_p1);
N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, exec_generator_impl)(tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* self_p0, tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* gen_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, generator_has_next__OOZsrcZgeneZvmZgenerator_u102)(tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p1, NI arg_count_p2, NIM_BOOL has_keyword_args_p3);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZgeneZtypesZtype95defs_u7396)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* dest_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ src_p1);
static N_INLINE(tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*, new_ref__OOZsrcZgeneZtypesZcore_u3043)(tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw kind_p0);
N_LIB_PRIVATE N_NOCONV(void*, alloc0Impl__system_u1759)(NI size_p0);
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2);
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZgeneZtypesZcore_u5056)(tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g** dest_p0, tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqwasMoved___OOZsrcZgeneZtypesZcore_u5042)(tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g** dest_p0);
static N_INLINE(tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA*, app__OOZsrcZgeneZtypesZcore_u5402)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ self_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZgeneZtypesZcore_u5411)(tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA** dest_p0, tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* src_p1);
static N_INLINE(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, to_ref_value__OOZsrcZgeneZtypesZcore_u3071)(tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* v_p0);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl__stdZassertions_u234)(NimStringV2 msg_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, eqdup___OOZsrcZgeneZtypesZcore_u105)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ src_p0);
static N_INLINE(void, X5BX5Deq___OOZsrcZgeneZtypesZcore_u74)(tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* self_p0, NI64 key_p1, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ val_p2);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq___OOZsrcZgeneZtypesZcore_u5883)(tyObject_Table__lszZnMlhqAeiHEXplgyxMg* t_p0, NI64 key_p1, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ val_p2);
static N_INLINE(NI64, to_key__OOZsrcZgeneZtypesZcore_u1881)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, to_symbol_value__OOZsrcZgeneZtypesZcore_u123)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
extern TNimTypeV2 NTIv2__0LTplYjqhVFXG6XBqdJOOg_;
static const struct {
  NI cap; NIM_CHAR data[24+1];
} TM__LXL6yWqSwJg42sh8gcJheg_2 = { 24 | NIM_STRLIT_FLAG, "Value is not a reference" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_3 = {24, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_2};
static const struct {
  NI cap; NIM_CHAR data[9+1];
} TM__LXL6yWqSwJg42sh8gcJheg_4 = { 9 | NIM_STRLIT_FLAG, "Generator" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_5 = {9, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_4};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__LXL6yWqSwJg42sh8gcJheg_6 = { 4 | NIM_STRLIT_FLAG, "next" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_7 = {4, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_6};
extern TNimTypeV2 NTIv2__LUq7TaB0iuPkr5UAFwNqGw_;
static const struct {
  NI cap; NIM_CHAR data[35+1];
} TM__LXL6yWqSwJg42sh8gcJheg_8 = { 35 | NIM_STRLIT_FLAG, "Generator.next requires a generator" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_9 = {35, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_8};
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__LXL6yWqSwJg42sh8gcJheg_11 = { 38 | NIM_STRLIT_FLAG, "next can only be called on a Generator" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_12 = {38, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_11};
static NIM_CONST tySet_tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw TM__LXL6yWqSwJg42sh8gcJheg_13 = {
0x00, 0x00, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[71+1];
} TM__LXL6yWqSwJg42sh8gcJheg_14 = { 71 | NIM_STRLIT_FLAG, "field \'generator\' is not accessible for type \'Reference\' using \'kind = " };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_15 = {71, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_14};
static const struct {
  NI cap; NIM_CHAR data[23+1];
} TM__LXL6yWqSwJg42sh8gcJheg_16 = { 23 | NIM_STRLIT_FLAG, "Generator object is nil" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_17 = {23, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_16};
static const struct {
  NI cap; NIM_CHAR data[8+1];
} TM__LXL6yWqSwJg42sh8gcJheg_18 = { 8 | NIM_STRLIT_FLAG, "has_next" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_19 = {8, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_18};
static const struct {
  NI cap; NIM_CHAR data[39+1];
} TM__LXL6yWqSwJg42sh8gcJheg_20 = { 39 | NIM_STRLIT_FLAG, "Generator.has_next requires a generator" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_21 = {39, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_20};
static const struct {
  NI cap; NIM_CHAR data[42+1];
} TM__LXL6yWqSwJg42sh8gcJheg_22 = { 42 | NIM_STRLIT_FLAG, "has_next can only be called on a Generator" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_23 = {42, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_22};
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_24 = {71, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_14};
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_25 = {23, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_16};
static NIM_CONST tySet_tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw TM__LXL6yWqSwJg42sh8gcJheg_26 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[67+1];
} TM__LXL6yWqSwJg42sh8gcJheg_27 = { 67 | NIM_STRLIT_FLAG, "field \'class\' is not accessible for type \'Reference\' using \'kind = " };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_28 = {67, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_27};
static NIM_CONST tySet_tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw TM__LXL6yWqSwJg42sh8gcJheg_29 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x08, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[65+1];
} TM__LXL6yWqSwJg42sh8gcJheg_30 = { 65 | NIM_STRLIT_FLAG, "field \'app\' is not accessible for type \'Reference\' using \'kind = " };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_31 = {65, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_30};
static const struct {
  NI cap; NIM_CHAR data[161+1];
} TM__LXL6yWqSwJg42sh8gcJheg_33 = { 161 | NIM_STRLIT_FLAG, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim(207, 3) `(ptr_addr and 0xFFFF000000000000\'u64) == 0` Reference pointer too large for NaN boxing" };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_34 = {161, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_33};
static NIM_CONST tySet_tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw TM__LXL6yWqSwJg42sh8gcJheg_35 = {
0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
0x00, 0x00}
;
static const struct {
  NI cap; NIM_CHAR data[64+1];
} TM__LXL6yWqSwJg42sh8gcJheg_36 = { 64 | NIM_STRLIT_FLAG, "field \'ns\' is not accessible for type \'Reference\' using \'kind = " };
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_37 = {64, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_36};
static const NimStringV2 TM__LXL6yWqSwJg42sh8gcJheg_38 = {9, (NimStrPayload*)&TM__LXL6yWqSwJg42sh8gcJheg_4};
extern NIM_CONST tyObject_Value__SWDx48y3phX6dE7KVcXeCQ NIL__OOZsrcZgeneZtypesZcore_u28;
extern NIM_CONST tyObject_Value__SWDx48y3phX6dE7KVcXeCQ NOT_FOUND__OOZsrcZgeneZtypesZcore_u33;
extern NIM_CONST tyObject_Value__SWDx48y3phX6dE7KVcXeCQ TRUE__OOZsrcZgeneZtypesZcore_u29;
extern NIM_CONST tyObject_Value__SWDx48y3phX6dE7KVcXeCQ FALSE__OOZsrcZgeneZtypesZcore_u30;
extern tySequence__aNpJjaoUowCQc7fBn3wtDQ VmCreatedCallbacks__OOZsrcZgeneZtypesZcore_u87;
extern tyObject_Value__SWDx48y3phX6dE7KVcXeCQ App__OOZsrcZgeneZtypesZcore_u79;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
static N_INLINE(tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*, ref__OOZsrcZgeneZtypesZcore_u3066)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ v_p0) {
	tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* result;
	tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* colontmpD_;
	NU64 u_1;
	union { tyObject_Value__SWDx48y3phX6dE7KVcXeCQ source; NU64 dest; } LOC1;
	nimfr_("ref", "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");
{	result = (tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*)0;
	colontmpD_ = (tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*)0;
	nimlf_(197, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");	LOC1.source = v_p0;
	u_1 = LOC1.dest;
	nimln_(198);	{
		if (!((NU64)(u_1 & 18446462598732840960ULL) == 18445618173802708992ULL)) goto LA4_;
		nimln_(199);		colontmpD_ = ((tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*) ((NU64)(u_1 & 281474976710655ULL)));
		result = colontmpD_;
	}
	goto LA2_;
LA4_: ;
	{
		tyObject_ValueError__0LTplYjqhVFXG6XBqdJOOg* T7_;
		T7_ = NIM_NIL;
		T7_ = (tyObject_ValueError__0LTplYjqhVFXG6XBqdJOOg*) nimNewObj(sizeof(tyObject_ValueError__0LTplYjqhVFXG6XBqdJOOg), NIM_ALIGNOF(tyObject_ValueError__0LTplYjqhVFXG6XBqdJOOg));
		(*T7_).Sup.Sup.Sup.m_type = (&NTIv2__0LTplYjqhVFXG6XBqdJOOg_);
		(*T7_).Sup.Sup.name = "ValueError";
		(*T7_).Sup.Sup.message = TM__LXL6yWqSwJg42sh8gcJheg_3;
		(*T7_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(201);		raiseExceptionEx((Exception*)T7_, "ValueError", "ref", "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim", 201);
goto BeforeRet_;
	}
LA2_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw, kind__OOZsrcZgeneZtypesZcore_u46)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ v_p0) {
	tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw result;
	NU64 u_1;
	union { tyObject_Value__SWDx48y3phX6dE7KVcXeCQ source; NU64 dest; } LOC1;
	NU64 tag_1;
NIM_BOOL* nimErr_;
	nimfr_("kind", "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");
{nimErr_ = nimErrorFlag();
	result = (tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)0;
	nimln_(315);	LOC1.source = v_p0;
	u_1 = LOC1.dest;
	nimln_(318);	{
		if (!!(((NU64)(u_1 & 18442240474082181120ULL) == 18442240474082181120ULL))) goto LA4_;
		nimln_(319);		nimln_(313);		nimln_(319);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)9);
		goto BeforeRet_;
	}
LA4_: ;
	nimln_(322);	tag_1 = (NU64)(u_1 & 18446462598732840960ULL);
	nimln_(323);	switch (tag_1) {
	case 18442803424035602432ULL:
	{
		nimln_(325);		nimln_(313);		nimln_(325);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)7);
		goto BeforeRet_;
	}
	break;
	case 18445618173802708992ULL:
	{
		tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* T8_;
		nimln_(327);		nimln_(313);		nimln_(327);		T8_ = (tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*)0;
		T8_ = ref__OOZsrcZgeneZtypesZcore_u3066(v_p0);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = (*T8_).kind;
		goto BeforeRet_;
	}
	break;
	case 18444492273895866368ULL:
	{
		nimln_(329);		nimln_(313);		nimln_(329);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)30);
		goto BeforeRet_;
	}
	break;
	case 18444773748872577024ULL:
	{
		nimln_(331);		nimln_(313);		nimln_(331);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)32);
		goto BeforeRet_;
	}
	break;
	case 18445055223849287680ULL:
	{
		nimln_(333);		nimln_(313);		nimln_(333);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)53);
		goto BeforeRet_;
	}
	break;
	case 18443084899012313088ULL:
	{
		nimln_(335);		nimln_(313);		nimln_(335);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)16);
		goto BeforeRet_;
	}
	break;
	case 18445899648779419648ULL:
	{
		nimln_(337);		nimln_(313);		nimln_(337);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)15);
		goto BeforeRet_;
	}
	break;
	case 18445336698825998336ULL:
	{
		nimln_(339);		nimln_(313);		nimln_(339);		result = ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)33);
		goto BeforeRet_;
	}
	break;
	default:
	{
		nimln_(342);		nimln_(313);		nimln_(342);		result = kind_slow__OOZsrcZgeneZtypesZcore_u3985(v_p0, u_1, tag_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	break;
	}
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL, nimAddInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) + (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ b_p1));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, get_positional_arg__OOZsrcZgeneZtypesZcore_u15954)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p0, NI index_p1, NIM_BOOL has_keyword_args_p2) {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ result;
	NI colontmpD_;
	NI colontmpD__2;
	NI offset_1;
	NI TM__LXL6yWqSwJg42sh8gcJheg_10;
NIM_BOOL* nimErr_;
	nimfr_("get_positional_arg", "/Users/gcao/gene-workspace/gene/src/gene/types/core/native_helpers.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	colontmpD_ = (NI)0;
	colontmpD__2 = (NI)0;
	nimlf_(25, "/Users/gcao/gene-workspace/gene/src/gene/types/core/native_helpers.nim");	{
		if (!has_keyword_args_p2) goto LA3_;
		colontmpD_ = ((NI)1);
		offset_1 = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		colontmpD__2 = ((NI)0);
		offset_1 = colontmpD__2;
	}
LA1_: ;
	nimln_(26);	nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");	nimlf_(26, "/Users/gcao/gene-workspace/gene/src/gene/types/core/native_helpers.nim");	if (nimAddInt(offset_1, index_p1, &TM__LXL6yWqSwJg42sh8gcJheg_10)) { raiseOverflow(); goto BeforeRet_;
	};
	nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");	eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&result), args_p0[(NI)(TM__LXL6yWqSwJg42sh8gcJheg_10)]);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, exec_generator__OOZsrcZgeneZvmZgenerator_u67)(tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* self_p0, tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* gen_p1) {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ result;
	nimfr_("exec_generator", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");
{	nimlf_(127, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	nimln_(125);	nimln_(127);	result = exec_generator_impl(self_p0, gen_p1);
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, generator_next__OOZsrcZgeneZvmZgenerator_u77)(tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p1, NI arg_count_p2, NIM_BOOL has_keyword_args_p3) {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ result;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ gen_arg_1;
	tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* gen_1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ result_2;
	tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* T13_;
NIM_BOOL oldNimErrFin25_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("generator_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	nimZeroMem((void*)(&gen_arg_1), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	gen_1 = NIM_NIL;
	nimZeroMem((void*)(&result_2), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	nimln_(37);	{
		tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw* T6_;
		if (!(arg_count_p2 < ((NI)1))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw*) nimNewObj(sizeof(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw), NIM_ALIGNOF(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__LUq7TaB0iuPkr5UAFwNqGw_);
		(*T6_).Sup.Sup.name = "Exception";
		(*T6_).Sup.Sup.message = TM__LXL6yWqSwJg42sh8gcJheg_9;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(38);		raiseExceptionEx((Exception*)T6_, "Exception", "generator_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim", 38);
goto LA1_;
	}
LA4_: ;
	nimln_(40);	gen_arg_1 = get_positional_arg__OOZsrcZgeneZtypesZcore_u15954(args_p1, ((NI)0), has_keyword_args_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(41);	{
		tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw T9_;
		tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw* T12_;
		T9_ = (tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)0;
		T9_ = kind__OOZsrcZgeneZtypesZcore_u46(gen_arg_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!((T9_ == ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)23)))) goto LA10_;
		T12_ = NIM_NIL;
		T12_ = (tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw*) nimNewObj(sizeof(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw), NIM_ALIGNOF(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw));
		(*T12_).Sup.Sup.Sup.m_type = (&NTIv2__LUq7TaB0iuPkr5UAFwNqGw_);
		(*T12_).Sup.Sup.name = "Exception";
		(*T12_).Sup.Sup.message = TM__LXL6yWqSwJg42sh8gcJheg_12;
		(*T12_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(42);		raiseExceptionEx((Exception*)T12_, "Exception", "generator_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim", 42);
goto LA1_;
	}
LA10_: ;
	nimln_(7);	nimln_(45);	T13_ = (tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*)0;
	T13_ = ref__OOZsrcZgeneZtypesZcore_u3066(gen_arg_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (!(((TM__LXL6yWqSwJg42sh8gcJheg_13[(NU)(((*T13_).kind))>>3] &(1U<<((NU)(((*T13_).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__LXL6yWqSwJg42sh8gcJheg_15, dollar___OOZsrcZgeneZtypesZtype95defs_u285((*T13_).kind)); goto LA1_;
	}
	nimln_(7);	eqcopy___OOZsrcZgeneZvmZgenerator_u17(&gen_1, (*T13_)._kind_28.generator, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(48);	{
		tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw* T18_;
		if (!(gen_1 == ((tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA*) NIM_NIL))) goto LA16_;
		T18_ = NIM_NIL;
		T18_ = (tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw*) nimNewObj(sizeof(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw), NIM_ALIGNOF(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw));
		(*T18_).Sup.Sup.Sup.m_type = (&NTIv2__LUq7TaB0iuPkr5UAFwNqGw_);
		(*T18_).Sup.Sup.name = "Exception";
		(*T18_).Sup.Sup.message = TM__LXL6yWqSwJg42sh8gcJheg_17;
		(*T18_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(49);		raiseExceptionEx((Exception*)T18_, "Exception", "generator_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim", 49);
goto LA1_;
	}
LA16_: ;
	nimln_(52);	{
		NIM_BOOL T21_;
		tyObject_Value__SWDx48y3phX6dE7KVcXeCQ val_1;
		T21_ = (NIM_BOOL)0;
		T21_ = !((gen_1 == ((tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA*) NIM_NIL)));
		if (!(T21_)) goto LA22_;
		T21_ = (*gen_1).has_peeked;
LA22_: ;
		if (!T21_) goto LA23_;
		nimZeroMem((void*)(&val_1), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
		nimln_(53);		(*gen_1).has_peeked = NIM_FALSE;
		nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&val_1), (*gen_1).peeked_value);
		if (NIM_UNLIKELY(*nimErr_)) goto LA25_;
		eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&(*gen_1).peeked_value), NIL__OOZsrcZgeneZtypesZcore_u28);
		if (NIM_UNLIKELY(*nimErr_)) goto LA25_;
		nimlf_(56, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		nimln_(35);		nimln_(56);		result = val_1;
		nimlf_(106, "/Users/gcao/gene-workspace/gene/src/gene/types/core.nim");		eqwasMoved___OOZsrcZgeneZtypesZcore_u102((&val_1));
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&val_1));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&result_2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
		{
			LA25_:;
		}
		{
			oldNimErrFin25_ = *nimErr_; *nimErr_ = NIM_FALSE;
			eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&val_1));
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin25_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA23_: ;
	nimlf_(59, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	{
		if (!(*gen_1).done) goto LA30_;
		nimln_(60);		nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&result), NOT_FOUND__OOZsrcZgeneZtypesZcore_u33);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimln_(179);		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&result_2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA30_: ;
	nimlf_(64, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	result_2 = exec_generator__OOZsrcZgeneZvmZgenerator_u67(vm_p0, gen_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(65);	nimln_(35);	nimln_(65);	result = result_2;
	nimlf_(106, "/Users/gcao/gene-workspace/gene/src/gene/types/core.nim");	eqwasMoved___OOZsrcZgeneZtypesZcore_u102((&result_2));
	nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");	eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&result_2));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");	eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	goto BeforeRet_;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&result_2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, generator_has_next__OOZsrcZgeneZvmZgenerator_u102)(tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p1, NI arg_count_p2, NIM_BOOL has_keyword_args_p3) {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ result;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ gen_arg_1;
	tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* gen_1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ next_val_1;
	tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* T13_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_("generator_has_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	nimZeroMem((void*)(&gen_arg_1), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	gen_1 = NIM_NIL;
	nimZeroMem((void*)(&next_val_1), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	nimlf_(69, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	{
		tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw* T6_;
		if (!(arg_count_p2 < ((NI)1))) goto LA4_;
		T6_ = NIM_NIL;
		T6_ = (tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw*) nimNewObj(sizeof(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw), NIM_ALIGNOF(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw));
		(*T6_).Sup.Sup.Sup.m_type = (&NTIv2__LUq7TaB0iuPkr5UAFwNqGw_);
		(*T6_).Sup.Sup.name = "Exception";
		(*T6_).Sup.Sup.message = TM__LXL6yWqSwJg42sh8gcJheg_21;
		(*T6_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(70);		raiseExceptionEx((Exception*)T6_, "Exception", "generator_has_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim", 70);
goto LA1_;
	}
LA4_: ;
	nimln_(72);	gen_arg_1 = get_positional_arg__OOZsrcZgeneZtypesZcore_u15954(args_p1, ((NI)0), has_keyword_args_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(73);	{
		tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw T9_;
		tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw* T12_;
		T9_ = (tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)0;
		T9_ = kind__OOZsrcZgeneZtypesZcore_u46(gen_arg_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!!((T9_ == ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)23)))) goto LA10_;
		T12_ = NIM_NIL;
		T12_ = (tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw*) nimNewObj(sizeof(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw), NIM_ALIGNOF(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw));
		(*T12_).Sup.Sup.Sup.m_type = (&NTIv2__LUq7TaB0iuPkr5UAFwNqGw_);
		(*T12_).Sup.Sup.name = "Exception";
		(*T12_).Sup.Sup.message = TM__LXL6yWqSwJg42sh8gcJheg_23;
		(*T12_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(74);		raiseExceptionEx((Exception*)T12_, "Exception", "generator_has_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim", 74);
goto LA1_;
	}
LA10_: ;
	nimln_(7);	nimln_(77);	T13_ = (tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*)0;
	T13_ = ref__OOZsrcZgeneZtypesZcore_u3066(gen_arg_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	if (!(((TM__LXL6yWqSwJg42sh8gcJheg_13[(NU)(((*T13_).kind))>>3] &(1U<<((NU)(((*T13_).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__LXL6yWqSwJg42sh8gcJheg_24, dollar___OOZsrcZgeneZtypesZtype95defs_u285((*T13_).kind)); goto LA1_;
	}
	nimln_(7);	eqcopy___OOZsrcZgeneZvmZgenerator_u17(&gen_1, (*T13_)._kind_28.generator, NIM_FALSE);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(80);	{
		tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw* T18_;
		if (!(gen_1 == ((tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA*) NIM_NIL))) goto LA16_;
		T18_ = NIM_NIL;
		T18_ = (tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw*) nimNewObj(sizeof(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw), NIM_ALIGNOF(tyObject_Exception__LUq7TaB0iuPkr5UAFwNqGw));
		(*T18_).Sup.Sup.Sup.m_type = (&NTIv2__LUq7TaB0iuPkr5UAFwNqGw_);
		(*T18_).Sup.Sup.name = "Exception";
		(*T18_).Sup.Sup.message = TM__LXL6yWqSwJg42sh8gcJheg_25;
		(*T18_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(81);		raiseExceptionEx((Exception*)T18_, "Exception", "generator_has_next", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim", 81);
goto LA1_;
	}
LA16_: ;
	nimln_(84);	{
		if (!(*gen_1).has_peeked) goto LA21_;
		nimln_(85);		nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&result), TRUE__OOZsrcZgeneZtypesZcore_u29);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimln_(179);		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&next_val_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA21_: ;
	nimlf_(88, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	{
		if (!(*gen_1).done) goto LA25_;
		nimln_(89);		nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&result), FALSE__OOZsrcZgeneZtypesZcore_u30);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimln_(179);		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&next_val_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA25_: ;
	nimlf_(92, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	next_val_1 = exec_generator__OOZsrcZgeneZvmZgenerator_u67(vm_p0, gen_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(96);	{
		NIM_BOOL T29_;
		T29_ = (NIM_BOOL)0;
		T29_ = eqeq___OOZsrcZgeneZtypesZcore_u48(next_val_1, NOT_FOUND__OOZsrcZgeneZtypesZcore_u33);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!T29_) goto LA30_;
		nimln_(99);		nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&result), FALSE__OOZsrcZgeneZtypesZcore_u30);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimln_(179);		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&next_val_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
	goto LA27_;
LA30_: ;
	{
		nimlf_(101, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		(*gen_1).has_peeked = NIM_TRUE;
		nimlf_(200, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqsink___OOZsrcZgeneZtypesZtype95defs_u7396((&(*gen_1).peeked_value), next_val_1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimlf_(106, "/Users/gcao/gene-workspace/gene/src/gene/types/core.nim");		eqwasMoved___OOZsrcZgeneZtypesZcore_u102((&next_val_1));
		nimlf_(103, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		nimlf_(185, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqcopy___OOZsrcZgeneZtypesZtype95defs_u7393((&result), TRUE__OOZsrcZgeneZtypesZcore_u29);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		nimln_(179);		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&next_val_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA27_: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&next_val_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(7, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");		eqdestroy___OOZsrcZgeneZvmZgenerator_u14(gen_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(179, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");		eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391((&gen_arg_1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, nimCopyMem)(void* dest_p0, void* source_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest_p0, source_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, copyMem__system_u1741)(void* dest_p0, void* source_p1, NI size_p2) {
	nimCopyMem(dest_p0, source_p1, size_p2);
}
static N_INLINE(tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*, new_ref__OOZsrcZgeneZtypesZcore_u3043)(tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw kind_p0) {
	tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* result;
	void* T1_;
	tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw k_1;
	nimfr_("new_ref", "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");
	nimlf_(189, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");	T1_ = (void*)0;
	T1_ = alloc0Impl__system_u1759(((NI)64));
	result = ((tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*) (T1_));
	nimln_(190);	(*result).ref_count = ((NI)1);
	nimln_(193);	k_1 = kind_p0;
	nimln_(194);	copyMem__system_u1741(((void*) ((NU)((NU64)(((NU) (ptrdiff_t) (result))) + (NU64)(((NU)8))))), ((void*) ((&k_1))), ((NI)2));
	popFrame();
	return result;
}
static N_INLINE(tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA*, app__OOZsrcZgeneZtypesZcore_u5402)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ self_p0) {
	tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* result;
	tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* T1_;
NIM_BOOL* nimErr_;
	nimfr_("app", "/Users/gcao/gene-workspace/gene/src/gene/types/core/collections.nim");
{nimErr_ = nimErrorFlag();
	result = NIM_NIL;
	nimlf_(12, "/Users/gcao/gene-workspace/gene/src/gene/types/core/collections.nim");	T1_ = (tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*)0;
	T1_ = ref__OOZsrcZgeneZtypesZcore_u3066(self_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	if (!(((TM__LXL6yWqSwJg42sh8gcJheg_29[(NU)(((*T1_).kind))>>3] &(1U<<((NU)(((*T1_).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__LXL6yWqSwJg42sh8gcJheg_31, dollar___OOZsrcZgeneZtypesZtype95defs_u285((*T1_).kind)); goto BeforeRet_;
	}
	eqcopy___OOZsrcZgeneZtypesZcore_u5411(&result, (*T1_)._kind_31.app);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, to_ref_value__OOZsrcZgeneZtypesZcore_u3071)(tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* v_p0) {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ result;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ colontmpD_;
	NI TM__LXL6yWqSwJg42sh8gcJheg_32;
	NU64 ptr_addr_1;
	union { NU64 source; tyObject_Value__SWDx48y3phX6dE7KVcXeCQ dest; } LOC5;
NIM_BOOL* nimErr_;
	nimfr_("to_ref_value", "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	nimlf_(204, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");	if (nimAddInt((*v_p0).ref_count, ((NI)1), &TM__LXL6yWqSwJg42sh8gcJheg_32)) { raiseOverflow(); goto BeforeRet_;
	};
	(*v_p0).ref_count = (NI)(TM__LXL6yWqSwJg42sh8gcJheg_32);
	nimln_(206);	ptr_addr_1 = ((NU64) (ptrdiff_t) (v_p0));
	nimln_(207);	{
		if (!!(((NU64)(ptr_addr_1 & 18446462598732840960ULL) == 0ULL))) goto LA3_;
		failedAssertImpl__stdZassertions_u234(TM__LXL6yWqSwJg42sh8gcJheg_34);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA3_: ;
	nimln_(208);	nimlf_(106, "/Users/gcao/gene-workspace/gene/src/gene/types/core.nim");	nimlf_(208, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");	LOC5.source = (NU64)(18445618173802708992ULL | ptr_addr_1);
	nimlf_(106, "/Users/gcao/gene-workspace/gene/src/gene/types/core.nim");	colontmpD_ = eqdup___OOZsrcZgeneZtypesZcore_u105(LOC5.dest);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = colontmpD_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(void, X5BX5Deq___OOZsrcZgeneZtypesZcore_u74)(tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* self_p0, NI64 key_p1, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ val_p2) {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ colontmpD_;
NIM_BOOL* nimErr_;
	nimfr_("[]=", "/Users/gcao/gene-workspace/gene/src/gene/types/core/collections.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	nimlf_(97, "/Users/gcao/gene-workspace/gene/src/gene/types/core/collections.nim");	nimlf_(106, "/Users/gcao/gene-workspace/gene/src/gene/types/core.nim");	colontmpD_ = eqdup___OOZsrcZgeneZtypesZcore_u105(val_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimlf_(97, "/Users/gcao/gene-workspace/gene/src/gene/types/core/collections.nim");	X5BX5Deq___OOZsrcZgeneZtypesZcore_u5883((&(*self_p0).members), key_p1, colontmpD_);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(98);	(*self_p0).version += ((NI)1);
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(NI64, to_key__OOZsrcZgeneZtypesZcore_u1881)(NimStringV2 s_p0) {
	NI64 result;
	union { tyObject_Value__SWDx48y3phX6dE7KVcXeCQ source; NI64 dest; } LOC1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ T2_;
NIM_BOOL* nimErr_;
	nimfr_("to_key", "/Users/gcao/gene-workspace/gene/src/gene/types/core/symbols.nim");
{nimErr_ = nimErrorFlag();
	result = (NI64)0;
	nimlf_(46, "/Users/gcao/gene-workspace/gene/src/gene/types/core/symbols.nim");	nimZeroMem((void*)(&T2_), sizeof(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ));
	T2_ = to_symbol_value__OOZsrcZgeneZtypesZcore_u123(s_p0);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391(&T2_); goto BeforeRet_;}
	LOC1.source = T2_;
	result = LOC1.dest;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, colonanonymous___OOZsrcZgeneZvmZgenerator_u71)(void) {
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* generator_class_1;
	tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* colontmpD_;
	tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* colontmpD__2;
	tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* generator_class_ref_1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ T9_;
NIM_BOOL oldNimErrFin15_;
NIM_BOOL oldNimErrFin1_;
NIM_BOOL* nimErr_;
	nimfr_(":anonymous", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");
{nimErr_ = nimErrorFlag();
	generator_class_1 = NIM_NIL;
	colontmpD_ = NIM_NIL;
	colontmpD__2 = NIM_NIL;
	nimlf_(29, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	{
		NIM_BOOL T4_;
		tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw T6_;
		T4_ = (NIM_BOOL)0;
		T4_ = eqeq___OOZsrcZgeneZtypesZcore_u48(App__OOZsrcZgeneZtypesZcore_u79, NIL__OOZsrcZgeneZtypesZcore_u28);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (T4_) goto LA5_;
		T6_ = (tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)0;
		T6_ = kind__OOZsrcZgeneZtypesZcore_u46(App__OOZsrcZgeneZtypesZcore_u79);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T4_ = !((T6_ == ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)43)));
LA5_: ;
		if (!T4_) goto LA7_;
		nimln_(30);		nimlf_(12, "/Users/gcao/gene-workspace/gene/src/gene/types/core/collections.nim");		eqdestroy___OOZsrcZgeneZtypesZcore_u5408(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZsrcZgeneZtypesZcore_u5408(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(189, "/Users/gcao/gene-workspace/gene/src/gene/types/core/constructors.nim");		eqdestroy___OOZsrcZgeneZtypesZcore_u5045(generator_class_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		goto BeforeRet_;
	}
LA7_: ;
	nimlf_(32, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	generator_class_1 = new_class__OOZsrcZgeneZtypesZclasses_u83(TM__LXL6yWqSwJg42sh8gcJheg_5);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(106);	def_native_method__OOZsrcZgeneZtypesZclasses_u619(generator_class_1, TM__LXL6yWqSwJg42sh8gcJheg_7, generator_next__OOZsrcZgeneZvmZgenerator_u77);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(107);	def_native_method__OOZsrcZgeneZtypesZclasses_u619(generator_class_1, TM__LXL6yWqSwJg42sh8gcJheg_19, generator_has_next__OOZsrcZgeneZvmZgenerator_u102);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(110);	generator_class_ref_1 = new_ref__OOZsrcZgeneZtypesZcore_u3043(((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)49));
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(189, "/Users/gcao/gene-workspace/gene/src/gene/types/core/constructors.nim");	if (!(((TM__LXL6yWqSwJg42sh8gcJheg_26[(NU)(((*generator_class_ref_1).kind))>>3] &(1U<<((NU)(((*generator_class_ref_1).kind))&7U)))!=0))) 	{ raiseFieldErrorStr(TM__LXL6yWqSwJg42sh8gcJheg_28, dollar___OOZsrcZgeneZtypesZtype95defs_u285((*generator_class_ref_1).kind)); goto LA1_;
	}
	eqsink___OOZsrcZgeneZtypesZcore_u5056(&(*generator_class_ref_1)._kind_37.class_0, generator_class_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	eqwasMoved___OOZsrcZgeneZtypesZcore_u5042(&generator_class_1);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(200, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");	nimlf_(112, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	colontmpD_ = app__OOZsrcZgeneZtypesZcore_u5402(App__OOZsrcZgeneZtypesZcore_u79);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T9_ = to_ref_value__OOZsrcZgeneZtypesZcore_u3071(generator_class_ref_1);
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZsrcZgeneZtypesZtype95defs_u7391(&T9_); goto LA1_;}
	nimlf_(200, "/Users/gcao/gene-workspace/gene/src/gene/types/memory.nim");	eqsink___OOZsrcZgeneZtypesZtype95defs_u7396((&(*colontmpD_).generator_class), T9_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimlf_(115, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	{
		tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw T12_;
		tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* colontmpD__3;
		tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* colontmpD__4;
		tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* T16_;
		NI64 T17_;
		colontmpD__2 = app__OOZsrcZgeneZtypesZcore_u5402(App__OOZsrcZgeneZtypesZcore_u79);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		T12_ = (tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)0;
		T12_ = kind__OOZsrcZgeneZtypesZcore_u46((*colontmpD__2).gene_ns);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(T12_ == ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)46))) goto LA13_;
		colontmpD__3 = NIM_NIL;
		colontmpD__4 = NIM_NIL;
		nimln_(116);		colontmpD__3 = app__OOZsrcZgeneZtypesZcore_u5402(App__OOZsrcZgeneZtypesZcore_u79);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		T16_ = (tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*)0;
		T16_ = ref__OOZsrcZgeneZtypesZcore_u3066((*colontmpD__3).gene_ns);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		if (!(((TM__LXL6yWqSwJg42sh8gcJheg_35[(NU)(((*T16_).kind))>>3] &(1U<<((NU)(((*T16_).kind))&7U)))!=0))) 		{ raiseFieldErrorStr(TM__LXL6yWqSwJg42sh8gcJheg_37, dollar___OOZsrcZgeneZtypesZtype95defs_u285((*T16_).kind)); goto LA15_;
		}
		T17_ = (NI64)0;
		T17_ = to_key__OOZsrcZgeneZtypesZcore_u1881(TM__LXL6yWqSwJg42sh8gcJheg_38);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		colontmpD__4 = app__OOZsrcZgeneZtypesZcore_u5402(App__OOZsrcZgeneZtypesZcore_u79);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		X5BX5Deq___OOZsrcZgeneZtypesZcore_u74((*T16_)._kind_34.ns, T17_, (*colontmpD__4).generator_class);
		if (NIM_UNLIKELY(*nimErr_)) goto LA15_;
		{
			LA15_:;
		}
		{
			oldNimErrFin15_ = *nimErr_; *nimErr_ = NIM_FALSE;
			nimlf_(12, "/Users/gcao/gene-workspace/gene/src/gene/types/core/collections.nim");			eqdestroy___OOZsrcZgeneZtypesZcore_u5408(colontmpD__4);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			eqdestroy___OOZsrcZgeneZtypesZcore_u5408(colontmpD__3);
			if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
			*nimErr_ = oldNimErrFin15_;
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA13_: ;
	{
		LA1_:;
	}
	{
		oldNimErrFin1_ = *nimErr_; *nimErr_ = NIM_FALSE;
		eqdestroy___OOZsrcZgeneZtypesZcore_u5408(colontmpD__2);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		eqdestroy___OOZsrcZgeneZtypesZcore_u5408(colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(189, "/Users/gcao/gene-workspace/gene/src/gene/types/core/constructors.nim");		eqdestroy___OOZsrcZgeneZtypesZcore_u5045(generator_class_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		*nimErr_ = oldNimErrFin1_;
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, init_generator__OOZsrcZgeneZvmZgenerator_u70)(void) {
	tyProc__HzVCwACFYM9cx9aV62PdjtuA T1_;
	nimfr_("init_generator", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");
	nimlf_(27, "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");	nimZeroMem((void*)(&T1_), sizeof(tyProc__HzVCwACFYM9cx9aV62PdjtuA));
	T1_.ClP_0 = ((TM__LXL6yWqSwJg42sh8gcJheg_39) (colonanonymous___OOZsrcZgeneZvmZgenerator_u71)); T1_.ClE_0 = NIM_NIL;
	add__system_u3931((&VmCreatedCallbacks__OOZsrcZgeneZtypesZcore_u87), T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atpgeneatsvmatsgeneratordotnim_Init000)(void) {
{
NIM_BOOL* nimErr_;
	nimfr_("generator", "/Users/gcao/gene-workspace/gene/src/gene/vm/generator.nim");
nimErr_ = nimErrorFlag();
	nimln_(119);	init_generator__OOZsrcZgeneZvmZgenerator_u70();
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

