/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_for_d/@pgene@snative@strampoline.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_for_d/@pgene@snative@strampoline.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ;
typedef struct tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA;
typedef struct tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA_Content tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA_Content;
typedef struct tyObject_Value__SWDx48y3phX6dE7KVcXeCQ tyObject_Value__SWDx48y3phX6dE7KVcXeCQ;
typedef struct tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w;
typedef struct tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ;
typedef struct tySequence__ZVX5BuQsLWKQ74s3Z6yxGA tySequence__ZVX5BuQsLWKQ74s3Z6yxGA;
typedef struct tySequence__ZVX5BuQsLWKQ74s3Z6yxGA_Content tySequence__ZVX5BuQsLWKQ74s3Z6yxGA_Content;
typedef struct tySequence__o1omg3X3DzA9bve4WDmfMUQ tySequence__o1omg3X3DzA9bve4WDmfMUQ;
typedef struct tySequence__o1omg3X3DzA9bve4WDmfMUQ_Content tySequence__o1omg3X3DzA9bve4WDmfMUQ_Content;
typedef struct tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg;
typedef struct tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ;
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ tySequence__sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ tySequence__6H5Oh5UUvVCLiakt9aTwtUQ;
typedef struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content;
typedef struct tySequence__z0sGq7A9cdKlr0udA70xFEw tySequence__z0sGq7A9cdKlr0udA70xFEw;
typedef struct tySequence__z0sGq7A9cdKlr0udA70xFEw_Content tySequence__z0sGq7A9cdKlr0udA70xFEw_Content;
typedef struct tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw;
typedef struct tySequence__dTyLQYzW1cGZoBBW67Gnmw tySequence__dTyLQYzW1cGZoBBW67Gnmw;
typedef struct tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content;
typedef struct tyObject_Table__lszZnMlhqAeiHEXplgyxMg tyObject_Table__lszZnMlhqAeiHEXplgyxMg;
typedef struct tySequence__YxXxm7F9cWRkm9bU9atASi80w tySequence__YxXxm7F9cWRkm9bU9atASi80w;
typedef struct tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content;
typedef struct tyObject_DocumentcolonObjectType___ZreCvWCNZGwXGf3saSD71Q tyObject_DocumentcolonObjectType___ZreCvWCNZGwXGf3saSD71Q;
typedef struct tyObject_Table__wSm1FEVkikY0Yro661FlBQ tyObject_Table__wSm1FEVkikY0Yro661FlBQ;
typedef struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ;
typedef struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content;
typedef struct tyObject_FutureObjcolonObjectType___lVyqvC6y9btmDx5f50djx7g tyObject_FutureObjcolonObjectType___lVyqvC6y9btmDx5f50djx7g;
typedef struct tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA;
typedef struct tyObject_ThreadcolonObjectType___9cw9c9a3NDm8mEB69bLkGLptZA tyObject_ThreadcolonObjectType___9cw9c9a3NDm8mEB69bLkGLptZA;
typedef struct tyObject_ThreadMessagecolonObjectType___bMgIvffznV2N1WxPcSJlTQ tyObject_ThreadMessagecolonObjectType___bMgIvffznV2N1WxPcSJlTQ;
typedef struct tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA;
typedef struct tyObject_PackagecolonObjectType___Rr5CWm4wKukVtN2EwbleRg tyObject_PackagecolonObjectType___Rr5CWm4wKukVtN2EwbleRg;
typedef struct tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg;
typedef struct tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg;
typedef struct tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew;
typedef struct tyObject_BlockcolonObjectType___5QIclX57MyQMOwdLXBLwLg tyObject_BlockcolonObjectType___5QIclX57MyQMOwdLXBLwLg;
typedef struct tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g;
typedef struct tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg;
typedef struct tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA;
typedef struct tyObject_EnumDefcolonObjectType___Oca059cdYCZ5x9b3TABVPstw tyObject_EnumDefcolonObjectType___Oca059cdYCZ5x9b3TABVPstw;
typedef struct tyObject_EnumMembercolonObjectType___L5PoYyd4vwGBveVneEMGjA tyObject_EnumMembercolonObjectType___L5PoYyd4vwGBveVneEMGjA;
typedef struct tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ;
typedef struct tyObject_ExceptionDatacolonObjectType___bpptbc0S9bvZvYEvMUQ3ccg tyObject_ExceptionDatacolonObjectType___bpptbc0S9bvZvYEvMUQ3ccg;
typedef struct tyObject_InterceptioncolonObjectType___eWAKsCNb6G1xztiG1V9bJVw tyObject_InterceptioncolonObjectType___eWAKsCNb6G1xztiG1V9bJVw;
typedef struct tyObject_AspectcolonObjectType___Zgz6QVVjTjizn1WiW59cVnQ tyObject_AspectcolonObjectType___Zgz6QVVjTjizn1WiW59cVnQ;
typedef struct tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA;
typedef struct tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA;
typedef struct tyObject_ScopeTrackercolonObjectType___R8lbBr1AIZQilD37aPAfug tyObject_ScopeTrackercolonObjectType___R8lbBr1AIZQilD37aPAfug;
typedef struct tyObject_FunctionDefInfocolonObjectType___SjMhC3kEgzLPHZSpJsyVbg tyObject_FunctionDefInfocolonObjectType___SjMhC3kEgzLPHZSpJsyVbg;
typedef struct tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA;
typedef struct tyObject_NativeFramecolonObjectType___re9aEd2LQ7lO1pRvhb09cQUQ tyObject_NativeFramecolonObjectType___re9aEd2LQ7lO1pRvhb09cQUQ;
typedef struct tyObject_CustomValuecolonObjectType___aoatYF31mo2xDG546n6qaw tyObject_CustomValuecolonObjectType___aoatYF31mo2xDG546n6qaw;
typedef struct tyObject_RootMatchercolonObjectType___e61awMfFi9c6AyAUUkocSiQ tyObject_RootMatchercolonObjectType___e61awMfFi9c6AyAUUkocSiQ;
typedef struct tyObject_ArrayObj__ZUI9aMYJjCR8k5zHYFn9bZVw tyObject_ArrayObj__ZUI9aMYJjCR8k5zHYFn9bZVw;
typedef struct tyObject_MapObj__vuqr6dIwnoKLD7d1BACBSw tyObject_MapObj__vuqr6dIwnoKLD7d1BACBSw;
typedef struct tyObject_InstanceObj__nb67a3w2PRfV6vq6rV2PgA tyObject_InstanceObj__nb67a3w2PRfV6vq6rV2PgA;
typedef struct tyObject_Gene__Pwxq5gyi6V5rsp5CSSAj9bw tyObject_Gene__Pwxq5gyi6V5rsp5CSSAj9bw;
typedef struct tyObject_SourceTracecolonObjectType___te8wA8IVE8b9bIWk7nD3vlQ tyObject_SourceTracecolonObjectType___te8wA8IVE8b9bIWk7nD3vlQ;
typedef struct tyObject_String__YA69alMlD9cVPI3T9ahGxam9cg tyObject_String__YA69alMlD9cVPI3T9ahGxam9cg;
typedef struct tyTuple__FPssS3c7hqLeL6Lb3a2P0g tyTuple__FPssS3c7hqLeL6Lb3a2P0g;
typedef struct tyTuple__fzfO9cZNjuQk2gYupM9aIG7w tyTuple__fzfO9cZNjuQk2gYupM9aIG7w;
typedef struct tyTuple__jZQK8lovE2CcAHYpGfxW3A tyTuple__jZQK8lovE2CcAHYpGfxW3A;
typedef struct tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ;
struct tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA {
  NI len; tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA_Content* p;
};
struct tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ {
	tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA data;
	NI counter;
};
typedef N_NIMCALL_PTR(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, tyProc__ohS1ljvA2eJrXrq8PifaPQ) (tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ* args_p1, NI arg_count_p2, NIM_BOOL has_keyword_args_p3);
struct tySequence__ZVX5BuQsLWKQ74s3Z6yxGA {
  NI len; tySequence__ZVX5BuQsLWKQ74s3Z6yxGA_Content* p;
};
typedef NU8 tyEnum_CallReturnType__sY4fSl2Fo9asz6s6JXC69aRQ;
struct tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ {
	tySequence__ZVX5BuQsLWKQ74s3Z6yxGA argTypes;
	tyEnum_CallReturnType__sY4fSl2Fo9asz6s6JXC69aRQ returnType;
};
struct tySequence__o1omg3X3DzA9bve4WDmfMUQ {
  NI len; tySequence__o1omg3X3DzA9bve4WDmfMUQ_Content* p;
};
struct tyObject_Value__SWDx48y3phX6dE7KVcXeCQ {
	NU64 raw;
};
struct tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ callable;
	tySequence__ZVX5BuQsLWKQ74s3Z6yxGA argTypes;
	tyEnum_CallReturnType__sY4fSl2Fo9asz6s6JXC69aRQ returnType;
};
typedef NU16 tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ {
  NI len; tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content* p;
};
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ {
  NI len; tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content* p;
};
struct tySequence__z0sGq7A9cdKlr0udA70xFEw {
  NI len; tySequence__z0sGq7A9cdKlr0udA70xFEw_Content* p;
};
struct tySequence__dTyLQYzW1cGZoBBW67Gnmw {
  NI len; tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content* p;
};
struct tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw {
	tySequence__dTyLQYzW1cGZoBBW67Gnmw data;
	NI counter;
};
struct tySequence__YxXxm7F9cWRkm9bU9atASi80w {
  NI len; tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content* p;
};
struct tyObject_Table__lszZnMlhqAeiHEXplgyxMg {
	tySequence__YxXxm7F9cWRkm9bU9atASi80w data;
	NI counter;
};
struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ {
  NI len; tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content* p;
};
struct tyObject_Table__wSm1FEVkikY0Yro661FlBQ {
	tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ data;
	NI counter;
};
struct tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ self;
	tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg* method_0;
};
typedef N_NIMCALL_PTR(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ, tyProc__Q9c4i3jiuHIlJvJtkyxxx4w) (tyObject_VirtualMachine__1gO9bCImPIYEkpokR9bZ506w* vm_p0, tyObject_Value__SWDx48y3phX6dE7KVcXeCQ gene_value_p1, tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ* caller_frame_p2);
typedef NU16 tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA;
struct tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA {
	tyEnum_InstructionKind__lnVD6Ivd9bsWb3Rw66TSYdA kind;
	NI16 label;
	NI32 arg1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ arg0;
};
struct tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ {
	NI ref_count;
	tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw kind;
union{
	struct {
	NimStringV2 str;
} _kind_1;
	struct {
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ csymbol;
} _kind_2;
	struct {
	NI64 ratio_num;
	NI64 ratio_denom;
} _kind_3;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bin_data;
	NU bin_bit_size;
} _kind_4;
	struct {
	NU64 bin64_data;
	NU bin64_bit_size;
} _kind_5;
	struct {
	NU8 byte_data;
	NU byte_bit_size;
} _kind_6;
	struct {
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ bytes_data;
} _kind_7;
	struct {
	NimStringV2 regex_pattern;
	NU8 regex_flags;
	NimStringV2 regex_replacement;
	NIM_BOOL regex_has_replacement;
} _kind_8;
	struct {
	NimStringV2 regex_match_value;
	tySequence__sM4lkSb7zS6F7OVMvW9cffQ regex_match_captures;
	NI64 regex_match_start;
	NI64 regex_match_end;
} _kind_9;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ range_start;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ range_end;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ range_step;
} _kind_10;
	struct {
	NimStringV2 selector_pattern;
	tySequence__z0sGq7A9cdKlr0udA70xFEw selector_path;
} _kind_11;
	struct {
	NI16 date_year;
	NI8 date_month;
	NI8 date_day;
} _kind_12;
	struct {
	NI16 dt_year;
	NI8 dt_month;
	NI8 dt_day;
	NI8 dt_hour;
	NI8 dt_minute;
	NI8 dt_second;
	NI16 dt_timezone;
} _kind_13;
	struct {
	NI8 time_hour;
	NI8 time_minute;
	NI8 time_second;
	NI32 time_microsecond;
} _kind_14;
	struct {
	NI16 tz_offset;
	NimStringV2 tz_name;
} _kind_15;
	struct {
	tyObject_HashSet__QopNzf7TRE2krzPvTqDhAw set;
} _kind_16;
	struct {
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg map;
} _kind_17;
	struct {
	tySequence__z0sGq7A9cdKlr0udA70xFEw stream;
	NI64 stream_index;
	NIM_BOOL stream_ended;
} _kind_18;
	struct {
	tyObject_DocumentcolonObjectType___ZreCvWCNZGwXGf3saSD71Q* doc;
} _kind_19;
	struct {
	NimStringV2 file_path;
	tySequence__6H5Oh5UUvVCLiakt9aTwtUQ file_content;
	NU16 file_permissions;
} _kind_20;
	struct {
	NimStringV2 arc_path;
	tyObject_Table__wSm1FEVkikY0Yro661FlBQ arc_members;
} _kind_21;
	struct {
	NimStringV2 dir_path;
	tyObject_Table__wSm1FEVkikY0Yro661FlBQ dir_members;
} _kind_22;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ quote;
} _kind_23;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ unquote;
	NIM_BOOL unquote_discard;
} _kind_24;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ ref_target;
} _kind_25;
	struct {
	NI64 target_id;
} _kind_26;
	struct {
	tyObject_FutureObjcolonObjectType___lVyqvC6y9btmDx5f50djx7g* future;
} _kind_27;
	struct {
	tyObject_GeneratorObjcolonObjectType___MIaepHcKYq729azPu5FxgGA* generator;
} _kind_28;
	struct {
	tyObject_ThreadcolonObjectType___9cw9c9a3NDm8mEB69bLkGLptZA* thread;
} _kind_29;
	struct {
	tyObject_ThreadMessagecolonObjectType___bMgIvffznV2N1WxPcSJlTQ* thread_message;
} _kind_30;
	struct {
	tyObject_ApplicationcolonObjectType___toGzAYW9a1ucsGKy4tHSDPA* app;
} _kind_31;
	struct {
	tyObject_PackagecolonObjectType___Rr5CWm4wKukVtN2EwbleRg* pkg;
} _kind_32;
	struct {
	tyObject_ModulecolonObjectType___1bummaZvZ2nqEsNfE41GFg* module;
} _kind_33;
	struct {
	tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* ns;
} _kind_34;
	struct {
	tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew* fn;
} _kind_35;
	struct {
	tyObject_BlockcolonObjectType___5QIclX57MyQMOwdLXBLwLg* block_0;
} _kind_36;
	struct {
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* class_0;
} _kind_37;
	struct {
	tyObject_MethodcolonObjectType___xjgsyjmojkAWynmdzggVWg* method_0;
} _kind_38;
	struct {
	tyObject_BoundMethod__Q6qg8yjom1vhFlsLBLFWBA bound_method;
} _kind_39;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ super_instance;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* super_class;
} _kind_40;
	struct {
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ cast_value;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* cast_class;
} _kind_41;
	struct {
	tyObject_EnumDefcolonObjectType___Oca059cdYCZ5x9b3TABVPstw* enum_def;
} _kind_42;
	struct {
	tyObject_EnumMembercolonObjectType___L5PoYyd4vwGBveVneEMGjA* enum_member;
} _kind_43;
	struct {
	tyProc__ohS1ljvA2eJrXrq8PifaPQ native_fn;
} _kind_44;
	struct {
	tyProc__Q9c4i3jiuHIlJvJtkyxxx4w native_macro;
} _kind_45;
	struct {
	tyProc__ohS1ljvA2eJrXrq8PifaPQ native_method;
} _kind_46;
	struct {
	tyObject_ExceptionDatacolonObjectType___bpptbc0S9bvZvYEvMUQ3ccg* exception_data;
} _kind_47;
	struct {
	tyObject_InterceptioncolonObjectType___eWAKsCNb6G1xztiG1V9bJVw* interception;
} _kind_48;
	struct {
	tyObject_AspectcolonObjectType___Zgz6QVVjTjizn1WiW59cVnQ* aspect;
} _kind_49;
	struct {
	NimStringV2 json_data;
} _kind_50;
	struct {
	FILE* native_file;
} _kind_51;
	struct {
	tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA* cu;
} _kind_52;
	struct {
	tyObject_Instruction__auXG4wDM52ksgVvDCeI9ciA instr;
} _kind_53;
	struct {
	tyObject_ScopeTrackercolonObjectType___R8lbBr1AIZQilD37aPAfug* scope_tracker;
} _kind_54;
	struct {
	tyObject_FunctionDefInfocolonObjectType___SjMhC3kEgzLPHZSpJsyVbg* function_def;
} _kind_55;
	struct {
	tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA* scope;
} _kind_56;
	struct {
	tyObject_FrameObj__8DhZVOVgm5m4DhFXrbxZcQ* frame;
} _kind_57;
	struct {
	tyObject_NativeFramecolonObjectType___re9aEd2LQ7lO1pRvhb09cQUQ* native_frame;
} _kind_58;
	struct {
	void* any_data;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* any_class;
} _kind_59;
	struct {
	tyObject_CustomValuecolonObjectType___aoatYF31mo2xDG546n6qaw* custom_data;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* custom_class;
} _kind_60;
};
};
struct tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew {
	NIM_BOOL async;
	NIM_BOOL is_generator;
	NIM_BOOL is_macro_like;
	NimStringV2 name;
	tyObject_NamespacecolonObjectType___43pR9bkZLEiSEDqnOI7VtXg* ns;
	tyObject_ScopeTrackercolonObjectType___R8lbBr1AIZQilD37aPAfug* scope_tracker;
	tyObject_ScopeObj__Nb3RO58LyFbYurWeRWC7HA* parent_scope;
	tyObject_RootMatchercolonObjectType___e61awMfFi9c6AyAUUkocSiQ* matcher;
	tySequence__z0sGq7A9cdKlr0udA70xFEw body;
	tyObject_CompilationUnitcolonObjectType___PDHEMu9aOyVFWN8Jy8M56lA* body_compiled;
	void* native_entry;
	NIM_BOOL native_ready;
	NIM_BOOL native_failed;
	NIM_BOOL native_return_float;
	tySequence__o1omg3X3DzA9bve4WDmfMUQ native_descriptors;
};
struct tyObject_ArrayObj__ZUI9aMYJjCR8k5zHYFn9bZVw {
	NI ref_count;
	tySequence__z0sGq7A9cdKlr0udA70xFEw arr;
};
struct tyObject_MapObj__vuqr6dIwnoKLD7d1BACBSw {
	NI ref_count;
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg map;
};
struct tyObject_InstanceObj__nb67a3w2PRfV6vq6rV2PgA {
	NI ref_count;
	tyObject_ClasscolonObjectType___qkYe0t1Hr0dzDoPyrmFp3g* instance_class;
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg instance_props;
};
struct tyObject_Gene__Pwxq5gyi6V5rsp5CSSAj9bw {
	NI ref_count;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ type_0;
	tyObject_SourceTracecolonObjectType___te8wA8IVE8b9bIWk7nD3vlQ* trace;
	tyObject_Table__lszZnMlhqAeiHEXplgyxMg props;
	tySequence__z0sGq7A9cdKlr0udA70xFEw children;
};
struct tyObject_String__YA69alMlD9cVPI3T9ahGxam9cg {
	NI ref_count;
	NimStringV2 str;
};
struct tyTuple__FPssS3c7hqLeL6Lb3a2P0g {
	NI Field0;
	void* Field1;
	tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ Field2;
};
struct tySequence__PkxYCZtiW2mQ9cu9c0b8yUEA_Content { NI cap; tyTuple__FPssS3c7hqLeL6Lb3a2P0g data[SEQ_DECL_SIZE]; };
typedef NU8 tyEnum_CallArgType__DVRs9bWS86Z42I9b6AKoKUQA;
struct tySequence__ZVX5BuQsLWKQ74s3Z6yxGA_Content { NI cap; tyEnum_CallArgType__DVRs9bWS86Z42I9b6AKoKUQA data[SEQ_DECL_SIZE]; };
struct tySequence__o1omg3X3DzA9bve4WDmfMUQ_Content { NI cap; tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg data[SEQ_DECL_SIZE]; };
struct tySequence__sM4lkSb7zS6F7OVMvW9cffQ_Content { NI cap; NimStringV2 data[SEQ_DECL_SIZE]; };
struct tySequence__6H5Oh5UUvVCLiakt9aTwtUQ_Content { NI cap; NU8 data[SEQ_DECL_SIZE]; };
struct tySequence__z0sGq7A9cdKlr0udA70xFEw_Content { NI cap; tyObject_Value__SWDx48y3phX6dE7KVcXeCQ data[SEQ_DECL_SIZE]; };
struct tyTuple__fzfO9cZNjuQk2gYupM9aIG7w {
	NI Field0;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ Field1;
};
struct tySequence__dTyLQYzW1cGZoBBW67Gnmw_Content { NI cap; tyTuple__fzfO9cZNjuQk2gYupM9aIG7w data[SEQ_DECL_SIZE]; };
struct tyTuple__jZQK8lovE2CcAHYpGfxW3A {
	NI Field0;
	NI64 Field1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ Field2;
};
struct tySequence__YxXxm7F9cWRkm9bU9atASi80w_Content { NI cap; tyTuple__jZQK8lovE2CcAHYpGfxW3A data[SEQ_DECL_SIZE]; };
struct tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ {
	NI Field0;
	NimStringV2 Field1;
	tyObject_Value__SWDx48y3phX6dE7KVcXeCQ Field2;
};
struct tySequence__sIFSL9aoVEZ4Y9bwpSVlLE9bQ_Content { NI cap; tyTuple__FzW8W2GK9bbSKaDqpmVbhnQ data[SEQ_DECL_SIZE]; };
N_LIB_PRIVATE N_NIMCALL(tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ, initTable__OOZsrcZgeneZnativeZtrampoline_u24)(NI initialSize_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZnativeZtrampoline_u163)(tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ* dest_p0);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains__OOZsrcZgeneZnativeZtrampoline_u1538)(tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ t_p0, void* key_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZgeneZnativeZtrampoline_u1082)(tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ* dest_p0, tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZgeneZtypesZtype95defs_u5336)(tySequence__ZVX5BuQsLWKQ74s3Z6yxGA* dest_p0, tySequence__ZVX5BuQsLWKQ74s3Z6yxGA src_p1);
N_LIB_PRIVATE N_NIMCALL(tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ*, X5BX5D___OOZsrcZgeneZnativeZtrampoline_u1621)(tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ* t_p0, void* key_p1);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZtypesZtype95defs_u5333)(tySequence__ZVX5BuQsLWKQ74s3Z6yxGA dest_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
static N_INLINE(void, release__OOZsrcZgeneZtypesZcore_u2111)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ v_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZgeneZtypesZtype95defs_u5315)(tySequence__o1omg3X3DzA9bve4WDmfMUQ* dest_p0, tySequence__o1omg3X3DzA9bve4WDmfMUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZtypesZtype95defs_u5312)(tySequence__o1omg3X3DzA9bve4WDmfMUQ dest_p0);
N_LIB_PRIVATE N_NIMCALL(void, eqsink___OOZsrcZgeneZtypesZtype95defs_u5321)(tySequence__o1omg3X3DzA9bve4WDmfMUQ* dest_p0, tySequence__o1omg3X3DzA9bve4WDmfMUQ src_p1);
N_LIB_PRIVATE N_NIMCALL(void*, newSeqPayload)(NI cap_p0, NI elemSize_p1, NI elemAlign_p2);
N_LIB_PRIVATE N_NIMCALL(void, reset__OOZsrcZgeneZtypesZtype95defs_u3220)(tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* obj_p0);
N_LIB_PRIVATE N_NOCONV(void, dealloc)(void* p_p0);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
N_LIB_PRIVATE tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ native_fn_sigs__OOZsrcZgeneZnativeZtrampoline_u221;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(void, eqcopy___OOZsrcZgeneZnativeZtrampoline_u1082)(tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ* dest_p0, tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ src_p1) {
	eqcopy___OOZsrcZgeneZtypesZtype95defs_u5336((&(*dest_p0).argTypes), src_p1.argTypes);
	(*dest_p0).returnType = src_p1.returnType;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, lookup_native_sig__OOZsrcZgeneZnativeZtrampoline_u1495)(tyProc__ohS1ljvA2eJrXrq8PifaPQ fn_p0, tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ* sig_p1) {
	NIM_BOOL result;
	void* key_1;
NIM_BOOL* nimErr_;
	nimfr_("lookup_native_sig", "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(16, "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");	key_1 = ((void*) (fn_p0));
	nimln_(17);	{
		NIM_BOOL T3_;
		tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ* T6_;
		T3_ = (NIM_BOOL)0;
		T3_ = contains__OOZsrcZgeneZnativeZtrampoline_u1538(native_fn_sigs__OOZsrcZgeneZnativeZtrampoline_u221, key_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!T3_) goto LA4_;
		nimlf_(170, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		nimlf_(18, "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");		T6_ = (tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ*)0;
		T6_ = X5BX5D___OOZsrcZgeneZnativeZtrampoline_u1621((&native_fn_sigs__OOZsrcZgeneZnativeZtrampoline_u221), key_1);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimlf_(170, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");		eqcopy___OOZsrcZgeneZnativeZtrampoline_u1082((&(*sig_p1)), (*T6_));
		nimlf_(19, "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");		nimln_(15);		nimln_(19);		result = NIM_TRUE;
		goto BeforeRet_;
	}
LA4_: ;
	result = NIM_FALSE;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___OOZsrcZgeneZnativeZtrampoline_u1079)(tyObject_NativeFnSig__9coMVaNu0TURtIeAFTqUmAQ* dest_p0) {
	eqdestroy___OOZsrcZgeneZtypesZtype95defs_u5333((*dest_p0).argTypes);
}
static N_INLINE(void, release__OOZsrcZgeneZtypesZcore_u2111)(tyObject_Value__SWDx48y3phX6dE7KVcXeCQ v_p0) {
	NU64 u_1;
	union { tyObject_Value__SWDx48y3phX6dE7KVcXeCQ source; NU64 dest; } LOC1;
NIM_BOOL* nimErr_;
	nimfr_("release", "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");
{nimErr_ = nimErrorFlag();
	nimlf_(83, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");	LOC1.source = v_p0;
	u_1 = LOC1.dest;
	nimln_(84);	{
		if (!((NU64)(u_1 & 18442240474082181120ULL) == 18442240474082181120ULL)) goto LA4_;
		nimln_(85);		switch ((NU64)(u_1 & 18446462598732840960ULL)) {
		case 18445618173802708992ULL:
		{
			tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ* x_1;
			nimln_(87);			x_1 = ((tyObject_Reference__FzzUxagezBuL6u6X8t1zMQ*) ((NU64)(u_1 & 281474976710655ULL)));
			nimln_(88);			{
				if (!((*x_1).ref_count == ((NI)1))) goto LA9_;
				nimln_(89);				{
					NIM_BOOL T13_;
					NIM_BOOL T14_;
					NI T17_;
					tySequence__o1omg3X3DzA9bve4WDmfMUQ T24_;
					T13_ = (NIM_BOOL)0;
					T14_ = (NIM_BOOL)0;
					T14_ = ((*x_1).kind == ((tyEnum_ValueKind__81uaTl5D0Ru9a8K7z2KQjIw)47));
					if (!(T14_)) goto LA15_;
					T14_ = !(((*x_1)._kind_35.fn == ((tyObject_FunctioncolonObjectType___1ubNEPxLyy2L6uFAqqQJew*) NIM_NIL)));
LA15_: ;
					T13_ = T14_;
					if (!(T13_)) goto LA16_;
					T17_ = (*(*x_1)._kind_35.fn).native_descriptors.len;
					T13_ = (((NI)0) < T17_);
LA16_: ;
					if (!T13_) goto LA18_;
					{
						tySequence__o1omg3X3DzA9bve4WDmfMUQ colontmp_;
						tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg* desc_1;
						NI i_1;
						NI L_1;
						NI T21_;
						colontmp_.len = 0; colontmp_.p = NIM_NIL;
						desc_1 = (tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg*)0;
						nimlf_(934, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");						eqcopy___OOZsrcZgeneZtypesZtype95defs_u5315((&colontmp_), (*(*x_1)._kind_35.fn).native_descriptors);
						nimlf_(249, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");						i_1 = ((NI)0);
						nimln_(250);						T21_ = colontmp_.len;
						L_1 = T21_;
						{
							nimln_(251);							while (1) {
								if (!(i_1 < L_1)) goto LA23;
								nimlf_(90, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");								desc_1 = (&colontmp_.p->data[i_1]);
								nimln_(91);								release__OOZsrcZgeneZtypesZcore_u2111((*desc_1).callable);
								if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
								nimlf_(13, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");								i_1 += ((NI)1);
							} LA23: ;
						}
						nimlf_(934, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");						eqdestroy___OOZsrcZgeneZtypesZtype95defs_u5312(colontmp_);
					}
					T24_.len = 0; T24_.p = NIM_NIL;
					T24_.len = 0; T24_.p = (tySequence__o1omg3X3DzA9bve4WDmfMUQ_Content*) newSeqPayload(0, sizeof(tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg), NIM_ALIGNOF(tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg));
					eqsink___OOZsrcZgeneZtypesZtype95defs_u5321((&(*(*x_1)._kind_35.fn).native_descriptors), T24_);
				}
LA18_: ;
				nimlf_(93, "/Users/gcao/gene-workspace/gene/src/gene/types/core/value_ops.nim");				reset__OOZsrcZgeneZtypesZtype95defs_u3220(x_1);
				nimln_(94);				dealloc(((void*) (x_1)));
			}
			goto LA7_;
LA9_: ;
			{
				nimln_(96);				(*x_1).ref_count -= ((NI)1);
			}
LA7_: ;
		}
		break;
		case 18444492273895866368ULL:
		{
			tyObject_ArrayObj__ZUI9aMYJjCR8k5zHYFn9bZVw* x_2;
			nimln_(98);			x_2 = ((tyObject_ArrayObj__ZUI9aMYJjCR8k5zHYFn9bZVw*) ((NU64)(u_1 & 281474976710655ULL)));
			nimln_(99);			{
				if (!((*x_2).ref_count == ((NI)1))) goto LA29_;
				nimln_(100);				dealloc(((void*) (x_2)));
			}
			goto LA27_;
LA29_: ;
			{
				nimln_(102);				(*x_2).ref_count -= ((NI)1);
			}
LA27_: ;
		}
		break;
		case 18444773748872577024ULL:
		{
			tyObject_MapObj__vuqr6dIwnoKLD7d1BACBSw* x_3;
			nimln_(104);			x_3 = ((tyObject_MapObj__vuqr6dIwnoKLD7d1BACBSw*) ((NU64)(u_1 & 281474976710655ULL)));
			nimln_(105);			{
				if (!((*x_3).ref_count == ((NI)1))) goto LA35_;
				nimln_(106);				dealloc(((void*) (x_3)));
			}
			goto LA33_;
LA35_: ;
			{
				nimln_(108);				(*x_3).ref_count -= ((NI)1);
			}
LA33_: ;
		}
		break;
		case 18445055223849287680ULL:
		{
			tyObject_InstanceObj__nb67a3w2PRfV6vq6rV2PgA* x_4;
			nimln_(110);			x_4 = ((tyObject_InstanceObj__nb67a3w2PRfV6vq6rV2PgA*) ((NU64)(u_1 & 281474976710655ULL)));
			nimln_(111);			{
				if (!((*x_4).ref_count == ((NI)1))) goto LA41_;
				nimln_(112);				dealloc(((void*) (x_4)));
			}
			goto LA39_;
LA41_: ;
			{
				nimln_(114);				(*x_4).ref_count -= ((NI)1);
			}
LA39_: ;
		}
		break;
		case 18445336698825998336ULL:
		{
			tyObject_Gene__Pwxq5gyi6V5rsp5CSSAj9bw* x_5;
			nimln_(116);			x_5 = ((tyObject_Gene__Pwxq5gyi6V5rsp5CSSAj9bw*) ((NU64)(u_1 & 281474976710655ULL)));
			nimln_(117);			{
				if (!((*x_5).ref_count == ((NI)1))) goto LA47_;
				nimln_(118);				dealloc(((void*) (x_5)));
			}
			goto LA45_;
LA47_: ;
			{
				nimln_(120);				(*x_5).ref_count -= ((NI)1);
			}
LA45_: ;
		}
		break;
		case 18445899648779419648ULL:
		{
			tyObject_String__YA69alMlD9cVPI3T9ahGxam9cg* x_6;
			nimln_(122);			x_6 = ((tyObject_String__YA69alMlD9cVPI3T9ahGxam9cg*) ((NU64)(u_1 & 281474976710655ULL)));
			nimln_(123);			{
				if (!!((x_6 == 0))) goto LA53_;
				nimln_(124);				{
					if (!((*x_6).ref_count == ((NI)1))) goto LA57_;
					nimln_(125);					dealloc(((void*) (x_6)));
				}
				goto LA55_;
LA57_: ;
				{
					nimln_(127);					(*x_6).ref_count -= ((NI)1);
				}
LA55_: ;
			}
LA53_: ;
		}
		break;
		default:
		{
		}
		break;
		}
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, release_descriptors__OOZsrcZgeneZnativeZtrampoline_u1707)(tySequence__o1omg3X3DzA9bve4WDmfMUQ descs_p0) {
NIM_BOOL* nimErr_;
	nimfr_("release_descriptors", "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");
{nimErr_ = nimErrorFlag();
	{
		tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg* desc_1;
		NI i_1;
		NI L_1;
		NI T2_;
		desc_1 = (tyObject_CallDescriptor__69bN2PpfP1D9bmWJyV5rWurg*)0;
		nimlf_(249, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");		i_1 = ((NI)0);
		nimln_(250);		T2_ = descs_p0.len;
		L_1 = T2_;
		{
			nimln_(251);			while (1) {
				if (!(i_1 < L_1)) goto LA4;
				nimlf_(23, "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");				if (i_1 < 0 || i_1 >= descs_p0.len){ raiseIndexError2(i_1,descs_p0.len-1); goto BeforeRet_;
				}
				desc_1 = (&descs_p0.p->data[i_1]);
				nimln_(24);				release__OOZsrcZgeneZtypesZcore_u2111((*desc_1).callable);
				if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
				nimlf_(13, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/iterators.nim");				i_1 += ((NI)1);
			} LA4: ;
		}
	}
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, atpgeneatsnativeatstrampolinedotnim_Init000)(void) {
{
	tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ T1_;
NIM_BOOL* nimErr_;
	nimfr_("trampoline", "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");
nimErr_ = nimErrorFlag();
	nimlf_(10, "/Users/gcao/gene-workspace/gene/src/gene/native/trampoline.nim");	nimZeroMem((void*)(&T1_), sizeof(tyObject_Table__0wWjNaedNlib9cG0LmUWfAQ));
	T1_ = initTable__OOZsrcZgeneZnativeZtrampoline_u24(((NI)32));
	if (NIM_UNLIKELY(*nimErr_)) {eqdestroy___OOZsrcZgeneZnativeZtrampoline_u163(&T1_); goto BeforeRet_;}
	native_fn_sigs__OOZsrcZgeneZnativeZtrampoline_u221 = T1_;
	BeforeRet_: ;
	nimTestErrorFlag();
	popFrame();
}
}

