/* Generated by Nim Compiler v2.2.6 */
/* Compiled for: MacOSX, arm64, clang */
/* Command for C compiler:
   clang -c  -w -ferror-limit=3 -fno-strict-aliasing -pthread   -I/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib -I/Users/gcao/gene-workspace/gene/tests -o /Users/gcao/gene-workspace/gene/.cache/nim/test_basic_d/@pnativesockets.nim.c.o /Users/gcao/gene-workspace/gene/.cache/nim/test_basic_d/@pnativesockets.nim.c */
#define NIM_INTBITS 64
#define NIM_EmulateOverflowChecks

#include "nimbase.h"
#include <sys/socket.h>
#include <unistd.h>
#include <netdb.h>
#include <string.h>
#include <netinet/in.h>
#include <fcntl.h>
#include <arpa/inet.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix
#define nimfr_(proc, file) \
  TFrame FR_; \
  FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

#define nimln_(n) \
  FR_.line = n;

#define nimlf_(n, file) \
  FR_.line = n; FR_.filename = file;

typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;
typedef struct tyObject_Option__HkGQcSC59b0olZFJtIthLew tyObject_Option__HkGQcSC59b0olZFJtIthLew;
typedef struct tyObject_HSlice__AztZM0sPNheK229at11oVrA tyObject_HSlice__AztZM0sPNheK229at11oVrA;
typedef struct tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ;
typedef struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimTypeV2 TNimTypeV2;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA tySequence__ObNb3ZkQVfF9aSBtrVROGjA;
typedef struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content;
typedef struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g;
typedef NU8 tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA;
typedef NU8 tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg;
struct NimStrPayload {
	NI cap;
	NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
	NI len;
	NimStrPayload* p;
};
typedef NU8 tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw;
struct tyObject_Option__HkGQcSC59b0olZFJtIthLew {
	tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw val;
	NIM_BOOL has;
};
typedef NIM_CHAR tyArray__dTlC27m9c9aWd5dvuePYanug[256];
typedef NIM_CHAR tyArray__Wfh9bjgBQ4UqJsyISUuDSuA[16];
struct tyObject_HSlice__AztZM0sPNheK229at11oVrA {
	NI a;
	NI b;
};
struct TNimTypeV2 {
	void* destructor;
	NI size;
	NI16 align;
	NI16 depth;
	NU32* display;
	void* traceImpl;
	void* typeInfoV1;
	NI flags;
	void* vTable[SEQ_DECL_SIZE];
};
struct RootObj {
	TNimTypeV2* m_type;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA {
  NI len; tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content* p;
};
struct Exception {
	RootObj Sup;
	Exception* parent;
	NCSTRING name;
	NimStringV2 message;
	tySequence__ObNb3ZkQVfF9aSBtrVROGjA trace;
	Exception* up;
};
struct tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A {
	Exception Sup;
};
struct tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ {
	tyObject_CatchableError__AILNJ2lpMc9cJLHbPUVox3A Sup;
};
struct tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g {
	NCSTRING procname;
	NI line;
	NCSTRING filename;
};
struct tySequence__ObNb3ZkQVfF9aSBtrVROGjA_Content { NI cap; tyObject_StackTraceEntry__zRPEjYjLjW4k2MnZ9cfCb1g data[SEQ_DECL_SIZE]; };
static N_INLINE(NIM_BOOL, setInheritable__pureZnativesockets_u206)(int s_p0, NIM_BOOL inheritable_p1);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, setInheritable__stdZsyncio_u286)(int f_p0, NIM_BOOL inheritable_p1);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
static N_INLINE(void, nimFrame)(TFrame* s_p0);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__system_u4625)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, close__pureZnativesockets_u201)(int socket_p0);
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1);
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2);
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u60)(tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw domain_p0);
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u62)(tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA typ_p0);
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u64)(tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg p_p0);
N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo__pureZnativesockets_u250)(NimStringV2 address_p0, NU16 port_p1, struct addrinfo hints_p2);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, dollar___systemZdollars_u49)(NU16 xX60gensym7__p0);
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0);
N_LIB_PRIVATE N_NOINLINE(void, raiseOSError__stdZoserrors_u119)(NI32 errorCode_p0, NimStringV2 additionalInfo_p1);
N_LIB_PRIVATE N_NIMCALL(NI32, osLastError__stdZoserrors_u122)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringV2, cstrToNimstr)(NCSTRING str_p0);
N_LIB_PRIVATE N_NOCONV(void, deallocShared)(void* p_p0);
static N_INLINE(tyObject_Option__HkGQcSC59b0olZFJtIthLew, some__pureZnativesockets_u77)(tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw val_p0);
static N_INLINE(tyObject_Option__HkGQcSC59b0olZFJtIthLew, none__pureZnativesockets_u131)(void);
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket__pureZnativesockets_u228)(int domain_p0, int sockType_p1, int protocol_p2, NIM_BOOL inheritable_p3);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i_p0, NI64 a_p1, NI64 b_p2);
N_NIMCALL(NimStringV2, mnewString)(NI len_p0);
static N_INLINE(NIM_BOOL, eqeq___system_u8846)(NCSTRING x_p0, NCSTRING y_p1);
N_LIB_PRIVATE N_NOINLINE(void, raiseIndexError2)(NI i_p0, NI n_p1);
N_LIB_PRIVATE N_NIMCALL(void, setSlice__stdZstrbasics_u76)(NimStringV2* s_p0, tyObject_HSlice__AztZM0sPNheK229at11oVrA slice_p1);
static N_INLINE(tyObject_HSlice__AztZM0sPNheK229at11oVrA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1);
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0);
N_LIB_PRIVATE N_NIMCALL(void, setLengthStrV2)(NimStringV2* s_p0, NI newLen_p1);
N_LIB_PRIVATE N_NIMCALL(void*, nimNewObj)(NI size_p0, NI alignment_p1);
N_LIB_PRIVATE N_NIMCALL(void, raiseExceptionEx)(Exception* e_p0, NCSTRING ename_p1, NCSTRING procname_p2, NCSTRING filename_p3, NI line_p4);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static const struct {
  NI cap; NIM_CHAR data[0+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2 = { 0 | NIM_STRLIT_FLAG, "" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_3 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_4 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_5 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_6 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_7 = {0, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_2};
static const struct {
  NI cap; NIM_CHAR data[4+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_9 = { 4 | NIM_STRLIT_FLAG, "unix" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_10 = {4, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_9};
extern TNimTypeV2 NTIv2__un52JTBmoza9c5jeMMMbgbQ_;
static const struct {
  NI cap; NIM_CHAR data[38+1];
} TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11 = { 38 | NIM_STRLIT_FLAG, "Unknown socket family in getAddrString" };
static const NimStringV2 TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12 = {38, (NimStrPayload*)&TM__f9bP3LqjpgpB9cXL8Nnak7tQ_11};
N_LIB_PRIVATE NIM_CONST int osInvalidSocket__pureZnativesockets_u48 = ((int)-1);
N_LIB_PRIVATE int nativeAfInet__pureZnativesockets_u49;
N_LIB_PRIVATE int nativeAfInet6__pureZnativesockets_u50;
N_LIB_PRIVATE int nativeAfUnix__pureZnativesockets_u51;
extern NIM_THREADVAR NIM_BOOL nimInErrorMode__system_u4407;
extern NIM_THREADVAR TFrame* framePtr__system_u2725;
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (&nimInErrorMode__system_u4407);
	return result;
}
static N_INLINE(void, nimFrame)(TFrame* s_p0) {
	{
		if (!(framePtr__system_u2725 == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s_p0).calldepth = ((NI16)0);
	}
	goto LA1_;
LA3_: ;
	{
		(*s_p0).calldepth = (NI16)((*framePtr__system_u2725).calldepth + ((NI16)1));
	}
LA1_: ;
	(*s_p0).prev = framePtr__system_u2725;
	framePtr__system_u2725 = s_p0;
	{
		if (!((*s_p0).calldepth == ((NI16)2000))) goto LA8_;
		callDepthLimitReached__system_u4625();
	}
LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__system_u2725 = (*framePtr__system_u2725).prev;
}
static N_INLINE(NIM_BOOL, setInheritable__pureZnativesockets_u206)(int s_p0, NIM_BOOL inheritable_p1) {
	NIM_BOOL result;
NIM_BOOL* nimErr_;
	nimfr_("setInheritable", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	result = (NIM_BOOL)0;
	nimlf_(237, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");	nimln_(242);	result = setInheritable__stdZsyncio_u286(((int) (s_p0)), inheritable_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, close__pureZnativesockets_u201)(int socket_p0) {
	int T1_;
	nimfr_("close", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	nimln_(231);	T1_ = (int)0;
	T1_ = close(socket_p0);
	(void)(T1_);
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket__pureZnativesockets_u228)(int domain_p0, int sockType_p1, int protocol_p2, NIM_BOOL inheritable_p3) {
	int result;
	int sockType_2;
NIM_BOOL* nimErr_;
	nimfr_("createNativeSocket", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(253);	sockType_2 = sockType_p1;
	nimln_(258);	result = socket(domain_p0, sockType_2, protocol_p2);
	nimln_(260);	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = setInheritable__pureZnativesockets_u206(result, inheritable_p3);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		if (!!(T3_)) goto LA4_;
		nimln_(261);		close__pureZnativesockets_u201(result);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		nimln_(262);		nimln_(244);		nimln_(262);		result = osInvalidSocket__pureZnativesockets_u48;
		goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA, toSockType__pureZnativesockets_u147)(tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg protocol_p0) {
	tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA result;
	tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA colontmpD_;
	tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA colontmpD__2;
	tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA colontmpD__3;
	nimfr_("toSockType", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	colontmpD_ = (tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)0;
	colontmpD__2 = (tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)0;
	colontmpD__3 = (tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)0;
	nimln_(206);	switch (protocol_p0) {
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)6):
	{
		nimln_(208);		colontmpD_ = ((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)1);
		result = colontmpD_;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)17):
	{
		nimln_(210);		colontmpD__2 = ((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)2);
		result = colontmpD__2;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)18):
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)19):
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)20):
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)21):
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)22):
	{
		nimln_(212);		colontmpD__3 = ((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)3);
		result = colontmpD__3;
	}
	break;
	default: __builtin_unreachable();
	}
	popFrame();
	return result;
}
static N_INLINE(void, nimSetMem__systemZmemory_u7)(void* a_p0, int v_p1, NI size_p2) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memset(a_p0, v_p1, ((size_t) (size_p2)));
}
static N_INLINE(void, nimZeroMem)(void* p_p0, NI size_p1) {
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	nimSetMem__systemZmemory_u7(p_p0, ((int)0), size_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u60)(tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw domain_p0) {
	int result;
	nimfr_("toInt", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	nimln_(141);	switch (domain_p0) {
	case ((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)0):
	{
		nimln_(142);		result = AF_UNSPEC;
	}
	break;
	case ((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)1):
	{
		nimln_(143);		result = AF_UNIX;
	}
	break;
	case ((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)2):
	{
		nimln_(144);		result = AF_INET;
	}
	break;
	case ((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)30):
	{
		nimln_(145);		result = AF_INET6;
	}
	break;
	default: __builtin_unreachable();
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u62)(tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA typ_p0) {
	int result;
	nimfr_("toInt", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	nimln_(157);	switch (typ_p0) {
	case ((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)1):
	{
		nimln_(158);		result = SOCK_STREAM;
	}
	break;
	case ((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)2):
	{
		nimln_(159);		result = SOCK_DGRAM;
	}
	break;
	case ((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)5):
	{
		nimln_(160);		result = SOCK_SEQPACKET;
	}
	break;
	case ((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)3):
	{
		nimln_(161);		result = SOCK_RAW;
	}
	break;
	default: __builtin_unreachable();
	}
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, toInt__pureZnativesockets_u64)(tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg p_p0) {
	int result;
	nimfr_("toInt", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	nimln_(164);	switch (p_p0) {
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)6):
	{
		nimln_(165);		result = IPPROTO_TCP;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)17):
	{
		nimln_(166);		result = IPPROTO_UDP;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)18):
	{
		nimln_(167);		result = IPPROTO_IP;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)19):
	{
		nimln_(168);		result = IPPROTO_IPV6;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)20):
	{
		nimln_(169);		result = IPPROTO_RAW;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)21):
	{
		nimln_(170);		result = IPPROTO_ICMP;
	}
	break;
	case ((tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg)22):
	{
		nimln_(171);		result = IPPROTO_ICMPV6;
	}
	break;
	default: __builtin_unreachable();
	}
	popFrame();
	return result;
}
static N_INLINE(NCSTRING, nimToCStringConv)(NimStringV2 s_p0) {
	NCSTRING result;
	{
		if (!(s_p0.len == ((NI)0))) goto LA3_;
		result = "";
	}
	goto LA1_;
LA3_: ;
	{
		result = ((NCSTRING) ((*s_p0.p).data));
	}
LA1_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo__pureZnativesockets_u250)(NimStringV2 address_p0, NU16 port_p1, struct addrinfo hints_p2) {
	struct addrinfo* result;
	NimStringV2 socketPort_1;
	NimStringV2 T2_;
	int gaiResult_1;
NIM_BOOL* nimErr_;
	nimfr_("getAddrInfo", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	result = (struct addrinfo*)0;
	socketPort_1.len = 0; socketPort_1.p = NIM_NIL;
	nimln_(292);	result = ((struct addrinfo*) NIM_NIL);
	T2_.len = 0; T2_.p = NIM_NIL;
	nimln_(293);	{
		int T5_;
		T5_ = (int)0;
		T5_ = toInt__pureZnativesockets_u62(((tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA)3));
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
		if (!(hints_p2.ai_socktype == T5_)) goto LA6_;
		socketPort_1 = TM__f9bP3LqjpgpB9cXL8Nnak7tQ_3;
	}
	goto LA3_;
LA6_: ;
	{
		socketPort_1 = dollar___systemZdollars_u49(port_p1);
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA3_: ;
	nimln_(294);	gaiResult_1 = getaddrinfo(nimToCStringConv(address_p0), nimToCStringConv(socketPort_1), (&hints_p2), &result);
	nimln_(295);	{
		NimStringV2 colontmpD_;
		NI32 T14_;
		NCSTRING T15_;
		if (!!((gaiResult_1 == ((NI32)0)))) goto LA11_;
		colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
		nimln_(299);		T14_ = (NI32)0;
		T14_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		T15_ = (NCSTRING)0;
		T15_ = (char *)gai_strerror(gaiResult_1);
		colontmpD_ = cstrToNimstr(T15_);
		raiseOSError__stdZoserrors_u119(T14_, colontmpD_);
		if (NIM_UNLIKELY(*nimErr_)) goto LA13_;
		{
			LA13_:;
		}
		{
			nimlf_(394, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");			if (colontmpD_.p && !(colontmpD_.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(colontmpD_.p);
}
		}
		if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	}
LA11_: ;
	{
		LA1_:;
	}
	{
		if (socketPort_1.p && !(socketPort_1.p->cap & NIM_STRLIT_FLAG)) {
 deallocShared(socketPort_1.p);
}
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(struct addrinfo*, getAddrInfo__pureZnativesockets_u276)(NimStringV2 address_p0, NU16 port_p1, tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw domain_p2, tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA sockType_p3, tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg protocol_p4) {
	struct addrinfo* result;
	struct addrinfo hints_1;
NIM_BOOL* nimErr_;
	nimfr_("getAddrInfo", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	result = (struct addrinfo*)0;
	nimlf_(307, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");	nimZeroMem((void*)(&hints_1), sizeof(struct addrinfo));
	nimln_(308);	hints_1.ai_family = toInt__pureZnativesockets_u60(domain_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(309);	hints_1.ai_socktype = toInt__pureZnativesockets_u62(sockType_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(310);	hints_1.ai_protocol = toInt__pureZnativesockets_u64(protocol_p4);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	nimln_(319);	{
		if (!(domain_p2 == ((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)30))) goto LA3_;
		nimln_(320);		hints_1.ai_flags = AI_V4MAPPED;
	}
LA3_: ;
	nimln_(321);	result = getAddrInfo__pureZnativesockets_u250(address_p0, port_p1, hints_1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_Option__HkGQcSC59b0olZFJtIthLew, some__pureZnativesockets_u77)(tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw val_p0) {
	tyObject_Option__HkGQcSC59b0olZFJtIthLew result;
	nimfr_("some", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/options.nim");
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	nimlf_(142, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/options.nim");	result.has = NIM_TRUE;
	result.val = val_p0;
	popFrame();
	return result;
}
static N_INLINE(tyObject_Option__HkGQcSC59b0olZFJtIthLew, none__pureZnativesockets_u131)(void) {
	tyObject_Option__HkGQcSC59b0olZFJtIthLew result;
	nimfr_("none", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/options.nim");
	nimln_(155);	nimZeroMem((void*)(&result), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(tyObject_Option__HkGQcSC59b0olZFJtIthLew, toKnownDomain__pureZnativesockets_u69)(int family_p0) {
	tyObject_Option__HkGQcSC59b0olZFJtIthLew result;
	tyObject_Option__HkGQcSC59b0olZFJtIthLew colontmpD_;
	tyObject_Option__HkGQcSC59b0olZFJtIthLew colontmpD__2;
	tyObject_Option__HkGQcSC59b0olZFJtIthLew colontmpD__3;
	tyObject_Option__HkGQcSC59b0olZFJtIthLew colontmpD__4;
	tyObject_Option__HkGQcSC59b0olZFJtIthLew colontmpD__5;
NIM_BOOL* nimErr_;
	nimfr_("toKnownDomain", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	nimZeroMem((void*)(&result), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	nimZeroMem((void*)(&colontmpD_), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	nimZeroMem((void*)(&colontmpD__2), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	nimZeroMem((void*)(&colontmpD__3), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	nimZeroMem((void*)(&colontmpD__4), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	nimZeroMem((void*)(&colontmpD__5), sizeof(tyObject_Option__HkGQcSC59b0olZFJtIthLew));
	nimlf_(150, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");	{
		if (!(family_p0 == AF_UNSPEC)) goto LA3_;
		colontmpD_ = some__pureZnativesockets_u77(((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)0));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD_;
	}
	goto LA1_;
LA3_: ;
	{
		nimln_(151);		if (!(family_p0 == AF_UNIX)) goto LA6_;
		colontmpD__2 = some__pureZnativesockets_u77(((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)1));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__2;
	}
	goto LA1_;
LA6_: ;
	{
		nimln_(152);		if (!(family_p0 == AF_INET)) goto LA9_;
		colontmpD__3 = some__pureZnativesockets_u77(((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)2));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__3;
	}
	goto LA1_;
LA9_: ;
	{
		nimln_(153);		if (!(family_p0 == AF_INET6)) goto LA12_;
		colontmpD__4 = some__pureZnativesockets_u77(((tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw)30));
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__4;
	}
	goto LA1_;
LA12_: ;
	{
		nimln_(154);		colontmpD__5 = none__pureZnativesockets_u131();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		result = colontmpD__5;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, createNativeSocket__pureZnativesockets_u235)(tyEnum_Domain__pf6i9aoKOoZII7FPrsGYBpw domain_p0, tyEnum_SockType__o4O6Zdu6tGA9cLVMS7uz4MA sockType_p1, tyEnum_Protocol__4HsnnZvHJtJ33FAHpv9bMkg protocol_p2, NIM_BOOL inheritable_p3) {
	int result;
	int T1_;
	int T2_;
	int T3_;
NIM_BOOL* nimErr_;
	nimfr_("createNativeSocket", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	result = (int)0;
	nimln_(268);	nimln_(272);	T1_ = (int)0;
	T1_ = toInt__pureZnativesockets_u60(domain_p0);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T2_ = (int)0;
	T2_ = toInt__pureZnativesockets_u62(sockType_p1);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	T3_ = (int)0;
	T3_ = toInt__pureZnativesockets_u64(protocol_p2);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	result = createNativeSocket__pureZnativesockets_u228(T1_, T2_, T3_, inheritable_p3);
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, setSockOptInt__pureZnativesockets_u997)(int socket_p0, NI level_p1, NI optname_p2, NI optval_p3) {
	int value_1;
NIM_BOOL* nimErr_;
	nimfr_("setSockOptInt", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(766);	if ((optval_p3) < ((int)(-2147483647 -1)) || (optval_p3) > ((int)2147483647)){ raiseRangeErrorI(optval_p3, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
	}
	value_1 = ((int) (optval_p3));
	nimln_(767);	{
		int T3_;
		NI32 T6_;
		nimln_(768);		nimln_(767);		if ((level_p1) < ((int)(-2147483647 -1)) || (level_p1) > ((int)2147483647)){ raiseRangeErrorI(level_p1, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
		}
		if ((optname_p2) < ((int)(-2147483647 -1)) || (optname_p2) > ((int)2147483647)){ raiseRangeErrorI(optname_p2, ((int)(-2147483647 -1)), ((int)2147483647)); goto BeforeRet_;
		}
		T3_ = (int)0;
		T3_ = setsockopt(socket_p0, ((int) (level_p1)), ((int) (optname_p2)), ((void*) ((&value_1))), ((socklen_t)4));
		if (!(T3_ < ((NI32)0))) goto LA4_;
		nimln_(769);		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T6_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_4);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
LA4_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(void, setBlocking__pureZnativesockets_u1003)(int s_p0, NIM_BOOL blocking_p1) {
	NI x_1;
	int T1_;
NIM_BOOL* nimErr_;
	nimfr_("setBlocking", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	nimln_(780);	T1_ = (int)0;
	T1_ = fcntl(s_p0, F_GETFL, ((NI)0));
	x_1 = ((NI) (T1_));
	nimln_(781);	{
		NI32 T6_;
		if (!(x_1 == ((NI)-1))) goto LA4_;
		nimln_(782);		T6_ = (NI32)0;
		T6_ = osLastError__stdZoserrors_u122();
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		raiseOSError__stdZoserrors_u119(T6_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_5);
		if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}
	goto LA2_;
LA4_: ;
	{
		NI colontmpD_;
		NI colontmpD__2;
		NI mode_1;
		colontmpD_ = (NI)0;
		colontmpD__2 = (NI)0;
		nimln_(784);		{
			if (!blocking_p1) goto LA10_;
			colontmpD_ = (NI)(x_1 & ((NI) ((NI32)((NU32) ~(O_NONBLOCK)))));
			mode_1 = colontmpD_;
		}
		goto LA8_;
LA10_: ;
		{
			colontmpD__2 = (NI)(x_1 | ((NI) (O_NONBLOCK)));
			mode_1 = colontmpD__2;
		}
LA8_: ;
		nimln_(785);		{
			int T15_;
			NI32 T18_;
			T15_ = (int)0;
			T15_ = fcntl(s_p0, F_SETFL, mode_1);
			if (!(T15_ == ((NI32)-1))) goto LA16_;
			nimln_(786);			T18_ = (NI32)0;
			T18_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			raiseOSError__stdZoserrors_u119(T18_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_6);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA16_: ;
	}
LA2_: ;
	}BeforeRet_: ;
	popFrame();
}
N_LIB_PRIVATE N_NIMCALL(int, bindAddr__pureZnativesockets_u241)(int socket_p0, struct sockaddr* name_p1, socklen_t namelen_p2) {
	int result;
	nimfr_("bindAddr", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	nimln_(276);	result = bind(socket_p0, name_p1, namelen_p2);
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(int, listen__pureZnativesockets_u246)(int socket_p0, int backlog_p1) {
	int result;
	nimfr_("listen", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	nimln_(286);	result = listen(socket_p0, backlog_p1);
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, eqeq___system_u8846)(NCSTRING x_p0, NCSTRING y_p1) {
	NIM_BOOL result;
	nimfr_("==", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");
	nimlf_(2747, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");	{
		if (!(((void*) (x_p0)) == ((void*) (y_p1)))) goto LA3_;
		result = NIM_TRUE;
	}
	goto LA1_;
LA3_: ;
	{
		NIM_BOOL T6_;
		nimln_(2748);		T6_ = (NIM_BOOL)0;
		T6_ = (((void*) (x_p0)) == NIM_NIL);
		if (T6_) goto LA7_;
		T6_ = (((void*) (y_p1)) == NIM_NIL);
LA7_: ;
		if (!T6_) goto LA8_;
		result = NIM_FALSE;
	}
	goto LA1_;
LA8_: ;
	{
		int T11_;
		nimln_(2749);		T11_ = (int)0;
		T11_ = strcmp(x_p0, y_p1);
		result = (T11_ == ((NI32)0));
	}
LA1_: ;
	popFrame();
	return result;
}
static N_INLINE(tyObject_HSlice__AztZM0sPNheK229at11oVrA, dotdot___stdZstrbasics_u48)(NI a_p0, NI b_p1) {
	tyObject_HSlice__AztZM0sPNheK229at11oVrA result;
	nimfr_("..", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system.nim");
	nimln_(436);	result.a = a_p0;
	result.b = b_p1;
	popFrame();
	return result;
}
static N_INLINE(NIM_BOOL, nimSubInt)(NI a_p0, NI b_p1, NI* res_p2) {
	NIM_BOOL result;
	NI r_1;
	result = (NIM_BOOL)0;
	r_1 = ((NI) ((NU)((NU64)(((NU) (a_p0))) - (NU64)(((NU) (b_p1))))));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI)0) <= (NI)(r_1 ^ a_p0));
		if (T3_) goto LA4_;
		T3_ = (((NI)0) <= (NI)(r_1 ^ (NI)((NU64) ~(b_p1))));
LA4_: ;
		if (!T3_) goto LA5_;
		(*res_p2) = r_1;
	}
	goto LA1_;
LA5_: ;
	{
		result = NIM_TRUE;
	}
LA1_: ;
	return result;
}
static N_INLINE(NI, nimCStrLen)(NCSTRING a_p0) {
	NI result;
	size_t T5_;
{	result = (NI)0;
	{
		if (!(a_p0 == 0)) goto LA3_;
		result = ((NI)0);
		goto BeforeRet_;
	}
LA3_: ;
	T5_ = (size_t)0;
	T5_ = strlen(a_p0);
	result = ((NI) (T5_));
	}BeforeRet_: ;
	return result;
}
N_LIB_PRIVATE N_NIMCALL(NimStringV2, getAddrString__pureZnativesockets_u768)(struct sockaddr* sockAddr_p0) {
	NimStringV2 result;
NIM_BOOL* nimErr_;
	nimfr_("getAddrString", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
{nimErr_ = nimErrorFlag();
	result.len = 0; result.p = NIM_NIL;
	nimlf_(524, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");	{
		NCSTRING T5_;
		if (!(((int) ((*sockAddr_p0).sa_family)) == nativeAfInet__pureZnativesockets_u49)) goto LA3_;
		nimln_(525);		T5_ = (NCSTRING)0;
		T5_ = inet_ntoa((*((struct sockaddr_in*) (sockAddr_p0))).sin_addr);
		result = cstrToNimstr(T5_);
	}
	goto LA1_;
LA3_: ;
	{
		NI addrLen_1;
		struct in6_addr* addr6_1;
		nimln_(526);		if (!(((int) ((*sockAddr_p0).sa_family)) == nativeAfInet6__pureZnativesockets_u50)) goto LA7_;
		nimln_(527);		addrLen_1 = ((NI) (INET6_ADDRSTRLEN));
		nimln_(529);		if ((addrLen_1) < ((NI)0) || (addrLen_1) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(addrLen_1, ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		result = mnewString((addrLen_1));
		nimln_(530);		addr6_1 = (&(*((struct sockaddr_in6*) (sockAddr_p0))).sin6_addr);
		nimln_(532);		{
			NCSTRING T11_;
			NIM_BOOL T12_;
			NI32 T15_;
			nimln_(533);			nimln_(532);			if (((NI)0) < 0 || ((NI)0) >= result.len){ raiseIndexError2(((NI)0),result.len-1); goto BeforeRet_;
			}
			nimln_(533);			if ((result.len) < ((NI32)(-2147483647 -1)) || (result.len) > ((NI32)2147483647)){ raiseRangeErrorI(result.len, ((NI32)(-2147483647 -1)), ((NI32)2147483647)); goto BeforeRet_;
			}
			nimln_(532);			T11_ = (NCSTRING)0;
			T11_ = (char *)inet_ntop(AF_INET6, addr6_1, ((NCSTRING) ((&result.p->data[((NI)0)]))), ((NI32) (result.len)));
			nimln_(533);			T12_ = (NIM_BOOL)0;
			T12_ = eqeq___system_u8846(T11_, ((NCSTRING) NIM_NIL));
			if (!T12_) goto LA13_;
			nimln_(534);			T15_ = (NI32)0;
			T15_ = osLastError__stdZoserrors_u122();
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
			raiseOSError__stdZoserrors_u119(T15_, TM__f9bP3LqjpgpB9cXL8Nnak7tQ_7);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA13_: ;
		nimln_(535);		{
			int T18_;
			NI TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8;
			tyObject_HSlice__AztZM0sPNheK229at11oVrA T21_;
			T18_ = (int)0;
			T18_ = IN6_IS_ADDR_V4MAPPED(addr6_1);
			if (!!((T18_ == ((NI32)0)))) goto LA19_;
			nimln_(536);			nimlf_(53, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/system/indices.nim");			if (nimSubInt(addrLen_1, ((NI)1), &TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8)) { raiseOverflow(); goto BeforeRet_;
			};
			nimlf_(536, "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");			T21_ = dotdot___stdZstrbasics_u48(((NI)7), (NI)(TM__f9bP3LqjpgpB9cXL8Nnak7tQ_8));
			setSlice__stdZstrbasics_u76((&result), T21_);
			if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
		}
LA19_: ;
		nimln_(541);		if ((nimCStrLen(nimToCStringConv(result))) < ((NI)0) || (nimCStrLen(nimToCStringConv(result))) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(nimCStrLen(nimToCStringConv(result)), ((NI)0), ((NI)IL64(9223372036854775807))); goto BeforeRet_;
		}
		setLengthStrV2((&result), (nimCStrLen(nimToCStringConv(result))));
	}
	goto LA1_;
LA7_: ;
	{
		tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ* T27_;
		nimln_(544);		{
			if (!(((int) ((*sockAddr_p0).sa_family)) == nativeAfUnix__pureZnativesockets_u51)) goto LA25_;
			nimln_(545);			nimln_(522);			nimln_(545);			result = TM__f9bP3LqjpgpB9cXL8Nnak7tQ_10;
			goto BeforeRet_;
		}
LA25_: ;
		T27_ = NIM_NIL;
		T27_ = (tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ*) nimNewObj(sizeof(tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ), NIM_ALIGNOF(tyObject_IOError__un52JTBmoza9c5jeMMMbgbQ));
		(*T27_).Sup.Sup.Sup.m_type = (&NTIv2__un52JTBmoza9c5jeMMMbgbQ_);
		(*T27_).Sup.Sup.name = "IOError";
		(*T27_).Sup.Sup.message = TM__f9bP3LqjpgpB9cXL8Nnak7tQ_12;
		(*T27_).Sup.Sup.parent = ((Exception*) NIM_NIL);
		nimln_(546);		raiseExceptionEx((Exception*)T27_, "IOError", "getAddrString", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim", 546);
goto BeforeRet_;
	}
LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}
N_LIB_PRIVATE N_NIMCALL(void, atpnativesocketsdotnim_Init000)(void) {
{
	nimfr_("nativesockets", "/Users/gcao/.nimble/pkgs2/nim-2.2.6-2c9e77a691294dad7472a539f9b78ef0088a1a87/lib/pure/nativesockets.nim");
	nimln_(120);	nativeAfInet__pureZnativesockets_u49 = AF_INET;
	nimln_(121);	nativeAfInet6__pureZnativesockets_u50 = AF_INET6;
	nimln_(122);	nativeAfUnix__pureZnativesockets_u51 = AF_UNIX;
	nimTestErrorFlag();
	popFrame();
}
}

